### PR TITLE
Fix agent shutdown on SIGINT

### LINKED ISSUE #995: V2: Agent doesn't stop cleanly on SIGINT
Agent doesn't stop cleanly on SIGINT.
Running off of the latest V2 branch:
https://github.com/elastic/elastic-agent/tree/feature-arch-v2

Steps to reproduce:
1. Enroll the agent from the command line
2. Run the agent from the command line
3. Press Ctrl+C, observe the agent doesn't exist requires SIGKILL for each of the running processes.

### LINKED ISSUE #996: V2: Agent policy change is not applied properly and requires agent restart
Agent doesn't apply configuration change properly.
Running off of the latest V2 branch:
https://github.com/elastic/elastic-agent/tree/feature-arch-v2

Steps to reproduce:
1. Enroll the agent from the command line
2. Run the agent from the command line
3. Update the policy. In this particular case was playing with osquery_manager configuration. The agent restart is required in order to get the configuration reloaded properly.

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Fix the agent shutdown on SIGINT.

1. There was an issue with the "destroy" call that gets blocked forever on the watch channel due to circular nature of the code. The componentRuntimeState "watch" loop was calling "manager" stateChanged, that was calling back the componentRuntimeState "destroy" method that was blocking on the "watchChan" waiting on the "watch" loop to exit. And that watchChan is only closed upon the exit from that "watch" loop which never happens cause the call is blocked at the 
```state.manager.stateChanged(state, s)```

```
goroutine 129 [chan receive, 18 minutes]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).destroy(0xc000580a80)
	/Users/amaus/elastic/elastic-agent/pkg/component/runtime/runtime.go:179 +0xf8
github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).stateChanged(0xc0001c9200, 0xc000580a80, {0x6, {0x1103d24bb, 0x23}, 0xc000e88120, {{0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/Users/amaus/elastic/elastic-agent/pkg/component/runtime/manager.go:624 +0x485
github.com/elastic/elastic-agent/pkg/component/runtime.newComponentRuntimeState.func1()
	/Users/amaus/elastic/elastic-agent/pkg/component/runtime/runtime.go:131 +0x4b8
created by github.com/elastic/elastic-agent/pkg/component/runtime.newComponentRuntimeState
	/Users/amaus/elastic/elastic-agent/pkg/component/runtime/runtime.go:121 +0x736  
```

2. There is a general issue in few places with the data that was attempted to be sent to the unbuffered channels after the loops reading from these channels already exited upon context cancel. This causes blocks on send and the goroutines leak.
Dumping ```goroutines``` with pprof after SIGINT showed many goroutines stuck on sending to to chans. Depending on the goroutines scheduling during the run and shutdown sequence you could get different results and different blocking points. 

For example:
```
goroutine 132 [chan receive, 18 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.(*managedConfigManager).Run(0xc00070f800, {0x110a147e0, 0xc0005b2040})
	/Users/amaus/elastic/elastic-agent/internal/pkg/agent/application/managed_mode.go:210 +0x1271
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner.func2({0x118e7adf8, 0xc00070f800})
	/Users/amaus/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:324 +0x62
created by github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner
	/Users/amaus/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:323 +0x4d4

goroutine 133 [chan send, 18 minutes]:
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner.func3({0x118e7ae20, 0xc000c78930})
	/Users/amaus/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:335 +0x99
created by github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner
	/Users/amaus/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:332 +0x6d4 
```

After a bit of digging, I changed the channels that caused the blocking (found via pprof goroutines dumps) to the buffered channels in order to fix the shutdown on SIGINT. It looks like if there was an assumption that no data will be send to the channels after loops stopped serving them, it is not valid. One way to unblock these calls is to make the channels buffered.
I don't have the full confidence that there are no other possible cases with unbuffered channels that can block and leak goroutines at the moment. It's very difficult to figure out shutdown sequence without adding bunch more logs.

@blakerouse why the agent uses unbuffered channels everywhere in the first place?
is there any attempt to guarantee the orderly shutdown that would not block on channels that I might have missed in the current code? should the agent switch to buffered channels and what would be the implications for the current implementation?
could you review the changes since you are more familiar with the runtime code details? 

## Why is it important?

Currently the agent doesn't shutdown on SIGINT and is needed to be SIGKILLed, reproducible 99% of times on my Mac dev environment.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

Closes #995 
Closes #996

### CODE REVIEW

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 1]
```diff
@@ -328,7 +328,7 @@ func (c *Coordinator) runner(ctx context.Context) error {
 
 	varsWatcher := c.varsMgr
 	varsRun := make(chan bool)
-	varsErrCh := make(chan error)
+	varsErrCh := make(chan error, 1)
```
Comment (blakerouse) [inline internal/pkg/agent/application/coordinator/coordinator.go:331]: Can you explain to me why this is needed? The `select/case` reads from all these channels, so why would an unbuffered channel be needed here?

File: internal/pkg/agent/application/gateway/fleet/fleet_gateway.go [hunk 2]
```diff
@@ -124,7 +124,7 @@ func newFleetGatewayWithScheduler(
 		acker:        acker,
 		stateFetcher: stateFetcher,
 		stateStore:   stateStore,
-		errCh:        make(chan error),
+		errCh:        make(chan error, 1),
```
Comment (blakerouse) [inline internal/pkg/agent/application/gateway/fleet/fleet_gateway.go:127]: Same here? The `Errors()` should be watched by the coordinator, so why does this need to be changed to buffered. What is causing this to be blocking unless you make it buffered.

File: pkg/component/runtime/runtime_comm.go [hunk 3]
```diff
@@ -83,7 +83,7 @@ func newRuntimeComm(logger *logger.Logger, listenAddr string, ca *authority.Cert
 		token:           token.String(),
 		cert:            pair,
 		checkinConn:     true,
-		checkinExpected: make(chan *proto.CheckinExpected),
+		checkinExpected: make(chan *proto.CheckinExpected, 1),
```
Comment (blakerouse) [inline pkg/component/runtime/runtime_comm.go:86]: Why the change here? I would prefer to not buffer expected configurations.

File: pkg/component/runtime/runtime.go [hunk 4]
```diff
@@ -176,7 +176,10 @@ func (s *componentRuntimeState) destroy() {
 	if s.watchCanceller != nil {
 		s.watchCanceller()
 		s.watchCanceller = nil
-		<-s.watchChan
+		// Do not wait on watchChan here
+		// the watch loop calls stateChanged that calls "destroy" (this function) and will block forever
+		// since the watch channel will never be closed because the watch loop is blocked on stateChanged call
+		// <-s.watchChan
```
Comment (blakerouse) [inline pkg/component/runtime/runtime.go:182]: I think we need to ensure that we wait for the watcher goroutine does stop. This seems like a hacky way of fixing it, by just commenting it out.

Maybe we could use a different channel to know when its done? Or a waitgroup?

**Review by blakerouse — COMMENTED** [review]
I do not like buffered channels. The use of buffered channels normally means something wrong is being done.

**Comment by aleksmaus** [comment]
> I do not like buffered channels. The use of buffered channels normally means something wrong is being done.

https://github.com/golang/go/blob/master/src/time/sleep.go#L87

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 1 above)
Comment (aleksmaus) [reply internal/pkg/agent/application/coordinator/coordinator.go:331]: All the places where the unbuffered channels were changed to buffered are the channels that were blocking on shutdown. So it was either something was writing to that channel that nothing was reading from (exited read loop before the writers were fully stopped) or reading from the channel that nothing was writing to.
This fix is not ideal, I understand. Might have to fix more code in order to avoid buffered channels then.

Comment (michalpristas) [reply internal/pkg/agent/application/coordinator/coordinator.go:331]: we should aim on fixing the real issue not the symptom. 
however if we agree that this is sufficient for now add a TODO there at least and create an issue. otherwise we're creating technical debt which we will probably never deal with

File: pkg/component/runtime/runtime_comm.go (hunk 3 above)
Comment (aleksmaus) [reply pkg/component/runtime/runtime_comm.go:86]: so for this one the "command" runtime sends "CheckinExpected" while the beat for example failed to connect over gRPC and the V2 checkin call from the client is never called.
So this loop that reads from the unbuffered channel was never run
https://github.com/elastic/elastic-agent/blob/feature-arch-v2/pkg/component/runtime/runtime_comm.go#L184

and the CheckinExpected called from the "command" runtime is blocked forever until the components comes online and kicks off the "check-in" sequence.


We can either:
1. cache the latest "CheckinExpected" state until the component checks in over GRPs so we can send something back, or 
2. drop it on a floor, loosing some state that we suppose to synchronize on.
Think would have to redo the comms to keep the last state and not block on that chan

Comment (aleksmaus) [reply pkg/component/runtime/runtime_comm.go]: Pushed another commit with the change in runtime_comms to addresses this particular issue according to the explanation above, implementing the caching of the latest state in the buffered channel of size 1.
https://github.com/elastic/elastic-agent/pull/1258/commits/d5f7de05a7a2ff9396ed73ddae6ea891bd945d88

File: pkg/component/runtime/runtime.go (hunk 4 above)
Comment (aleksmaus) [reply pkg/component/runtime/runtime.go:182]: I'll rewrite how the runners are managed, it currently deadlocks on wait for this channel to be closed while it can't be closed until you return from this function.

Comment (aleksmaus) [reply pkg/component/runtime/runtime.go]: this is rewritten now, think it's cleaner

File: internal/pkg/agent/application/gateway/fleet/fleet_gateway.go (hunk 2 above)
Comment (aleksmaus) [reply internal/pkg/agent/application/gateway/fleet/fleet_gateway.go]: Fixed managed_mode coordination with fleet gateway. Now the gateway errors reading loop waits until gateway exits. Otherwise if the gateway shuts down out of sequence blocks it can block on errCh.

**Comment by aleksmaus** [comment]
I refactored and rewrote some code to fix some underlying problems with shutdown sequence. Could take another look? 
@blakerouse

File: internal/pkg/runner/runner.go [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+		cn()
+		close(r.done)
+	}()
+
+	return r
+}
+
+func (r *Runner) setError(err error) {
+	r.mx.Lock()
+	if r.err == nil {
```
Comment (michalpristas) [inline internal/pkg/runner/runner.go:76]: setting error only if nil

File: internal/pkg/agent/application/managed_mode.go [hunk 6]
```diff
@@ -182,32 +183,26 @@ func (m *managedConfigManager) Run(ctx context.Context) error {
...
-		gatewayCancel()
-		<-gatewayRun
-	}()
-	go func() {
-		err := gateway.Run(gatewayCtx)
-		close(gatewayRun)
-		gatewayErrCh <- err
-	}()
+	gatewayRunner := runner.Start(gatewayCtx, func(ctx context.Context) error {
+		defer gatewayErrorsRunner.Stop()
```
Comment (michalpristas) [inline internal/pkg/agent/application/managed_mode.go:200]: should this be `gatewayRunner.Stop()` ?

File: internal/pkg/runner/runner.go (hunk 5 above)
Comment (aleksmaus) [reply internal/pkg/runner/runner.go:76]: yeah, if it was not previously set

File: internal/pkg/runner/runner.go [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+	r.mx.Lock()
+	if r.cn != nil {
+		r.cn()
+		r.cn = nil
+	}
+	r.mx.Unlock()
+}
+
+func (r *Runner) Err() error {
+	return r.err
```
Comment (michalpristas) [inline internal/pkg/runner/runner.go:34]: should be inside lock

File: internal/pkg/agent/application/managed_mode.go (hunk 6 above)
Comment (aleksmaus) [reply internal/pkg/agent/application/managed_mode.go:200]: nope, the errors runner should be stopped only after the gateway run stopped

File: internal/pkg/runner/runner.go (hunk 7 above)
Comment (aleksmaus) [reply internal/pkg/runner/runner.go:34]: correct, will fix

File: internal/pkg/runner/runner.go [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+
+func (r *Runner) Done() <-chan struct{} {
+	return r.done
+}
+
+func (r *Runner) DoneWithTimeout(to time.Duration) <-chan struct{} {
+	done := make(chan struct{})
+
+	go func() {
+		t := time.NewTimer(to)
```
Comment (michalpristas) [inline internal/pkg/runner/runner.go:45]: would be better to initialize timer outside of goroutine and pass it as arg. 
can take some time to start a goroutine

File: internal/pkg/agent/application/managed_mode.go (hunk 6 above)
Comment (aleksmaus) [reply internal/pkg/agent/application/managed_mode.go:200]: we could and yeah, it's safe as calling context cancel multiple times

File: internal/pkg/runner/runner.go (hunk 5 above)
Comment (aleksmaus) [reply internal/pkg/runner/runner.go:81]: added a comment

**Review by blakerouse — APPROVED** [review]
Nice, thanks for the fixes.

Changes looks much better!
