### PR TITLE
Fix TestAddToBucket flakiness on Windows

### LINKED ISSUE #2146: TestAddToBucket unit tests are flaky on Windows
Example failures:
- [ ] https://github.com/elastic/elastic-agent/issues/2135
- [ ] https://github.com/elastic/elastic-agent/issues/2134
- [ ] https://github.com/elastic/elastic-agent/issues/2123

Fix the tests or justify disabling them for this platform.

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?

Some testcases insert 3 or more events in a loop to test the rate limiter.
On windows machines system clock ticks every 15ms so the loop we use to add events to the rate limiter run slower (we set the timer to 2 ms which translates to ~20 ms between iterations on windows). 
Using a timeframe of 50ms for the rate limiter makes the unit tests flaky when running on windows (there's a growing chance of the loop running for longer than that the more items we add)
This commit extends the timeframe of the rate limiter from 50ms to 150ms in such testcases to make sure that all the events we use in the unit tests are kept into account of a single timeframe.

## Why is it important?

This eliminates flakiness of unit tests run on CI.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)

## Author's Checklist

- [ ]

## How to test this PR locally

To test this we can simply run the tests for a few times (10 in the example below)
```
go test ./pkg/component/runtime -run TestAddToBucket -count 10
```

## Related issues

- Closes  #2146

### CODE REVIEW

File: pkg/component/runtime/command_test.go [hunk 1]
```diff
@@ -13,29 +13,33 @@ import (
...
+		// These testcases use a longer duration as dropRate to make sure that on Windows machine we don't drop any old events
+		"errors > than limit within timespans, off by one": {2, 150 * time.Millisecond, 3, 2 * time.Millisecond, true},
+		"errors > than limit within timespans":             {2, 150 * time.Millisecond, 4, 2 * time.Millisecond, true},
 	}
 
 	for name, tc := range testCases {
 		t.Run(name, func(t *testing.T) {
-			dropRate := 50 * time.Millisecond
-			b := newRateLimiter(dropRate, tc.bucketSize)
+
```
Comment (michalpristas) [inline pkg/component/runtime/command_test.go:34]: please remove newling

**Review by michalpristas — APPROVED** [review]
Very weird issue to debug, please remove a newline and make sure ci is green before merging

**Review by cmacknz — APPROVED** [review]
Looks good, thanks! The backport-v8.6 label here means Mergify will automatically create this same PR against the 8.6 branch once this one merges. Make sure that one gets merged as well, you won't need approvals for the backport PR.

File: pkg/component/runtime/command.go [hunk 2]
```diff
@@ -553,11 +553,11 @@ func newRateLimiter(restartMonitoringPeriod time.Duration, maxEventsPerPeriod in
 		return nil
 	}
 
-	freq := restartMonitoringPeriod.Seconds()
+	period := restartMonitoringPeriod.Seconds()
```
Comment (amitkanfer) [inline pkg/component/runtime/command.go:556]: Seconds() cannot return 0 by any chance, right?

Comment (cmacknz) [reply pkg/component/runtime/command.go:556]: It can if `restartMonitoringPeriod` itself were zero, but we should be protected from this by the if conditions above:

```
if restartMonitoringPeriod <= 0 || maxEventsPerPeriod <= 0 {
		return nil
}
```

If either of the periods evaluate to zero we consider the rate limiter disabled. Perhaps worth a specific test case for either period being zero to avoid something slipping through here in the future.
