### PR TITLE
Fix/5595 force uninstall correct installation

### LINKED ISSUE #5595: `--force` ignores `--develop` and uninstalls production agent instead
When installing an development elastic-agent, using `--develop`, if it's done to override an existing development agent, using `--force`, the development agent will uninstall the production agent.

It seems the `--force` ignores the `--develop` and runs the uninstall command against the production agent. It creates two problems:
 - the develop agent uninstalls the production agent
 - if the uninstall succeeds, the install fails as the development agent hasn't been removed.

For confirmed bugs, please report:
- Version: 8.15.0, main
- Operating System: linux, mac, needs test on Windows, but it should be affected as well
- Discuss Forum URL: N/A
- Steps to Reproduce:
  - install an production agent
  - install a development agent
  - try to override the development agent: `sudo elastic-agent install -nf [...]`
  - it'll uninstall the production agent and fail:
```
root@elastic-agent:~# ./elastic-agent-8.15.0-linux-x86_64/elastic-agent install -fn --develop --url=https://fleet.elastic-cloud.com:443 --enrollment-token=a-token==
Installing into development namespace; this is an experimental and currently unsupported feature.
Installing in non-interactive mode.
[    ] Done  [39s]                                    
Elastic Agent has been uninstalled. ## <---- the production agent was uninstalled
[ ===] Error copying files  [39s] Error uninstalling. Printing logs
Error: error installing package: failed to copy source directory (data/elastic-agent-25075f) to destination (data/elastic-agent-8.15.0-25075f): open /opt/Elastic/Agent-Development/data/elastic-agent-8.15.0-25075f/components/agentbeat: text file busy # <---- the develop agent hasn't been removed
```

### PR DESCRIPTION
**Pull request by kaanyalti**
- Bug

## What does this PR do?

Updates the uninstall command so that when the development agent is installed with `--force` flag and if there is already a development agent, then the command will replace the already existing development agent

## Why is it important?

Currently force installing the development agent removes the production agent.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## How to test this PR locally

- Install the agent with and without the `--develop` flag
- Try to reinstall each agent with the `--force` flag
- Validate that the force installation replaces the correct agent
  - Development replaces development
  - Production replaces production 

## Related issues

- Closes #5595

### CODE REVIEW

**Review by jlind23 — COMMENTED** [review]
Could you please add a changelog.

File: internal/pkg/agent/cmd/install.go [hunk 1]
```diff
@@ -344,21 +346,35 @@ func installCmd(streams *cli.IOStreams, cmd *cobra.Command) error {
...
+	// Using the topPath with binaryName is feasible only because the shell wrapper (linux) does not
+	// do anything complicated aside from calling the agent binary. If this were
+	// to change, the implementation here may need to change as well.
+	binPath := filepath.Join(topPath, binName)
+	fi, err := os.Stat(binPath)
 	if err != nil {
-		return fmt.Errorf("unable to find %s on path: %w", paths.BinaryName, err)
+		if errors.Is(err, fs.ErrNotExist) {
+			return fmt.Errorf("unable to find %s on path: %w", binPath, err)
+		}
```
Comment (blakerouse) [inline internal/pkg/agent/cmd/install.go:368]: Why this specific error message for `ErrNotExist`? I think just the one below would be also acceptable.

File: internal/pkg/agent/cmd/install.go [hunk 2]
```diff
@@ -344,21 +346,35 @@ func installCmd(streams *cli.IOStreams, cmd *cobra.Command) error {
...
 		"uninstall",
 		"--force",
 	}
-	execPath, err := exec.LookPath(paths.BinaryName)
+
+	// Using the topPath with binaryName is feasible only because the shell wrapper (linux) does not
+	// do anything complicated aside from calling the agent binary. If this were
+	// to change, the implementation here may need to change as well.
+	binPath := filepath.Join(topPath, binName)
+	fi, err := os.Stat(binPath)
```
Comment (blakerouse) [inline internal/pkg/agent/cmd/install.go:364]: Do you need this check at all? Why are we making this check?

**Review by blakerouse — COMMENTED** [review]
Looks good overall, just a question before approval.

File: internal/pkg/agent/cmd/install.go (hunk 2 above)
Comment (kaanyalti) [reply internal/pkg/agent/cmd/install.go:364]: I was trying to be cautious when using the path, if the previous steps in the install process guarantee that the binpath is valid, then I can skip this.

File: internal/pkg/agent/cmd/install.go (hunk 1 above)
Comment (kaanyalti) [reply internal/pkg/agent/cmd/install.go:368]: Not needed indeed. Will update right away.
