### PR TITLE
Fix issue with `--delay-enroll` and `--unprivileged` on Windows

### LINKED ISSUE #4678: Windows agent is not available on Fleet UI on restart when installed with `--delay-enroll` and `--unprivileged`.
**Kibana Build details:**
```
VERSION: 8.14.0 BC3
BUILD: 73762
COMMIT: 2a492e1625f24336f3259b2b8df62b2b18127e81
```
Artifact Link: https://staging.elastic.co/8.14.0-7c638435/downloads/beats/elastic-agent/elastic-agent-8.14.0-windows-x86_64.zip

**Preconditions:**
1. 8.14.0-BC3 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Run agent install command with  `--delay-enroll` and `--unprivileged`.
2. Observe agent is successfully installed.
3. Restart the Windows host.
4. Observe agent is not visible on Fleet UI and the Elastic Agent service is not started.

**Note:**
Issue is consistently reproducible on multiple Windows Hosts.

**Expected Result:**
Windows agent should be available on Fleet UI on restart when installed with `--delay-enroll` and `--unprivileged`.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/15218565/logs.zip)
[logs2.zip](https://github.com/elastic/elastic-agent/files/15218569/logs2.zip)

**Screenshot:**
image

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes an issue where `--delay-enroll` with `--unprivileged` on Windows didn't allow the Elastic Agent to start. This is because the `FixPermissions` work was being skipped with delayed enrollment.

This also adjusts the integration tests for delay enrollment to work both on Linux and on Windows. Adds specific tests for delay enrollment with privileged and unprivileged mode.

## Why is it important?

To allow `--delay-enroll` to work with `--unprivileged` on Windows.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~ (integration tests added)
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Related issues

- Closes #4678

### CODE REVIEW

File: testing/integration/delay_enroll_test.go [hunk 1]
```diff
@@ -77,11 +77,69 @@ func TestDelayEnroll(t *testing.T) {
...
+
+	ctx, cancel := testcontext.WithDeadline(t, context.Background(), time.Now().Add(10*time.Minute))
+	defer cancel()
+
+	agentFixture, err := define.NewFixtureFromLocalBuild(t, define.Version())
+	require.NoError(t, err)
 
+	// 1. Create a policy in Fleet with monitoring enabled.
+	// To ensure there are no conflicts with previous test runs against
+	// the same ESS stack, we add the current time at the end of the policy
```
Comment (pchila) [inline testing/integration/delay_enroll_test.go:103]:
```suggestion
	// the same ESS stack, we add a UUID at the end of the policy
```

**Review by pchila — APPROVED** [review]
Looks good!
There's a small fix needed in code comments, not blocking

**Comment by blakerouse** [comment]
@ycombinator It already passed all the tests once, latest commit was just a nitpick from @pchila. Once ready, if you could 
force merge, as SonarQube is complaining this has no coverage. Covered in integration tests, on both Linux and Windows and in both privileged and unprivileged mode.
