### PR TITLE
Fix TestRemovePath flakiness on windows

### LINKED ISSUE #3221: [Flaky Test] TestRemovePath (internal/pkg/agent/install)
## Flaky Test

* **Test Name:** TestRemovePath (internal/pkg/agent/install).
* **Link:** [Link to file/line number in github.](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/install/uninstall_windows_test.go#L54)
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
   - https://github.com/elastic/elastic-agent/pull/3214
   - main
* **Artifact Link:** https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/PR-3214/4/pipeline/1973
* **Notes:** Perhaps the time between starting the binary and trying to remove it is, sometimes, so short windows considers other process is using it.

### Stack Trace

```
[2023-08-10T08:08:27.569Z] === Failed

[2023-08-10T08:08:27.569Z] === FAIL: internal/pkg/agent/install TestRemovePath (0.62s)

[2023-08-10T08:08:27.569Z]     uninstall_windows_test.go:54: 

[2023-08-10T08:08:27.569Z]         	Error Trace:	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall_windows_test.go:54

[2023-08-10T08:08:27.569Z]         	Error:      	Received unexpected error:

[2023-08-10T08:08:27.569Z]         	            	failed to open handle for "C:\\Users\\jenkins\\AppData\\Local\\Temp\\TestRemovePath1878842873\\001\\subdir\\main.exe": The process cannot access the file because it is being used by another process.

[2023-08-10T08:08:27.569Z]         	Test:       	TestRemovePath

[2023-08-10T08:08:27.569Z] 

```

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?

Slightly modified the `RemovePath` retry loop on windows adding another iteration after deleting a blocking executable.

## Why is it important?
We want to make sure that we can uninstall elastic-agent even if a binary is still executing within the directory but we want to avoid false positives

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Author's Checklist

- [ ]

## How to test this PR locally

Just run the test on windows (multiple times would be ideal) like:
```shell
gotestsum -- -count 1000 -v -run '^TestRemovePath$' github.com/elastic/elastic-agent/internal/pkg/agent/install/
```

## Related issues

- Closes #3221 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: internal/pkg/agent/install/uninstall.go [hunk 1]
```diff
@@ -99,27 +99,23 @@ func Uninstall(cfgFile, topPath, uninstallToken string) error {
...
 		}
 
-		if d := time.Since(start) + nextSleep; d >= arbitraryTimeout {
-			return err
+		if isBlockingOnExe(lastErr) {
+			// try to remove the blocking exe and try again to clean up the path
+			removeBlockingExe(lastErr)
 		}
+
+		time.Sleep(time.Millisecond)
```
Comment (amitkanfer) [inline internal/pkg/agent/install/uninstall.go:115]: IMHO we should sleep longer. Ignoring the time it takes to run the commands above, this line will be called 5000 times, which is a whole lot. How about 50msec?

Comment (pchila) [reply internal/pkg/agent/install/uninstall.go:115]: well before the change we were not even sleeping, we were spinning in the loop. Than can be easily inclreased... (also on windows I think the minimum clock tick is ~15 ms)

Comment (pchila) [reply internal/pkg/agent/install/uninstall.go]: Done

**Review by cmacknz — APPROVED** [review]
Looks good, but I'd add a changelog entry. If it turns out the currently released version of this code has an issue users and support will want the changelog to help know which version has the fix.

File: internal/pkg/agent/install/uninstall.go [hunk 2]
```diff
@@ -99,27 +99,23 @@ func Uninstall(cfgFile, topPath, uninstallToken string) error {
...
 		}
 
-		if d := time.Since(start) + nextSleep; d >= arbitraryTimeout {
-			return err
+		if isBlockingOnExe(lastErr) {
+			// try to remove the blocking exe and try again to clean up the path
+			_ = removeBlockingExe(lastErr)
 		}
+
+		time.Sleep(50 * time.Millisecond)
```
Comment (AndersonQ) [inline internal/pkg/agent/install/uninstall.go:115]: I think it might be too much pressure on the OS. But it's a guess. However I think a counter of how many tries happened would be good.

**Review by AndersonQ — APPROVED** [review]

File: internal/pkg/agent/install/uninstall.go (hunk 2 above)
Comment (cmacknz) [reply internal/pkg/agent/install/uninstall.go:115]: 50 milliseconds is a long time to a computer, this is an improvement over what it did before which was not sleeping.

I'd be in favour of logging how long this function took to complete so we can tell if any future flakiness is just related to marginal timing.

Comment (pchila) [reply internal/pkg/agent/install/uninstall.go:115]: https://github.com/elastic/elastic-agent/issues/3434

**Comment by pchila** [comment]
buildkite test this
