### PR TITLE
Fix lookup issues with inputs.d fragment yml

### LINKED ISSUE #663: Inputs.d usage in container environments is fuzzy
Support for external configurations under `inputs.d` was introduced with https://github.com/elastic/elastic-agent/commit/3c2072d8d2fc52d842aa301ab3a4cd1de1eb3710 . However the documentation around this is not quite helpful and it is only mentioned at https://www.elastic.co/guide/en/fleet/8.2/elastic-agent-configuration.html as `you can put input configurations in YAML files into the folder {path.config}/inputs.d`.

However this is not quite trivial to use this in container environments and even trying several different combinations didn't work.
I tried putting the `inputs.d` as `/usr/share/elastic-agent/state/inputs.d`, as `/etc/elastic-agent` when running with `-c /etc/elastic-agent/elastic.yml` and as `/usr/share/elastic-agent/inputs.d` but nothing works and logs don't provide any useful insight.

Note that Agent directory is under `/usr/share/elastic-agent`  and it is started with `-c /etc/elastic-agent/agent.yml`.

```console
cat container-paths.yml 
state_path: /usr/share/elastic-agent/state
config_path: /usr/share/elastic-agent/state
```

Find a complete k8s manifest below:
[elastic-agent-standalone-kubernetes.yaml.txt](https://github.com/elastic/elastic-agent/files/9038727/elastic-agent-standalone-kubernetes.yaml.txt)

@ph could we have some help on clarifying those please? 
cc: @gizas 

This is important for https://github.com/elastic/elastic-agent/issues/662.
Also related to https://github.com/elastic/elastic-agent/issues/622.

### PR DESCRIPTION
**Pull request by ph**
The Elastic Agent was looking next to the binary for the `inputs.d`
folder instead it should look up into the `Home` folder where
the Elastic Agent symlink is located.

Fixes: #663

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #123

### CODE REVIEW

File: internal/pkg/agent/configuration/settings.go [hunk 1]
```diff
@@ -16,7 +17,7 @@ import (
 )
 
 // ExternalInputsPattern is a glob that matches the paths of external configuration files.
-var ExternalInputsPattern = filepath.Join("inputs.d", "*.yml")
```
Comment (blakerouse) [inline internal/pkg/agent/configuration/settings.go:19]: You should not use `paths.AgentInputsDPath()` at initialization. It is possible that it will change here: https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/cmd/container.go#L852 because it calls `setPaths`.


So you should have the code path that does the searching perform the join at that point, not here in a global var.

**Review by blakerouse — CHANGES_REQUESTED** [review]

File: internal/pkg/agent/configuration/settings.go (hunk 1 above)
Comment (aleksmaus) [reply internal/pkg/agent/configuration/settings.go:19]: 👍 good catch

Comment (ph) [reply internal/pkg/agent/configuration/settings.go:19]: good catch indeed.

**Comment by ChrsMark** [comment]
@blakerouse @aleksmaus hey folks, is there any update on this? Do you plan to resume the work here? We would really need this to be fixed to unblock https://github.com/elastic/elastic-agent/issues/662 :).

**Comment by aleksmaus** [comment]
@blakerouse I'll fix it up and update this PR

**Review by blakerouse — APPROVED** [review]
Thanks for fixing it!

**Comment by ChrsMark** [comment]
Thanks @aleksmaus ! Can we also add some examples in the docs about this to make the usage clear? See https://www.elastic.co/guide/en/fleet/8.2/elastic-agent-configuration.html  and https://github.com/elastic/elastic-agent/issues/663#issue-1292985268. Thanks!

**Comment by ChrsMark** [comment]
Fetched the commits and tested again using what I mentioned at https://github.com/elastic/elastic-agent/issues/663#issuecomment-1202599356. I still cannot see the data_stream from the external configuration to collect metrics. Here is how the mounts happen inside the Pod:

```console
root@kind-control-plane:/usr/share/elastic-agent# ls /etc/elastic-agent/
agent.yml  inputs.d
root@kind-control-plane:/usr/share/elastic-agent# ls /etc/elastic-agent/inputs.d/
kubernetes.yml
```

And Agent is running as `root          13  0.9  0.2 1884312 74720 ?       Sl   10:21   0:07 elastic-agent container -c /etc/elastic-agent/agent.yml -e`.

Do you see anything wrong with my configs?

**Comment by aleksmaus** [comment]
@ChrsMark I was not familiar how this 

> And Agent is running as `root 13 0.9 0.2 1884312 74720 ? Sl 10:21 0:07 elastic-agent container -c /etc/elastic-agent/agent.yml -e`.
> 
> Do you see anything wrong with my configs?

@ChrsMark I'm not familiar with many ways the elastic-agent configuration path can be set.

Looking at the code it looks like there are few ways: 
1. ```-path.config``` command line flag https://github.com/elastic/elastic-agent/blob/64cb5a05121904c2b1f1a7b7af5227c8f56ced5a/internal/pkg/agent/application/paths/common.go#L49
2. for the ```container``` command the path seems to be derived from environment CONFIG_PATH
https://github.com/elastic/elastic-agent/blob/acc60132237c0c8add8a32be447b8e9896e46958/internal/pkg/agent/cmd/container.go#L772
which is derived from the STATE_PATH if CONFIG_PATH is not specified, and the STATE_PATH defaults
to ```/usr/share/elastic-agent/state```.
3. there is even the ```container-paths.yml``` file override possibly for some of the commands (!but not the container command)

I tested running with  from the command line with the -path.config and STATE_PATH, which seems to be detecting the files
here is an example of the command with the STATE_PATH
```
sudo STATE_PATH=/etc/elastic-agent ./build/elastic-agent container -c /etc/elastic-agent/elastic-agent.yml
```

@blakerouse are you familiar with which way the agent suppose to have the configuration path set for this particular use case?

**Comment by ChrsMark** [comment]
@aleksmaus by setting the `STATE_PATH=/etc/elastic-agent` on the Pod it works!

Screenshot from 2022-08-31 10-16-11


I think we are ok to proceed here :).

**Comment by ChrsMark** [comment]
@blakerouse @aleksmaus  It would be nice to document it though accordingly in Agent's doc for everyone's benefit ;).

**Comment by aleksmaus** [comment]
> @blakerouse @aleksmaus It would be nice to document it though accordingly in Agent's doc for everyone's benefit ;).

@blakerouse do know what is the recommended way to configure the agent in this particular use case? and where it needs to be documented?
