### PR TITLE
Fix bootstrapping a Fleet Server with v2.

### LINKED ISSUE #995: V2: Agent doesn't stop cleanly on SIGINT
Agent doesn't stop cleanly on SIGINT.
Running off of the latest V2 branch:
https://github.com/elastic/elastic-agent/tree/feature-arch-v2

Steps to reproduce:
1. Enroll the agent from the command line
2. Run the agent from the command line
3. Press Ctrl+C, observe the agent doesn't exist requires SIGKILL for each of the running processes.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes Fleet Server bootstrap process to work with the v2 architecture. Includes fix for #995 an issue during my testing.

## Why is it important?

Path to v2 architecture.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #995

### CODE REVIEW

File: internal/pkg/agent/application/fleet_server_bootstrap_test.go [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+		return mgr.Run(ctx)
+	})
+
+	err := g.Wait()
+	if err != nil && !errors.Is(err, context.Canceled) {
+		require.NoError(t, err)
+	}
+
+	require.NotNil(t, change)
+	assert.NotNil(t, change.Config())
```
Comment (cmacknz) [inline internal/pkg/agent/application/fleet_server_bootstrap_test.go:55]: What is this testing, does the content of config need to be checked?

Comment (blakerouse) [reply internal/pkg/agent/application/fleet_server_bootstrap_test.go:55]: The config is hard-coded so it seems like a waste to check the contents of it. What is important is that a change was sent over the channel and that the config was set.

**Review by cmacknz — APPROVED** [review]
