### PR TITLE
[Flaky Test]: fix TestFakeInputSuite/TestManager_OutputChange

### LINKED ISSUE #4286: [Flaky Test]: TestFakeInputSuite/TestManager_OutputChange – Should be true
### Failing test case

TestFakeInputSuite/TestManager_OutputChange

### Error message

Should be true

### Build

https://buildkite.com/elastic/elastic-agent/builds/7268#018dc3d2-0f4b-42c2-bf41-1274db4e77e9

### OS

Windows

### Stacktrace and notes

```
=== Failed
=== FAIL: pkg/component/runtime TestFakeInputSuite/TestManager_OutputChange (3.51s)
{"log.level":"info","@timestamp":"2024-02-20T00:22:50.346Z","log.origin":{"file.name":"runtime/manager.go","file.line":213},"message":"Starting grpc control protocol listener on port 6789 with max_message_size 104857600","ecs.version":"1.6.0"}
    manager_fake_input_test.go:3276: component fake-0 state changed: {State:STARTING Message:Starting: spawned pid '508' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STARTING Message:Starting: spawned pid '508' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STARTING Message:Starting: spawned pid '508' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STARTING Message:Starting: spawned pid '508' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 Component:<nil> ComponentIdx:0 VersionInfo:{Name: Meta:map[] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000a83710 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc0004d6ea0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000a838c0 err:<nil> logLevel:0}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
{"log.level":"info","@timestamp":"2024-02-20T00:22:52.199Z","log.logger":"component.runtime.fake-0","log.origin":{"file.name":"runtime/manager.go","file.line":680},"message":"control checkin v2 protocol has chunking enabled","ecs.version":"1.6.0"}
    manager_fake_input_test.go:3276: component fake-0 state changed: {State:HEALTHY Message:Healthy: communicating with pid '508' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STARTING Message:Starting: spawned pid '508' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STARTING Message:Starting: spawned pid '508' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STARTING Message:Starting: spawned pid '508' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 Component:<nil> ComponentIdx:0 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000a83710 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc0004d6ea0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000a838c0 err:<nil> logLevel:0}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
    manager_fake_input_test.go:3276: component fake-0 state changed: {State:HEALTHY Message:Healthy: communicating with pid '508' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:HEALTHY Message:Fake Healthy 0-0 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-0 unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:HEALTHY Message:Fake Healthy 0-1 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-1 unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:HEALTHY Message:Fake Healthy 0-1 Payload:map[] unitState:2 unitMessage:Fake Healthy 0-1 unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 Component:<nil> ComponentIdx:1 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000a83710 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc0004d6ea0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000a838c0 err:<nil> logLevel:0}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
{"log.level":"debug","@timestamp":"2024-02-20T00:22:52.835Z","log.origin":{"file.name":"runtime/manager.go","file.line":779},"message":"Stopping component \"fake-0\"","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-02-20T00:22:53.037Z","log.origin":{"file.name":"runtime/manager.go","file.line":830},"message":"component \"fake-0\" stopped.","ecs.version":"1.6.0"}
    manager_fake_input_test.go:3341: [subErrCh0] received: <nil>
    manager_fake_input_test.go:3284: component fake-1 state changed: {State:STARTING Message:Starting: spawned pid '3384' Units:map[{UnitType:input UnitID:fake-input-1-0}:{State:STARTING Message:Starting: spawned pid '3384' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:input UnitID:fake-input-1-1}:{State:STARTING Message:Starting: spawned pid '3384' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] Features:<nil> FeaturesIdx:0 Component:<nil> ComponentIdx:0 VersionInfo:{Name: Meta:map[] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input-1-0}:{state:2 configStateIdx:1 config:0xc0080234d0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-1-1}:{state:2 configStateIdx:1 config:0xc008023830 err:<nil> logLevel:0}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
    manager_fake_input_test.go:3276: component fake-0 state changed: {State:STOPPED Message:Stopped: pid '508' exited with code '1' Units:map[{UnitType:input UnitID:fake-input-0-0}:{State:STOPPED Message:Stopped: pid '508' exited with code '1' Payload:map[] unitState:2 unitMessage:Fake Healthy 0-0 unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:input UnitID:fake-input-0-1}:{State:STOPPED Message:Stopped: pid '508' exited with code '1' Payload:map[] unitState:2 unitMessage:Fake Healthy 0-1 unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:input UnitID:fake-input-0-2}:{State:STOPPED Message:Stopped: pid '508' exited with code '1' Payload:map[] unitState:2 unitMessage:Fake Healthy 0-1 unitPayload:map[] configStateIdx:1 err:<nil>}] Features:<nil> FeaturesIdx:1 Component:<nil> ComponentIdx:1 VersionInfo:{Name:fake Meta:map[input:fake] BuildHash:} expectedUnits:map[{UnitType:0 UnitID:fake-input-0-0}:{state:2 configStateIdx:1 config:0xc000a83710 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-1}:{state:2 configStateIdx:1 config:0xc0004d6ea0 err:<nil> logLevel:0} {UnitType:0 UnitID:fake-input-0-2}:{state:2 configStateIdx:1 config:0xc000a838c0 err:<nil> logLevel:0}] expectedFeatures:<nil> expectedFeaturesIdx:1 expectedComponent:<nil> expectedComponentIdx:1}
    manager_fake_input_test.go:3341: [subErrCh0] received: <nil>
{"log.level":"debug","@timestamp":"2024-02-20T00:22:53.331Z","log.origin":{"file.name":"runtime/manager.go","file.line":779},"message":"Stopping component \"fake-1\"","ecs.version":"1.6.0"}
    manager_fake_input_test.go:3370:
        	Error Trace:	C:/buildkite-agent/builds/bk-agent-prod-gcp-1708387354325171423/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:3370
        	Error:      	Should be true
        	Test:       	TestFakeInputSuite/TestManager_OutputChange
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

- add debug logs on Manager.update for completeness
 - Refactor and rename TestManager_OutputChange
    - use eventually instead of time.Sleep
    - rename to better reflect what it tests
 - Remove TestManager_StartStop as TestManager_StartStopComponent already covers it

## Why is it important?

TestFakeInputSuite/TestManager_OutputChange was flaky

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

Run `FakeInputSuite/TestManager_StartStopComponent`, it should not be flaky

## Related issues

- Closes #4286 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: pkg/component/runtime/manager_fake_input_test.go [hunk 1]
```diff
@@ -3359,21 +3266,37 @@ LOOP:
...
+			case client.UnitStateDegraded, client.UnitStateFailed:
+				comp0Failed = true
+			}
+		case IDComp1:
+			switch step.state.State {
+			case client.UnitStateStarting:
+				comp1Started = true
+			case client.UnitStateDegraded, client.UnitStateFailed:
+				comp1Failed = true
+			}
```
Comment (cmacknz) [inline pkg/component/runtime/manager_fake_input_test.go:3288]: I'm not convinced you can ignore the order of operations.

If you don't do this, you risk bringing back a pervious bug. See https://github.com/elastic/elastic-agent/issues/4286#issuecomment-1954818251 and the description of the change that introduced this test: https://github.com/elastic/elastic-agent/pull/2226

> Currently we start new components before stopping old. This is usually fine unless component is a service (start/stop is slower).
When new service is started old one can be still running and using resources needed for new service to start.
We can than see something like bind port already in use.

We care about the order of operations for the same input type, otherwise we can create situations where the inputs can't start.

**Review by cmacknz — CHANGES_REQUESTED** [review]

File: pkg/component/runtime/manager.go [hunk 2]
```diff
@@ -828,20 +833,12 @@ func (m *Manager) waitForStopped(comp *componentRuntimeState) {
...
-			return
+			return nil
 		}
 
-		m.currentMx.RLock()
-		if _, exists := m.current[compID]; !exists {
-			m.currentMx.RUnlock()
-			return
-		}
-		m.currentMx.RUnlock()
```
Comment (AndersonQ) [inline pkg/component/runtime/manager.go:839]: @michalpristas do you remember why it'd be needed? It seems unnecessary to me. And if no tests fails, I'd believe it indeed is unnecessary

File: pkg/component/runtime/manager_fake_input_test.go [hunk 3]
```diff
@@ -3249,131 +3131,76 @@ func (suite *FakeInputSuite) TestManager_OutputChange() {
...
-		if step.componentID == IDComp0 &&
-			step.state.State == client.UnitStateStopped {
-			comp0Stopped = true
-		}
-		if step.componentID == IDComp1 &&
-			step.state.State == client.UnitStateStarting {
-			require.True(t, comp0Stopped)
-			break
+	assert.Truef(t, comp0StopLogs[0].Time.Before(comp1StartLogs[0].Time),
+		"component %s stopped after %s", comp0ID, comp1ID)
```
Comment (AndersonQ) [inline pkg/component/runtime/manager_fake_input_test.go:3193]: I'm not a fan of relying on logs for tests, but due to the concurrent nature of how the state is reported and the test was collecting them, checking directly the logs are the simplest and mo reliable way to check the correct order of the events.

File: pkg/component/runtime/manager_fake_input_test.go (hunk 1 above)
Comment (AndersonQ) [reply pkg/component/runtime/manager_fake_input_test.go]: > I'm not convinced you can ignore the order of operations.
> 
> If you don't do this, you risk bringing back a previous bug. See [#4286 (comment)](https://github.com/elastic/elastic-agent/issues/4286#issuecomment-1954818251) and the description of the change that introduced this test: #2226
> 
> > Currently we start new components before stopping old. This is usually fine unless component is a service (start/stop is slower).
> > When new service is started old one can be still running and using resources needed for new service to start.
> > We can than see something like bind port already in use.
> 
> We care about the order of operations for the same input type, otherwise we can create situations where the inputs can't start.

done, I kept the check on the order of the events

**Review by pchila — APPROVED** [review]

File: pkg/component/runtime/manager_fake_input_test.go (hunk 3 above)
Comment (cmacknz) [reply pkg/component/runtime/manager_fake_input_test.go:3192]: Agree this is fine.

You could additionally verify that the component 0 start time is before the component 0 stop time.

Right now the following ordering is allowed by the test (even though our logic should not produce it):

comp0stop -> comp1start -> comp0start

**Review by cmacknz — APPROVED** [review]
