### PR TITLE
Fix creation of containing directories for files in tar packages

### LINKED ISSUE #4093: [Unprivileged] Upgrade broken due to permission issues
Upgrading an Elastic Agent that is installed with unprivileged fails to perform upgrade unless the tarball is built with the correct permissions.

`
Failed trigger upgrade of daemon: TarInstaller: creating file /opt/Elastic/Agent/data/elastic-agent-5b3535/package.version: open /opt/Elastic/Agent/data/elastic-agent-5b3535/package.version: permission denied
`

```
root@ogc-linux-arm64-ubuntu-2204-upgrade-cb2f:/opt/Elastic/Agent/data# ls -lh
total 8.0K
-rw------- 1 elastic-agent elastic-agent    0 Jan 17 18:37 agent.lock
drw-r----- 2 elastic-agent elastic-agent 4.0K Jan 17 18:37 elastic-agent-5b3535
drwxr-x--- 5 elastic-agent elastic-agent 4.0K Jan 17 18:37 elastic-agent-666fd7
```

The `elastic-agent-5b3535` is the extracted directory for the upgrade and it doesn't have the correct permissions. It should have the same permissions as `elastic-agent-666fd7`.

https://github.com/elastic/elastic-agent/blob/71c7cb3e51841f555f305dd373f86fe44cd5576a/internal/pkg/agent/application/upgrade/step_unpack.go#L217

Only applies a bitmask for `0770` meaning that the contents of the tarball have an a effect on the extracted contents.

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?
This change fixes the creation of destination directories for file contained in a tar package.
If a file needs to be extracted to a destination directory that does not yet exist we create the necessary directories on the fly with permission `0750`.
If we encounter the same directories after the file, we fix the permissions according to what is specified in the tar archive

## Why is it important?
When running without superuser privileges we need to create a directory structure that has permissions that do not block access to the current user

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[x] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Author's Checklist

- [ ]

## Related issues

- Closes #4093

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: internal/pkg/agent/application/upgrade/step_unpack_test.go [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+			},
+			want:    "abcdef",
+			wantErr: assert.NoError,
+		},
+	}
+	for _, tt := range tests {
+		prevTop := paths.Top()
+		t.Run(tt.name, func(t *testing.T) {
+			testTop := t.TempDir()
+			paths.SetTop(testTop)
```
Comment (blakerouse) [inline internal/pkg/agent/application/upgrade/step_unpack_test.go:125]: There was a race condition that @faec just fixed related to adjusting paths in tests. Would it be possible to just pass in the top directory into the unpack function. That way the test can use that directory versus changing a global.

**Review by blakerouse — CHANGES_REQUESTED** [review]

File: internal/pkg/agent/application/upgrade/step_unpack_test.go (hunk 1 above)
Comment (pchila) [reply internal/pkg/agent/application/upgrade/step_unpack_test.go]: Removed the references to `paths.Data()` that required us to set `paths.Top()` in the unit test.

**Review by blakerouse — APPROVED** [review]
Looks good. Thanks for the change to remove the need for path adjustments in the unit tests.

**Comment by cmacknz** [comment]
This should have a changelog entry shouldn't it? It's a bug fix. It's not one anyone is hitting today, that doesn't mean we shouldn't document the change.

File: internal/pkg/agent/application/upgrade/step_unpack_test.go [hunk 2]
```diff
@@ -0,0 +1,197 @@
...
+	return f.fType == DIRECTORY
+}
+
+func (f files) Sys() any {
+	return nil
+}
+
+type createArchiveFunc func(*testing.T, []files) (string, error)
+
+func TestUpgrader_unpack(t *testing.T) {
```
Comment (cmacknz) [inline internal/pkg/agent/application/upgrade/step_unpack_test.go:89]: 1. Thank you for this, this is great.
2. This test still passes if you take out the `os.Stat` call and associated logic


```diff
diff --git a/internal/pkg/agent/application/upgrade/step_unpack.go b/internal/pkg/agent/application/upgrade/step_unpack.go
index 4f5b0bd744..c7d8100335 100644
--- a/internal/pkg/agent/application/upgrade/step_unpack.go
+++ b/internal/pkg/agent/application/upgrade/step_unpack.go
@@ -10,7 +10,6 @@ import (
        "compress/gzip"
        "fmt"
        "io"
-       "io/fs"
        "os"
        "path/filepath"
        "runtime"
@@ -214,20 +213,20 @@ func untar(log *logger.Logger, version string, archivePath, dataDir string) (str
                case mode.IsDir():
                        log.Debugw("Unpacking directory", "archive", "tar", "file.path", abs)
                        // remove any world permissions from the directory
-                       _, err = os.Stat(abs)
-                       if errors.Is(err, fs.ErrNotExist) {
-                               if err := os.MkdirAll(abs, mode.Perm()&0770); err != nil {
-                                       return "", errors.New(err, "TarInstaller: creating directory for file "+abs, errors.TypeFilesystem, errors.M(errors.MetaKeyPath, abs))
-                               }
-                       } else if err != nil {
-                               return "", errors.New(err, "TarInstaller: stat() directory for file "+abs, errors.TypeFilesystem, errors.M(errors.MetaKeyPath, abs))
-                       } else {
-                               // set the appropriate permissions
-                               err = os.Chmod(abs, mode.Perm()&0o770)
-                               if err != nil {
-                                       return "", errors.New(err, fmt.Sprintf("TarInstaller: setting permissions %O for directory %q", mode.Perm()&0o770, abs), errors.TypeFilesystem, errors.M(errors.MetaKeyPath, abs))
-                               }
+                       // _, err = os.Stat(abs)
+                       // if errors.Is(err, fs.ErrNotExist) {
+                       if err := os.MkdirAll(abs, mode.Perm()&0770); err != nil {
+                               return "", errors.New(err, "TarInstaller: creating directory for file "+abs, errors.TypeFilesystem, errors.M(errors.MetaKeyPath, abs))
                        }
+                       // } else if err != nil {
+                       //      return "", errors.New(err, "TarInstaller: stat() directory for file "+abs, errors.TypeFilesystem, errors.M(errors.MetaKeyPath, abs))
+                       // } else {
+                       //      // set the appropriate permissions
+                       //      err = os.Chmod(abs, mode.Perm()&0o770)
+                       //      if err != nil {
+                       //              return "", errors.New(err, fmt.Sprintf("TarInstaller: setting permissions %O for directory %q", mode.Perm()&0o770, abs), errors.TypeFilesystem, errors.M(errors.MetaKeyPath, abs))
+                       //      }
+                       // }
                default:
                        return "", errors.New(fmt.Sprintf("tar file entry %s contained unsupported file type %v", fileName, mode), errors.TypeFilesystem, errors.M(errors.MetaKeyPath, fileName))
                }
(END)
```

```sh
go test ./internal/pkg/agent/application/upgrade/... -run TestUpgrader_unpack -count 1 -v
?       github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download/localremote     [no test files]
=== RUN   TestUpgrader_unpack
=== RUN   TestUpgrader_unpack/targz_with_file_before_containing_folder
--- PASS: TestUpgrader_unpack (0.00s)
    --- PASS: TestUpgrader_unpack/targz_with_file_before_containing_folder (0.00s)
PASS
ok      github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade 0.591s
```

Comment (pchila) [reply internal/pkg/agent/application/upgrade/step_unpack_test.go:89]: The test passes because of the default 0750 permission when we create the directory on the fly (so we are able to write the file anyways). The code you removed is needed to restore permissions once we come across the directory in the tar archive, but that is not in the assertions. I will modify the test

**Comment by pchila** [comment]
> This should have a changelog entry shouldn't it? It's a bug fix. It's not one anyone is hitting today, that doesn't mean we shouldn't document the change.
@cmacknz  not sure about the changelog as the change that introduced the issue is related to the unprivileged elastic-agent feature. Before such change, directories created on the fly would always have `0755` permissions and that would not be corrected if we encountered the directory with different permission later in the tar.gz archive. So a customer cannot have encountered the exact same bug in the released versions.
I added a changelog regardless as we improve on the previous behavior by fixing the permissions as specified in the tar.gz  (minus the world ones, which I think was the original intention of the unprivileged change)
