### PR TITLE
move the package version file outside of app directory for MacOS

### LINKED ISSUE #3285: Error initializing version information: reading package version from file....package.version: no such file or directory
For confirmed bugs, please report:
- Version: `8.10.0-SNAPSHOT`
- Operating System: MacOS Ventura 13.5.1
- Steps to Reproduce:

1. Install or upgrade to Elastic Agent version `8.10.0-SNAPSHOT`.
2. Run any `elastic-agent` subcommand.  Examples below.

```
$ elastic-agent version
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Binary: 8.10.0-SNAPSHOT (build: 923c98b0b336d30adaa6e4d650ffbcde450e45cd at 2023-08-23 02:46:23 +0000 UTC)
Daemon: 8.10.0-SNAPSHOT (build: 923c98b0b336d30adaa6e4d650ffbcde450e45cd at 2023-08-23 02:46:23 +0000 UTC)
```

```
$ elastic-agent status
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   └─ status: (HEALTHY) Running
```

```
$ elastic-agent uninstall
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Elastic Agent will be uninstalled from your system at /Library/Elastic/Agent. Do you want to continue? [Y/n]:y
Elastic Agent has been uninstalled.
```

All the above commands succeeded. It's just annoying or misleading to print out this error, I think, especially since we do fallback to the default binary version when we can't read the package version file: https://github.com/elastic/elastic-agent/blob/5fe4fcda84ae9e915e5b734077e5db256860c808/version/helper.go#L43-L48

Looks like the error message is being emitted from here: https://github.com/elastic/elastic-agent/blob/5fe4fcda84ae9e915e5b734077e5db256860c808/internal/pkg/agent/cmd/common.go#L44-L48

### PR DESCRIPTION
**Pull request by pchila**
## What does this PR do?
Move elastic package version file outside of `elastic-agent.app` directory to fix the package signing for Mac

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Author's Checklist

- [ ]

## Related issues

- Closes #3285 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: version/helper.go [hunk 1]
```diff
@@ -64,7 +65,19 @@ func GetAgentPackageVersionFilePath() (string, error) {
...
+	if runtime.GOOS == "darwin" {
+		// On Mac the path is different because of package signing issues
+		// we have to go outside the elastic-agent.app directory
+		appDirIndex := strings.Index(dirPath, "/elastic-agent.app/")
+		if appDirIndex != -1 {
+			dirPath = dirPath[:appDirIndex]
+		}
+	}
+
+	return filepath.Join(dirPath, PackageVersionFileName), nil
```
Comment (ycombinator) [inline version/helper.go:80]: Take a look at https://github.com/elastic/elastic-agent/blob/454e6253a0e3457828b769e7c2c7c0e9365d870b/internal/pkg/agent/application/paths/common.go#L211-L221 and also https://github.com/elastic/elastic-agent/blob/454e6253a0e3457828b769e7c2c7c0e9365d870b/internal/pkg/agent/application/paths/common.go#L229-L241 and how they two are used together in https://github.com/elastic/elastic-agent/blob/454e6253a0e3457828b769e7c2c7c0e9365d870b/internal/pkg/agent/application/paths/common.go#L206-L208.

If I'm reading the logic of this function here, it looks pretty much the same as the logic in the functions mentioned above.  So maybe you could reuse them somehow, either by exporting `retrieveExecutableDir()` from the `paths` package or by moving `GetAgentPackageVersionFilePath()` into the `paths` package?  This would also let you get rid of the `getCurrentExecutablePath` function as I believe it's only being called from the `GetAgentPackageVersionFilePath` function.

Comment (pchila) [reply version/helper.go:80]: In this patch I am not making any assumption as to what the directory structure is... I just cut off the part of the path that goes in `elastic-agent.app`
the code we have in paths requires that there are exactly 2 or 5 levels (for Mac) between the executable and the execDir.

The initial idea of this was to have the package version file side by side with the executable wherever it is... we are just moving it for mac because of package signing issues and I would prefer to keep changes to a minimum for this hotfix. We can open a follow-up issue if you feel that we should remove the duplication (we still have to verify that everything still works also for packages that we just extract somewhere on disk (it must not depend on installing agent)

Comment (ycombinator) [reply version/helper.go:80]: Sounds fair. Would you mind opening that follow up issue and linking it here so we don't lose track of this work? Thanks.

**Review by ycombinator — APPROVED** [review]
Tested this PR locally on my Mac. 

### Before this PR
After installing Agent:
```
$ sudo find /Library/Elastic/Agent -iname package.version
/Library/Elastic/Agent/data/elastic-agent-454e62/elastic-agent.app/Contents/MacOS/package.version
$ sudo cat /Library/Elastic/Agent/data/elastic-agent-454e62/elastic-agent.app/Contents/MacOS/package.version
8.11.0
$ sudo elastic-agent version
Binary: 8.11.0-SNAPSHOT (build: 454e6253a0e3457828b769e7c2c7c0e9365d870b at 2023-08-30 17:38:19 +0000 UTC)
Daemon: 8.11.0-SNAPSHOT (build: 454e6253a0e3457828b769e7c2c7c0e9365d870b at 2023-08-30 17:38:19 +0000 UTC)
```

### After this PR
After installing Agent:
```
$ sudo find /Library/Elastic/Agent -iname package.version
/Library/Elastic/Agent/data/elastic-agent-73b4c7/package.version
$ sudo cat /Library/Elastic/Agent/data/elastic-agent-73b4c7/package.version
8.11.0
$ sudo elastic-agent version
Binary: 8.11.0-SNAPSHOT (build: 73b4c7cfaef362452cac4bd03e19518ed61212d5 at 2023-08-30 17:35:04 +0000 UTC)
Daemon: 8.11.0-SNAPSHOT (build: 73b4c7cfaef362452cac4bd03e19518ed61212d5 at 2023-08-30 17:35:04 +0000 UTC)
```

**Comment by pierrehilbert** [comment]
Thx @ycombinator, I'm merging this to unlock the next BC.
@pchila don't forget to babysit the backport to 8.10 branch

**Comment by ycombinator** [comment]
> @pchila don't forget to babysit the backport to 8.10 branch

@pchila I can take care of this if your day is ending.

File: version/helper.go (hunk 1 above)
Comment (pchila) [reply version/helper.go:80]: Created #3337
