### PR TITLE
Correctly merge component and collector extensions

### LINKED ISSUE #13610: [beats receivers] beatsauth extensions specified by users are not merged correctly with automatically generated ones
- Relates https://github.com/elastic/kibana/pull/259308
- Relates https://github.com/elastic/kibana/issues/255019

Fleet will now insert the beatsauth extension for users using OpenTelemetry integrations that have already configured SSL and proxies in the existing agent policy format.

Configuring an output with an arbitrary CA trusted fingerprint in a policy that contains any OpenTelemetry integration with agent monitoring enabled or any other non-OpenTelemetry integration, results in a correct agent policy that Elastic Agent cannot run.

Using the Custom File Log integration and configuring an output CA fingerprint generates the following collector configuration:

```yaml
service:
  pipelines:
    logs/otelcol-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-otelcol-filelog_otel-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5:
      receivers:
        - >-
          filelog/otelcol-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-otelcol-filelog_otel-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5
      processors:
        - >-
          transform/otelcol-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-otelcol-filelog_otel-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-routing
      exporters:
        - forward
    logs:
      receivers:
        - forward
      exporters:
        - elasticsearch/default
  extensions:
    - beatsauth/default

extensions:
  beatsauth/default:
    ssl:
      ca_trusted_fingerprint: 06ba26e540740d7460dc7209b59da87e3b7907802f5ac20bae86b2da78ea4114
exporters:
  elasticsearch/default:
    endpoints:
      - >-
        https://2a52706f31054eb29a59c9f4296b5af5.eastus2.staging.azure.foundit.no:443
    auth:
      authenticator: beatsauth/default
receivers:
  filelog/otelcol-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-otelcol-filelog_otel-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5:
    include:
      - /var/log/*.log
    start_at: end
    max_concurrent_files: 1024
    include_file_name: true
    include_file_path: false
    include_file_name_resolved: false
    include_file_path_resolved: false
    include_file_owner_name: false
    include_file_owner_group_name: false
    include_file_record_number: false
    include_file_record_offset: false
    encoding: utf-8
    preserve_leading_whitespaces: false
    preserve_trailing_whitespaces: false
    fingerprint_size: 1kb
    initial_buffer_size: 16KiB
    max_log_size: 1MiB
    poll_interval: 200ms
    force_flush_period: 500ms
processors:
  transform/otelcol-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-otelcol-filelog_otel-filelogreceiver-1cb0c015-a8ba-402a-89dd-e254711937b5-routing:
    log_statements:
      - context: log
        statements:
          - set(attributes["data_stream.type"], "logs")
          - set(attributes["data_stream.dataset"], "filelogreceiver")
          - set(attributes["data_stream.namespace"], "default")
connectors:
  forward: {}
```

However the agent fails to run because the otel-merged.yml does not include the agent generated beatsauth extensions in the service.extensions list:

```yaml
service:
    extensions:
        - beatsauth/default # Missing beatsauth/_agent-component/default and beatsauth/_agent-component/monitoring
        - elastic_diagnostics
        - healthcheckv2/7cc88848-22b5-4c10-a8dd-241e3ebb2567
extensions:
    beatsauth/_agent-component/default:
        continue_on_error: true
        idle_connection_timeout: 3s
        proxy_disable: false
        ssl:
            ca_trusted_fingerprint: 06ba26e540740d7460dc7209b59da87e3b7907802f5ac20bae86b2da78ea4114
        timeout: 1m30s
    beatsauth/_agent-component/monitoring:
        continue_on_error: true
        idle_connection_timeout: 3s
        proxy_disable: false
        ssl:
            ca_trusted_fingerprint: 06ba26e540740d7460dc7209b59da87e3b7907802f5ac20bae86b2da78ea4114
        timeout: 1m30s
    beatsauth/default:
        ssl:
            ca_trusted_fingerprint: 06ba26e540740d7460dc7209b59da87e3b7907802f5ac20bae86b2da78ea4114
```

### PR DESCRIPTION
**Pull request by swiatekm**
## What does this PR do?

When merging otel collector configuration coming from inputs with the embedded one, it explicitly merges the extension lists rather than let one override the other.

The newly introduced config merging function is used everywhere else in the package for consistency, in some cases simplifying the code paths.

## Why is it important?

Extensions from both sources should be present.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

Build the agent package locally and run it with the default configuration, adding:

```yaml
receivers:
  nop:
exporters:
  nop:
extensions:
  health_check:
service:
  extensions:
    - health_check
  pipelines:
    logs:
      receivers: [nop]
      exporters: [nop]
```

You should see attempts to ship data to ES.

## Related issues

- Closes https://github.com/elastic/elastic-agent/issues/13610

### CODE REVIEW

File: internal/pkg/otel/manager/manager.go [hunk 1]
```diff
@@ -518,31 +516,23 @@ func maybeInjectLogLevel(config *confmap.Conf, logplevel logp.Level) error {
...
-	if err := config.Merge(confmap.NewFromStringMap(map[string]any{"service::telemetry::logs::level": level})); err != nil {
+	if err := mergeWithExtensions(config, confmap.NewFromStringMap(map[string]any{"service::telemetry::logs::level": level})); err != nil {
 		return fmt.Errorf("failed to set log level in otel config: %w", err)
 	}
 	return nil
 }
 
 func injectDiagnosticsExtension(config *confmap.Conf) error {
-	extensionCfg := map[string]any{
+	return mergeWithExtensions(config, confmap.NewFromStringMap(map[string]any{
```
[the remark this answers is not in the document]
Comment (swiatekm) [reply internal/pkg/otel/manager/manager.go:526]: Fixed in https://github.com/elastic/elastic-agent/pull/13639/changes/4f45c924c632fb6cc0121c76ca7630890873ad05, which also fixed another bug involving relative ordering.

**Comment by cmacknz** [comment]
Manually tested for the situation that uncovered this problem and confirmed this fixes it

File: internal/pkg/otel/manager/confmap.go [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+		"service::extensions": combined,
+	}))
+}
+
+// mergeExtensionLists returns the union of dst and src preserving the ordering
+// within each list. Shared elements (present in both lists) act as
+// synchronisation points: all dst-only elements up to a shared element are
+// emitted first, then all src-only elements preceding it in src, then the
+// shared element itself. Remaining src-only elements are appended at the end.
+func mergeExtensionLists(dst, src []any) []any {
```
Comment (cmacknz) [inline internal/pkg/otel/manager/confmap.go:69]: Is this an alternate solution to the problem `ConfmapEnableMergeAppendOptionFeatureGate` solves? Can we use that?

https://github.com/open-telemetry/opentelemetry-collector/blob/307e3abdbae90f3b9f5ccec7d4d50087be7f9f67/confmap/internal/conf.go#L103

**Review by cmacknz — DISMISSED** [review]
LGTM, one non-blocking comment.

File: changelog/fragments/1776251957-fix-otel-embedded-auth.yaml [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+# - breaking-change: a change to previously-documented behavior
+# - deprecation: functionality that is being removed in a later release
+# - bug-fix: fixes a problem in a previous version
+# - enhancement: extends functionality but does not break or fix existing behavior
+# - feature: new functionality
+# - known-issue: problems that we are aware of in a given version
+# - security: impacts on the security of a product or a user’s deployment.
+# - upgrade: important information for someone upgrading from a prior version
+# - other: does not fit into any of the other categories
+kind: feature
```
Comment (blakerouse) [inline changelog/fragments/1776251957-fix-otel-embedded-auth.yaml]: This is more of a bug fix and not a feature.

**Review by blakerouse — DISMISSED** [review]
Definitely simplified the code. No comments other than the comment on the changelog entry.

**Review by cmacknz — APPROVED** [review]

File: internal/pkg/otel/manager/confmap.go (hunk 2 above)
Comment (swiatekm) [reply internal/pkg/otel/manager/confmap.go:69]: It is, but it's not very convenient for us to use that flag right now, as we'd need to keep our configurations separate and let the collector merge them. It's something we can consider doing in the longer term, but I think we still want to have access to the final merged state - for diagnostics if nothing else.
