### PR TITLE
Fix/5163 retry download upgrade verifiers

### LINKED ISSUE #5163: Upgrade verifiers do not retry if the download fails or times out.
Hello, I have deployed Elastic Agent with Fleet Server in version 8.14.2 and tried to upgrade few days later to 8.14.3.

When watching the logs through Observability -> Logs -> Stream I have noticed some error messages from *elastic_agent* dataset. The logs are provided below as well as temporary fix.

# **Steps to reproduce:**

- Upgrade Elastic Agent (Fleet Server) from Kibana UI.

## **Log output:**

```
12:28:50.843 elastic_agent [elastic_agent][info] download from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-linux-x86_64.tar.gz completed in 48 seconds @ 7.16MBps
12:28:50.843 elastic_agent [elastic_agent][info] updated upgrade details
12:28:50.854 elastic_agent [elastic_agent][info] download from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-linux-x86_64.tar.gz.sha512 completed in Less than a second @ +InfYBps12:28:50.854
12:28:50.854 elastic_agent [elastic_agent][info] updated upgrade details
12:28:50.854 elastic_agent [elastic_agent][info] updated upgrade details
12:28:50.854 elastic_agent [elastic_agent][info] updated upgrade details
12:28:50.854 elastic_agent [elastic_agent][info] updated upgrade details
12:28:51.464 elastic_agent [elastic_agent][info] Default PGP appended
12:29:21.465 elastic_agentm [elastic_agent][warn] Skipped remote PGP located at "https://artifacts.elastic.co/GPG-KEY-elastic-agent" because it's unavailable: 2 errors occurred:
	* Get "https://artifacts.elastic.co/GPG-KEY-elastic-agent": context deadline exceeded
	* Remote PGP download failed

12:29:21.468 elastic_agent [elastic_agent][warn] Skipped remote PGP located at "https://localhost:8221/api/agents/upgrades/8.14.3/pgp-public-key" because it's unavailable: 2 errors occurred:
	* Get "https://localhost:8221/api/agents/upgrades/8.14.3/pgp-public-key": x509: certificate is valid for myfleet.example.com, not localhost
	* Remote PGP download failed

12:29:21.468 elastic_agent [elastic_agent][info] Using 1 PGP keys
12:29:52.081 elastic_agent [elastic_agent][info] Cleaning up non-matching downloaded versions
12:29:52.114 elastic_agent [elastic_agent][error] upgrade to version 8.14.3 failed: failed verification of agent binary: 2 errors occurred:
	* could not get .asc file: fetching asc file from '/opt/Elastic/Agent/data/elastic-agent-8.14.2-173817/downloads/elastic-agent-8.14.3-linux-x86_64.tar.gz.asc': open /opt/Elastic/Agent/data/elastic-agent-8.14.2-173817/downloads/elastic-agent-8.14.3-linux-x86_64.tar.gz.asc: no such file or directory
	* fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-linux-x86_64.tar.gz.asc: failed loading public key: Get "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-linux-x86_64.tar.gz.asc": context deadline exceeded

12:29:52.114 elastic_agent [elastic_agent][info] updated upgrade details
```

# **Bug fix (manual):**

- While in the upgrade process, go into folder */opt/Elastic/Agent/data/elastic-agent-8.14.2-173817/downloads* and issue the command below.
- On the Fleet Server issue the command to manually download the .asc file:
```
root@myfleet:/opt/Elastic/Agent/data/elastic-agent-8.14.2-173817/downloads# curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-linux-x86_64.tar.gz.asc
```

- Start the upgrade process again if it fails the first time from Kibana UI.
  - Now the data stream shows "Using 2 PGP keys" as the second required one to download the update archive was manually put into the required downloads directory.
- Wait until the upgrade is successfully done.

# **Notes**

My Fleet Server host is listening on socket ``*:8220`` on a domain name *https://myfleet.example.com:8220*. The host has another socket open ``127.0.0.1:8221`` which is used for internal API operations. My firewall has OUTPUT chain to accept all and INPUT chain has the rule to accept all connections made to loopback adapter as specified in a rule ``iptables -A INPUT -i lo -j ACCEPT``.

### PR DESCRIPTION
**Pull request by kaanyalti**
- Bug

## What does this PR do?

Adds backoff retry for verifier artifact requests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~

## Related issues

- Closes #5163

### CODE REVIEW

File: internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+		btr.logger.Warnf("request failed: %s, retrying in %s", err, retryAfter)
+	}
+
+	var resp *http.Response
+	var err error
+	opFunc := func() error {
+		resp, err = btr.next.RoundTrip(req)
+		if err != nil {
+			return err
+		}
```
Comment (blakerouse) [inline internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go:45]: This lint error should be fixed. Should probably call close no matter what.

**Review by blakerouse — APPROVED** [review]
This looks good overall, just look at the lint issue.

File: internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go (hunk 1 above)
Comment (kaanyalti) [reply internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go:75]: Looked into this with @belimawr . The linter is most probably complaining here because the response is used in a closure and not passed onto anything else. Closing the response body here causes an error when the caller tries to read from it. The response is closed after each unsuccessful attempt so that we don't leak resources. When an attempt is successful, the response is sent back up the call stack. This is similar to how it is implemented in [FleetAuthRoundTripper](https://github.com/elastic/elastic-agent/blob/d9ee653f10ccb8fc30828ddb9c33dd94280c53e9/internal/pkg/fleetapi/client/round_trippers.go#L44). Another option was to read the whole response into a buffer, close the body, and then assign the bufffer back to the response body after wrapping it with `io.NopCloser`. This is how the [DebugRoundTripper](https://github.com/elastic/elastic-agent/blob/d9ee653f10ccb8fc30828ddb9c33dd94280c53e9/internal/pkg/remote/round_trippers.go#L53) handles the request body. While it is a valid solution, it may cause issues in case there are other midleware in the rountripper chain where there may be a response body size limiter, and it also doesn't seem to be necessary here as the current implementation works as expected. To resolve the linting problem I added a `nolint` comment.

File: internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+type BackoffRoundTripper struct {
+	next   http.RoundTripper
+	logger *logger.Logger
+}
+
+func (btr *BackoffRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
+	exp := backoff.NewExponentialBackOff()
+	boCtx := backoff.WithContext(exp, req.Context())
+
+	opNotify := func(err error, retryAfter time.Duration) {
```
Comment (michalpristas) [inline internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go:37]: 👍

**Review by michalpristas — APPROVED** [review]

**Review by swiatekm — APPROVED** [review]

File: internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go (hunk 1 above)
Comment (blakerouse) [reply internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt.go:75]: Thanks for the detailed explanation. Glad to see it was also added to the code.

File: internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt_test.go [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+
+	t.Run("test post request with body", func(t *testing.T) {
+		failedResCounter := 2
+		handler := func(rw http.ResponseWriter, req *http.Request) {
+			if failedResCounter > 0 {
+				rw.WriteHeader(http.StatusInternalServerError)
+				failedResCounter--
+			}
+
+			body, err := io.ReadAll(req.Body)
```
Comment (belimawr) [inline internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt_test.go:57]: [Suggestion]
Here and after L76, you could validate that the request/response body contain the correct value. So if there is a bug when reading the body and replacing it by the `bytes.Reader` we can catch it.

Comment (kaanyalti) [reply internal/pkg/agent/application/upgrade/artifact/download/http/verify_backoff_rtt_test.go:57]: On line 79 I'm validating that I receive the same value that is sent to the test server. So I am already doing what you're suggesting here. 

I'm not sure how necessary it is to validate the body in line 57 as it is only a test function. Please let me know if I'm misunderstanding anything here.

**Review by belimawr — APPROVED** [review]
