### PR TITLE
Fix debian packaging for upgrades

### LINKED ISSUE #5101: Agent .deb install: state.enc not copied during Elastic Agent upgrade from 8.13 and above
- Version: 8.13 and above
- Operating System: Ubuntu 22.04
  - Install Method: Apt
- Discuss Forum URL: [Discuss Forum Post](https://discuss.elastic.co/t/362752)

**Description**
When upgrading Elastic Agent from version 8.13 or above (e.g., 8.14.1 to 8.14.2), the `state.enc` file is not copied to the new install directory. This causes the agent to remain in a `(STARTING) Waiting for initial configuration and composable variables` state.

**Steps to Reproduce**
- Install Elastic Agent version 8.13 or above (e.g., 8.14.1).
- Enroll the agent in a Fleet policy.
- Verify the agent is running and healthy.
- Upgrade to a higher version (e.g., 8.14.2).
- Observe that state.enc is not copied to the new install directory, causing the agent to fail to start correctly.

**Observations Post Upgrade**
```
# elastic-agent version
Binary: 8.14.2 (build: 1738179d53e747c48af7350a0b8fe68eda1a5b31 at 2024-07-01 16:29:34 +0000 UTC)
Daemon: 8.14.2 (build: 1738179d53e747c48af7350a0b8fe68eda1a5b31 at 2024-07-01 16:29:34 +0000 UTC)

# ls -al /var/lib/elastic-agent/data/elastic-agent-*
elastic-agent-8.14.1-1348b9:
total 24
drwxr-xr-x 4 root root 4096 Jul 10 11:26 .
drwxr-xr-x 7 root root 4096 Jul 10 11:26 ..
drwx------ 2 root root 4096 Jul 10 11:26 logs
drwxr-x--- 4 root root 4096 Jul 10 11:25 run
-rw------- 1 root root 6745 Jul 10 11:26 state.enc

elastic-agent-8.14.2-173817:
total 111876
drwxr-xr-x 4 root root      4096 Jul 10 11:29 .
drwxr-xr-x 7 root root      4096 Jul 10 11:26 ..
drwxr-xr-x 5 root root      4096 Jul 10 11:26 components
-rwxr-xr-x 1 root root 114530504 Jul  2 18:54 elastic-agent
drwx------ 2 root root      4096 Jul 10 11:29 logs
-rw-r--r-- 1 root root       339 Jul  2 18:55 manifest.yaml
-rw-r--r-- 1 root root         7 Jul  2 18:55 package.version
```
**Issue**
The `postinst` script fails to correctly follow the symlink to the old agent directory, leading to the failure to copy `state.enc`. This leaves the agent in a broken state where it believes it is enrolled in Fleet but lacks the necessary state information.

**Additional Notes**
Upgrading from versions prior to 8.13 (e.g., from 8.12.2 to 8.14.2) successfully copies the `state.enc` file, indicating the issue is likely related to changes introduced in version 8.13.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes the debian packaging to properly copy the `state.enc` and `state.yml` files to the new version of the Elastic Agent.

## Why is it important?

Without this upgrading to a new version of the Elastic Agent losses the `state.enc` and/or `state.yml` file.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~ **(cannot add unit tests for packaging)**
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

None

## How to test this PR locally

Build the debian package:

```
$ PLATFORMS="linux/amd64" PACKAGES="deb" SNAPSHOT="true" EXTERNAL="true" mage package
```

Install older version of Elastic Agent

```
sudo dpkg -D2 -i elastic-agent-8.14.3-amd64.deb
```

Enroll into Fleet

```
sudo elastic-agent enroll --url={url} --enrollment-token={token}
```

Upgrade to built version

```
sudo dpkg -D2 -i build/distributions/elastic-agent-8.16.0-SNAPSHOT-amd64.deb
```

## Related issues

- Closes #5101

### CODE REVIEW

**Comment by blakerouse** [comment]
@pierrehilbert I said I had it ready, I just need to add an integration test. I also want to test this change with RPM's as well.

File: dev-tools/packaging/templates/linux/postinstall.sh.tmpl [hunk 1]
```diff
@@ -47,5 +17,9 @@ fi
 echo "create symlink "$symlink" to "$new_agent_dir/elastic-agent""
 ln -s "$new_agent_dir/elastic-agent" "$symlink"
 
+# reload systemctl and then restart service
+echo "systemd enable/restart elastic-agent"
 systemctl daemon-reload 2> /dev/null
+systemctl enable elatic-agent 2> /dev/null || true
```
Comment (leehinman) [inline dev-tools/packaging/templates/linux/postinstall.sh.tmpl:23]: Does this cause any documentation changes for `delayed enrollment` feature?  I'm not sure, but that is the one place I can think of where we might have accidentally relied on the service not starting immediately.

Comment (blakerouse) [reply dev-tools/packaging/templates/linux/postinstall.sh.tmpl:23]: Hmm, that is very true.

One of the reasons I liked this change was because upon fresh install the service was started, then enrollment worked correctly. With it off and enrollment the daemon is not running and it errors on restarting the Elastic Agent. Another reason is for upgrading, where it does restart the service and it becomes the new version.

This does cause an issue with delay enrollment though. I guess we just need to make a decision on the path we want to take.

Comment (blakerouse) [reply dev-tools/packaging/templates/linux/postinstall.sh.tmpl:23]: I have been thinking about this more and with delayed enrollment this actually isn't too much of an issue. If you install the package and then enroll with delayed enrollment then it will not restart the Elastic Agent so the running agent will be unaffected. It would only take affect if you restarted the service, at that point it would enroll.

I think I am in favor of keeping this new behavior and maybe add a note in the delayed enrollment documentation. It running will not affect it, so I think this is less of a worry.

Comment (leehinman) [reply dev-tools/packaging/templates/linux/postinstall.sh.tmpl:23]: I have a preference for the new behavior as well.  It is more inline with https://www.debian.org/doc/debian-policy/index.html

I just wanted to make sure we didn't have any surprises with delayed enrollment.

**Review by leehinman — APPROVED** [review]

File: dev-tools/packaging/templates/linux/postinstall.sh.tmpl (hunk 1 above)
Comment (ceeeekay) [inline dev-tools/packaging/templates/linux/postinstall.sh.tmpl:23]: I notice there's a typo in the service name here

Comment (blakerouse) [reply dev-tools/packaging/templates/linux/postinstall.sh.tmpl]: Thanks for the catch. I have updated this.

**Comment by blakerouse** [comment]
I am getting failures from flaky tests, no failures from DEB/RPM tests or the new upgrade tests. This is ready to be merged, but will need a force merge as the flaky tests have seem to become very consistent now.

**Comment by ycombinator** [comment]
> I am getting failures from flaky tests, no failures from DEB/RPM tests or the new upgrade tests. This is ready to be merged, but will need a force merge as the flaky tests have seem to become very consistent now.

The failing test is the same K8s test that has been failing for a while now: https://github.com/elastic/elastic-agent/issues/5275.  As such, I'm OK to force merge this PR here.
