### PR TITLE
Revert "Revert "Fix log level value reported by Agent to Fleet (#4838)" (#4938)"

### LINKED ISSUE #4747: `log_level` metadata is not accurate
Follow up to the discussion in https://github.com/elastic/kibana/issues/180778

Reproduction: 
1. Enroll a new agent into a policy that already has log level set to `debug`
2. Observe that the agent successfully sent debug logs
3. View agent document, observe that `local_metadata.elastic.agent.log_level` is reporting `info` even though it is running at `debug` level from its policy

### PR DESCRIPTION
**Pull request by pchila**
This reverts commit 2b2e8d0672b24e84753f434223f0a61c0fe56300.

## What does this PR do?
This PR reverts the revert of PR #4838.
The only difference compared to the original PR is the removal of agent client initialization in `(f *Fixture) PrepareAgentCommand` which was no longer needed once integration test `TestSetLogLevelFleetManaged` used `install` instead of `run` subcommand to run and enroll the agent

## Why is it important?
We still want to send the correct log level in use by elastic agent to Fleet during check-in

## Checklist

- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Related issues

- Closes #4747 

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: testing/integration/log_level_test.go [hunk 1]
```diff
@@ -44,93 +47,187 @@ func TestSetLogLevelFleetManaged(t *testing.T) {
...
 	t.Log("Getting default Fleet Server URL...")
 	fleetServerURL, err := fleettools.DefaultURL(ctx, info.KibanaClient)
 	require.NoError(t, err, "failed getting Fleet Server URL")
 
-	t.Cleanup(func() {
-		timeoutCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
-		defer cancel()
-		err := info.KibanaClient.DeletePolicy(timeoutCtx, policyResp.ID)
-		assert.NoError(t, err, "error deleting policy %s", policyResp.ID)
+	installOutput, err := f.Install(ctx, &atesting.InstallOpts{
```
Comment (cmacknz) [inline testing/integration/log_level_test.go:57]: That you now install the agent is the problem, it doesn't set the paths correctly for the DEB and RPM agents https://github.com/elastic/elastic-agent/issues/4929#issuecomment-2166736033

**Review by cmacknz — APPROVED** [review]

File: testing/integration/log_level_test.go (hunk 1 above)
Comment (cmacknz) [reply testing/integration/log_level_test.go:57]: (this is a bug in the test framework)
