### PR TITLE
Fix proxy download test

### LINKED ISSUE #11796: [Flaky Test]: TestFleetDownloadProxyURL – Unable to verify that upgrade has failed.
### Failing test case

TestFleetDownloadProxyURL

### Error message

Unable to verify that upgrade has failed.

### Build

https://buildkite.com/elastic/elastic-agent/builds/31990/steps/canvas?jid=019b149e-80b5-4b63-bf9a-8c9059914ba2#019b149e-80b5-4b63-bf9a-8c9059914ba2

### OS

Linux

### Stacktrace and notes

```markdown
proxy_url_test.go:947:
        	Error Trace:	/opt/buildkite-agent/builds/bk-agent-prod-gcp-1765577496692113238/elastic/elastic-agent/testing/integration/ess/proxy_url_test.go:951
        	            				/opt/buildkite-agent/.asdf/installs/golang/1.24.11/go/src/runtime/asm_amd64.s:1700
        	Error:      	Not equal:
        	            	expected: "UPG_FAILED"
        	            	actual  : "UPG_DOWNLOADING"
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-UPG_FAILED
        	            	+UPG_DOWNLOADING
    proxy_url_test.go:947:
        	Error Trace:	/opt/buildkite-agent/builds/bk-agent-prod-gcp-1765577496692113238/elastic/elastic-agent/testing/integration/ess/proxy_url_test.go:947
        	Error:      	Condition never satisfied
        	Test:       	TestFleetDownloadProxyURL
        	Messages:   	Unable to verify that upgrade has failed.

```
My guess is that downloading artifacts simply took longer than the test expected. Other than increasing the timeout, not sure there's anything we can do about this.

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Fixes flaky TestFleetDownloadProxyURL test by changing how agent status is gathered.

## Related issues

- Closes #11796

### CODE REVIEW

File: pkg/testing/fixture.go [hunk 1]
```diff
@@ -860,6 +860,63 @@ func (f *Fixture) ExecStatus(ctx context.Context, opts ...statusOpt) (AgentStatu
 	}
 }
 
+// ExecStatusRaw executes `elastic-agent status --output=json`.
+//
+// Returns the output parsed as map[string]any and the error from the execution. Keep in mind the agent exits with status 1 if it's
```
Comment (michel-laterman) [inline pkg/testing/fixture.go]: The agent [control server uses a non-standard format](https://github.com/elastic/elastic-agent/blob/9d1ea9123a820e2c086f66a54f351aea52189fb0/pkg/control/time.go#L9) when serializing timestamps breaking the `ExecStatus` command. I've added this method in order to avoid this.

Comment (cmacknz) [reply pkg/testing/fixture.go]: This is weird, how is something formatted with `time.Format` not a valid time.Time?

Do you have an example of the error this causes?

I don't like just duplicating the function like this, it would be better to fix things in place, but I can't suggest alternatives unless I know what specific error we are working around.

Comment (michel-laterman) [reply pkg/testing/fixture.go]: `agent status returned an error: could not unmarshal agent status output: parsing time "2025-12-18 19:02:32 +0000 UTC" as "2006-01-02T15:04:05Z07:00": cannot parse " 19:02:32 +0000 UTC" as "T"`.

By default Go will try to to parse strings using the RFC3339 nano format ([docs](https://pkg.go.dev/time#Time.UnmarshalJSON)), the control server does not use this when serializing times to send to the client

Comment (cmacknz) [reply pkg/testing/fixture.go]: Is there a drawback to changing to RFC3339? It seems like this would always unconditionally fail without a custom unmarshal implementation. Is this just the first time anyone has ever tried to unmarshal this as JSON in Go?

This is clearly just an artifact of the control server, the upgrade watcher is using gRPC instead so doesn't hit this I suspect because it never unmarshals as JSON.

Why do we have this non-standard format?

Comment (michel-laterman) [reply pkg/testing/fixture.go]: I can't think of a drawback from a technical standpoint; i've made a draft to change it here:https://github.com/elastic/elastic-agent/pull/11923.
I don't know why the non-standard format was chosen, perhaps @blakerouse or @michalpristas would know?

Comment (michel-laterman) [reply pkg/testing/fixture.go]: Removed the `ExecStatusRaw` call now that https://github.com/elastic/elastic-agent/pull/11923 is merged.

**Review by cmacknz — APPROVED** [review]

**Comment by michel-laterman** [comment]
I'm going run the tests a couple more times to ensure it's not flaky

**Comment by michel-laterman** [comment]
buildkite test this

**Comment by michel-laterman** [comment]
buildkite test this

**Comment by michel-laterman** [comment]
buildkite test this

**Comment by michel-laterman** [comment]
buildkite test this
