### PR TITLE
Validate install base path

### LINKED ISSUE #2558: Unable to install agent with `--base-path` location on Ubuntu 22.
**Kibana version:**  8.8 Snapshot kibana cloud environment

**Host OS and Browser version:** Ubuntu 22

**Build details:**
```
VERSION: 8.8.0 SNAPSHOT
BUILD: 62546
COMMIT: f5034e60a501e7b61a3e1bff34e64c9b94c71344
Artifacts: https://snapshots.elastic.co/8.8.0-fc95a751/downloads/beats/elastic-agent/elastic-agent-8.8.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 8.8 Snapshot kibana cloud environment should be available.
2. Agent policy should be created with System integration.

**Steps to reproduce:**
1. Run below installation command for ubuntu agent: with `--base-path= /var` flag. [invalid format with space]
2. Observe error while installation.
3. Run installation command with correct path:  `--base-path=/var` and observe same error.

**Screenshot:**

**Expected Result:**
User should be able to install agent with `--base-path` location on Ubuntu 22.

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR validates the value of the `--base-path` CLI option of the `elastic-agent install` command.  If the value is not an absolute path, it returns an error. 

## Why is it important?

To prevent users accidentally attempting to install Elastic Agent in the same folder where they extracted the downloaded Elastic Agent archive, and corrupting the contents of the folder in the process.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation: https://github.com/elastic/ingest-docs/pull/180
- [ ] ~I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] ~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~ Not needed as bug fix is in same release when the feature was introduced
- [ ] ~I have added an integration test or an E2E test~ Added unit tests

## Related issues

- Fixes #2558

### CODE REVIEW

File: internal/pkg/agent/cmd/install.go [hunk 1]
```diff
@@ -227,6 +233,14 @@ func installCmd(streams *cli.IOStreams, cmd *cobra.Command) error {
 	return nil
 }
 
+func validateBasePath(basePath string) error {
+	if !filepath.IsAbs(basePath) {
+		return fmt.Errorf("base path %q is not absolute", basePath)
+	}
+
+	return nil
+}
```
Comment (AndersonQ) [inline internal/pkg/agent/cmd/install.go:242]: [Suggestion]
I don't think a function just to call another function is necessary, using directly `filepath.IsAbs` is even more explicit about what is being validated.

File: internal/pkg/agent/cmd/install.go [hunk 2]
```diff
@@ -40,7 +42,7 @@ would like the Agent to operate.
 
 	cmd.Flags().BoolP("force", "f", false, "Force overwrite the current and do not prompt for confirmation")
 	cmd.Flags().BoolP("non-interactive", "n", false, "Install Elastic Agent in non-interactive mode which will not prompt on missing parameters but fails instead.")
-	cmd.Flags().String("base-path", paths.DefaultBasePath, "Base path for installing Elastic Agent's files.")
+	cmd.Flags().String(flagInstallBasePath, paths.DefaultBasePath, "Base path (absolute) for installing Elastic Agent's files.")
```
Comment (AndersonQ) [inline internal/pkg/agent/cmd/install.go:45]: [Suggestion]
I think we could take the opportunity and make it clearer.

```suggestion
	cmd.Flags().String(flagInstallBasePath, paths.DefaultBasePath, "The path where the Elastic Agent will be installed. It must be an absolute path.")
```

File: internal/pkg/agent/cmd/install_test.go
Comment (AndersonQ) [inline internal/pkg/agent/cmd/install_test.go:1]: For me this test is redundant because it's is actually testing `filepath.IsAbs`.
Id rather see a test ensuring `installCmd` returns an error is the `base-path` isn't absolute. That is the test which will ensure the functionality added.

If the call to `validateBasePath` is removed or misused, the tests will pass, but what the actual validation won't happen.

**Review by AndersonQ — CHANGES_REQUESTED** [review]
As I commented on one of the tests, it's my understanding the test necessary here is for `installCmd`. Could you write e a test for it?

The other comments are, as they say, suggestions, fell free to ignore them :)

**Comment by ycombinator** [comment]
Thanks for the review, @AndersonQ.  I've addressed all your feedback and this PR is ready for re-review, when you get a chance.

**Comment by ycombinator** [comment]
Unit tests from this PR are [failing](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/PR-2567/6/pipeline/841) in Windows.  Investigating...

File: version/version.go [hunk 3]
```diff
@@ -4,4 +4,4 @@
 
 package version
 
-const defaultBeatVersion = "8.9.0"
+const defaultBeatVersion = "8.8.0"
```
Comment (AndersonQ) [inline version/version.go:7]: [Blocker]
ooops, I think you need to rebase your branch

**Review by AndersonQ — CHANGES_REQUESTED** [review]
Sorry, but could add a test case with a valid base path, for completeness.

Also, I think you need to rebase your branch, it's setting the version back to 8.8

File: version/version.go (hunk 3 above)
Comment (ycombinator) [reply version/version.go:7]: Accidental commit.  Thanks for catching!

**Comment by ycombinator** [comment]
> Sorry, but could add a test case with a valid base path, for completeness.

Any suggestions on how to do this? Because with a valid base path, `installCmd` will continue execution... and the very next thing it will hit is the root check: https://github.com/elastic/elastic-agent/blob/d59128503e1bbde49027019fe60320b78d9e1173/internal/pkg/agent/cmd/install.go#L55

Even if we say, let's run this test as sudo, then it will try to actually install the Agent as a service, which is probably not something we want to do while testing?

**Comment by AndersonQ** [comment]
> > Sorry, but could add a test case with a valid base path, for completeness.
> 
> Any suggestions on how to do this? Because with a valid base path, `installCmd` will continue execution... and the very next thing it will hit is the root check:

My bad, you're right, we can let that to an e2e or QA validation

**Comment by ycombinator** [comment]
> My bad, you're right, we can let that to an e2e or QA validation

Yes, this is my thinking too.  QA is already validating the "happy path" scenario and we'll write an E2E/integration test for it as well where it will be okay to mess with the underlying host.

**Review by AndersonQ — APPROVED** [review]

**Comment by ycombinator** [comment]
> we'll write an E2E/integration test for it as well where it will be okay to mess with the underlying host.

Still WIP but the PR for this is up: https://github.com/elastic/elastic-agent/pull/2578
