### PR TITLE
`elastic-agent install`: Only uninstall when Agent is installed

### LINKED ISSUE #3414: Misguiding information- `Uninstalling current Elastic Agent` is shown under CLI while installing elastic-agent.
**Kibana Build details:**
```
VERSION: 8.11.0 SNAPSHOT
BUILD: 66942
COMMIT: 6526280785d585e495a827dee46c08c160461a83
```

**Host OS and Browser version:** All, All

**Preconditions:**
1. 8.11.0 SNAPSHOT Kibana cloud environment should be available.
2. No agent should be installed.

**Steps to reproduce:**
1. Navigate to CLI.
2. Run agent install command and observe CLI shows: `Uninstalling current Elastic Agent`, even when no agent is installed
3. Now observe agent is installed.
4. Rerun the same command and observe command still fails to execute as the agent is already installed.

**Expected Result:**
Misguiding information- `Uninstalling current Elastic Agent` should not be shown under CLI while installing elastic-agent.
- It doesn't uninstall existing installed agent.
- If no agent is already installed, there is nothing to uninstall.

**Screenshots:**

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR improves the `elastic-agent install` experience by only trying to uninstall the existing Elastic Agent installation if Elastic Agent is currently installed.

## Why is it important?

So the progress messages shown to the user during `elastic-agent install` are not misleading by suggesting that the existing Elastic Agent installation is being uninstalled, even when there is no Elastic Agent currently installed.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have made corresponding change to the default configuration files~
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [ ] ~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~
- [ ] ~I have added an integration test or an E2E test~

## How to test this PR locally

1. Start with a host where Elastic Agent is NOT currently installed.
2. Build Elastic Agent from this PR and install it.
   ```
    sudo ./elastic-agent install
   ```
3. Verify that the progress messages shown do NOT include a message about Elastic Agent being uninstalled.
4. Verify that the installation succeeds.
   ```
    sudo elastic-agent status
   ```
5. Try to install Elastic Agent again.
   ```
    sudo ./elastic-agent install
   ```
6. Verify that installation fails with a message about Elastic Agent already being installed.
7. Try to install Elastic Agent again, this time with the `--force` flag.
   ```
    sudo ./elastic-agent install --force
   ```
8. Verify that the progress messages shown include a message about Elastic Agent being uninstalled.
9. Verify that the installation succeeds.
   ```
    sudo elastic-agent status
   ```

## Related issues

- Resolves #3414

### CODE REVIEW

File: internal/pkg/agent/cmd/install.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func installCmd(streams *cli.IOStreams, cmd *cobra.Command) error {
 
 	nonInteractive, _ := cmd.Flags().GetBool("non-interactive")
 	if nonInteractive {
-		fmt.Fprintf(streams.Out, "Installing in non-interactive mode.")
+		fmt.Fprintln(streams.Out, "Installing in non-interactive mode.")
```
Comment (ycombinator) [inline internal/pkg/agent/cmd/install.go:86]: Not strictly related to the changes in this PR.

**Review by blakerouse — APPROVED** [review]
Looks good!

**Review by pchila — APPROVED** [review]
LGTM

@ycombinator could you please solve the conflicts so we can merge this ?
