### PR TITLE
Fix/panic with composable renderer

### LINKED ISSUE #806: panic while uninstalling part of Elastic Agent
```
panic: sync: negative WaitGroup counter
goroutine 55 [running]:
sync.(*WaitGroup).Add(0xc0002fa930?, 0xc0000ddd40?)
sync/waitgroup.go:80 +0xda\rsync.(*WaitGroup).Done(...)
sync/waitgroup.go:105
[github.com/elastic/elastic-agent/internal/pkg/agent/install.applyDynamics.func1](https://github.com/elastic/elastic-agent/internal/pkg/agent/install.applyDynamics.func1)({0xc0009494d0?, 0xc000524bb0?, 0x6?})
[github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall.go:240](https://github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall.go:240) +0x4c
[github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run.func1()](https://github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run.func1())
[github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:175](https://github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:175) +0x1df
created by [github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run](https://github.com/elastic/elastic-agent/internal/pkg/composable.(*controller).Run)
[github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:128](https://github.com/elastic/elastic-agent/internal/pkg/composable/controller.go:128) +0x71b"

```

./elastic-agent install -v -n --url=[xxxx.fleet.us-east-1.aws.found.io:443](https://xxxx.fleet.us-east-1.aws.found.io/) --enrollment-token=xxxxxxxx

### PR DESCRIPTION
**Pull request by ph**
## What does this PR do?

In the code to retrieve the variables from the configuration files we
need to pass a execution callback, this callback will be called in a
goroutine. This callback can be executed multiple time until the
composable renderer is stopped. There were a problem in the code that
made the callback called multiple time and it made the waitgroup
internal counter to do to a negative values.

This commit change the behavior, it start the composable renderer give
it a callback when the callback receives the variables it will stop the
composable's Run method using the context.

This ensure that the callback will be called a single time and that the
variables are correctly retrieved.

Fixes: https://github.com/elastic/elastic-agent/issues/806

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

This is hard race bug to reproduce, it was found using automation tools to deploy elastic agent on multiple machine.
Just enrolling the Agent could trigger this issue. Try to enroll gent on slower machines, its pretty hard to reproduce it, I was able to reproduce it on a Linux VM but in a loop.

## Related issues

- Closes #806

### CODE REVIEW

File: internal/pkg/agent/install/uninstall.go [hunk 1]
```diff
@@ -235,9 +235,15 @@ func applyDynamics(ctx context.Context, log *logger.Logger, cfg *config.Config)
...
 		wg.Add(1)
+
+		ctx, cancel := context.WithCancel(ctx)
+
+		// The composable system will continuously run, we are only interested in the first run on of the
+		// renderer to collect the variables we should stop the execution.
 		varsCallback := func(vv []*transpiler.Vars) {
 			varsArray = vv
 			wg.Done()
+			cancel()
```
Comment (aleksmaus) [inline internal/pkg/agent/install/uninstall.go:246]: imho this changes the behavior and introduces potential race that when the callback can be called before the context cancellation is detected in the caller.

and the ```cancel``` is not called here if the callback is not called for some reason, might be flagged by linter. the pattern is usually to guarantee the ```defer cancel()```

think using ```sync.Once``` might safer fix if you want to guarantee that you only need to capture the first run.

maybe for example:
https://go.dev/play/p/-KpLGWS03yX


what do you think about something like this?
```
		var (
			wg sync.WaitGroup
			once sync.Once
		)
		wg.Add(1)
		ctx, cancel := context.WithCancel(ctx)
		defer cancel()
		varsCallback := func(vv []*transpiler.Vars) {
			once.Do(func() {
				varsArray = vv
				wg.Done()
				cancel()
			})
		}

		ctrl, err := composable.New(log, cfg)
		if err != nil {
			return nil, err
		}
		_ = ctrl.Run(ctx, varsCallback)
		wg.Wait()
```

Comment (aleksmaus) [reply internal/pkg/agent/install/uninstall.go:246]: another possible problem here is if the callback is never called due to any error in Run (the error is not checked now), then it will wait on WaitGroup at the end forever

File: CHANGELOG.next.asciidoc [hunk 2]
```diff
@@ -112,6 +112,7 @@
 - Allow the / char in variable names in eql and transpiler. {issue}715[715] {pull}718[718]
 - Fix data duplication for standalone agent on Kubernetes using the default manifest {issue-beats}31512[31512] {pull}742[742]
 - Agent updates will clean up unneeded artifacts. {issue}693[693] {issue}694[694] {pull}752[752]
+- Fix a panic cause by a race condition when installing the Elastic Agent. {issues}806[806]
```
Comment (AndersonQ) [inline CHANGELOG.next.asciidoc:115]: typo?
```suggestion
- Fix a panic caused by a race condition when installing the Elastic Agent. {issues}806[806]
```

File: internal/pkg/agent/install/uninstall.go (hunk 1 above)
Comment (AndersonQ) [reply internal/pkg/agent/install/uninstall.go:246]: I like this approach, it's less prone to problems

**Review by AndersonQ — CHANGES_REQUESTED** [review]

File: internal/pkg/agent/install/uninstall.go (hunk 1 above)
Comment (ph) [reply internal/pkg/agent/install/uninstall.go:246]: I initially though about going with `Once` before doing the `cancel` thing, I thought it was adding more locking complexity over the current scenario, since we only want to opt out on the first render were we would assume we have all the appropriate information collected. But I do think a mix of cancelling the ctx and waiting on the `Done()` would be better than mixing cancel with the current Waitgroup, I will make the change.

File: internal/pkg/agent/install/uninstall.go [hunk 3]
```diff
@@ -233,19 +234,34 @@ func applyDynamics(ctx context.Context, log *logger.Logger, cfg *config.Config)
 	inputs, ok := transpiler.Lookup(ast, "inputs")
 	if ok {
 		varsArray := make([]*transpiler.Vars, 0)
-		var wg sync.WaitGroup
-		wg.Add(1)
+
+		// Gie some time for the providers to replaces the variables
```
Comment (aleksmaus) [inline internal/pkg/agent/install/uninstall.go:238]: "Gie some time for the providers to replaces the variables" -> "Give some time for the providers to replace the variables" typo?

File: internal/pkg/agent/install/uninstall.go [hunk 4]
```diff
@@ -233,19 +234,34 @@ func applyDynamics(ctx context.Context, log *logger.Logger, cfg *config.Config)
...
+		const timeout = 15 * time.Second
+		var doOnce sync.Once
+		ctx, cancel := context.WithTimeout(ctx, timeout)
+
```
Comment (aleksmaus) [inline internal/pkg/agent/install/uninstall.go:242]: add 
```
defer cancel()
```
there is a possibility that the 
```
ctrl, err := composable.New(log, cfg)
```
returns the error and the ```cancel``` is never called

**Review by aleksmaus — CHANGES_REQUESTED** [review]

**Review by aleksmaus — APPROVED** [review]
Thank you!

**Review by AndersonQ — APPROVED** [review]

**Comment by ph** [comment]
test this please

**Comment by ph** [comment]
@AndersonQ I've updated the description with a possible way to test it, it's really hard, I had success with a slow vm using less cpu and memory and have a tight retry loop, but 1 out of 200 tries.. :(

**Comment by ph** [comment]
Going to merge this, will take a look at the fleet flaky run for e2e. It seems the setup is not reliable enough to run.
