### PR TITLE
Fix shouldFleetEnroll so it doesn't re-enroll when FLEET_URL hasn't changed

### LINKED ISSUE #13185: `shouldFleetEnroll` always triggers re-enrollment due to Fleet URL scheme mismatch with stored host
When running Elastic Agent in a container managed by ECK as a DaemonSet, the agent re-enrolls on every pod restart despite valid enrollment state (fleet.enc) being persisted via a hostPath volume. This results in duplicate agent entries in Fleet.

The root cause is a string comparison mismatch in `shouldFleetEnroll` in `container.go`.

```
storedFleetHosts := storedConfig.Fleet.Client.GetHosts()
if len(storedFleetHosts) == 0 || !slices.Contains(storedFleetHosts, setupCfg.Fleet.URL) {
    // The Fleet URL in the setup does not exist in the stored configuration, so enrollment is required.
    return true, nil
}
```

`setupCfg.Fleet.URL` is populated directly from the `FLEET_URL` environment variable, which includes the scheme.

`storedConfig.Fleet.Client.GetHosts` returns values from the stored remote.Config struct, which stores the protocol separately in a Protocol field and the host as just `host:port`.

For confirmed bugs, please report:
- Version: All
- Operating System: Containers
- Steps to Reproduce:

1. Deploy ECK 3.3.1 with Elasticsearch, Kibana, and Fleet Server on a Kubernetes cluster
2. Deploy an Elastic Agent as a DaemonSet using the ECK Agent CRD with mode: fleet and fleetServerEnabled: false
3. The ECK operator injects `FLEET_ENROLL=true`, `FLEET_URL=https://...`, and `FLEET_ENROLLMENT_TOKEN` into the pod spec, and mounts agent state at `/usr/share/elastic-agent/state` via a hostPath volume
4. Wait for the agent to enroll and become healthy
5. Delete a DaemonSet pod `kubectl delete pod <agent-pod>`
6. The DaemonSet controller creates a replacement pod on the same node
7. Observe the replacement pod's logs: `Starting enrollment to URL: https://fleet-server-agent-http.default.svc:8220/`.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes shouldFleetEnroll so it doesn't re-enroll when FLEET_URL hasn't changed. `setupCfg.Fleet.URL` is now parsed and compared correctly to `remote.Config` struct, which stores the protocol separately in a Protocol field and the host as just `host:port`.

## Why is it important?

When running Elastic Agent in a container managed by ECK as a DaemonSet, the agent re-enrolls on every pod restart despite valid enrollment state (fleet.enc) being persisted via a hostPath volume. This results in duplicate agent entries in Fleet.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~ (unit test coverage)

## Disruptive User Impact

None

## How to test this PR locally

Build the container image from this PR. Then:

1. Deploy ECK 3.3.1 with Elasticsearch, Kibana, and Fleet Server on a Kubernetes cluster
2. Deploy an Elastic Agent as a DaemonSet using the ECK Agent CRD with `mode: fleet` and `fleetServerEnabled: false` using the built container image.
3. Delete a DaemonSet pod `kubectl delete pod <agent-pod>`

Observe that the re-created pod doesn't re-enroll.

## Related issues

- Closes #13185

### CODE REVIEW

**Review by ycombinator — DISMISSED** [review]

File: internal/pkg/agent/cmd/container.go [hunk 1]
```diff
@@ -1161,10 +1161,48 @@ func shouldFleetEnroll(setupCfg setupConfig) (bool, error) {
...
+	matchedHostOnly := slices.Contains(storedFleetHosts, setupFleetHost)
+	if !matchedFullURL && !matchedHostOnly {
 		// The Fleet URL in the setup does not exist in the stored configuration, so enrollment is required.
 		return true, nil
 	}
+	// When the stored config uses the pre-policy-update form (separate Protocol/Host
+	// fields, matched via setupFleetHost above), also verify the protocol hasn't changed.
+	// Skip this check when we matched via the full URL, because the scheme is already
+	// embedded in that URL and the stored Protocol field may hold a stale default value.
+	if !matchedFullURL && setupFleetURL.Host != "" && setupFleetURL.Scheme != "" &&
```
Comment (ycombinator) [inline internal/pkg/agent/cmd/container.go:1200]: Nit: I'm not sure you need `setupFleetURL.Scheme != ""`, because `url.Parse` only populates `Host` when the URL has a valid scheme and you're already checking `setupFleetURL.Host != ""` earlier.


```suggestion
	if !matchedFullURL && setupFleetURL.Host != "" &&
```

Comment (blakerouse) [reply internal/pkg/agent/cmd/container.go:1200]: The `setupFleetURL.Scheme != ""` check is actually needed. `url.Parse` does not guarantee that a non-empty `Host` implies a non-empty `Scheme`. A URL of `//host:port` produces a non-empty `Host` with an empty `Scheme`.

Without the `Scheme != ""` guard, a Fleet URL compared against `storedConfig.Fleet.Client.Protocol` would  mismatch, triggering a re-enrollment.
