### PR TITLE
Fix log level support to adjust components and remove need for re-exec 

### LINKED ISSUE #1896: Changing the agent log level does not update running beats
**Description**
When deploying the latest BC5 agent and trying to change the log level using the logs tab on the fleet page, it seems like the agent does not update its running beats log level.

**Expected Behavior**
Agent log level should propagate to other beats, and if I'm not mistaken I would expect them to restart, which I also didn't see (not 100% sure)

image
image
image

For confirmed bugs, please report:
- Version: 8.6.0 [BC5](https://github.com/elastic/elastic-agent/commits/7b1dc64c917b579652739f970b016f98cd1c8899) 
- Operating System: Linux
- Discuss Forum URL: 
- Steps to Reproduce:
1. Deploy the latest 8.6.0 stack (I've used cloud)
2. Deploy agent over ec2 as a daemonset (for example KSPM integration)
3. Go to the agent log tab in the fleet UI 
4. Change the log level and apply

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

This pushes the log level into the component model generation so each calculated unit has the appropriate log level. The command runtime log writer is now adjusted without having to restart each process to adjust the support log level for the overall component as well as each individual unit. The log level change is also sent to the component to adjust its own internal logging (but not required as Elastic Agent will be the ultimate authority on log level coming from that component).

The Elastic Agent overall log level is also changed now without requiring a re-execution of the entire process. Changing the log level is now quicker and doesn't require any of the components to restart.

All specification files that support the `-E logging.level` has now been set to `debug`. This allows each spawned process to start logging in debug with the Elastic Agent filtering out those log messages from stdout/stderr, but when placed into debug mode start getting those logs. This allows a component designed for Elastic Agent not need to worry about its configured log level, it can just log and Elastic Agent will handle the rest. If it can adjust its log level by reading its log level from the protocol that would be an optimization, but no longer a requirement.

## Why is it important?

Previously the log level setting was not being propagated into the coordinator and did not have an affect on the log levels set on each unit defined for a component. Changing the log level from Fleet used to result in the Elastic Agent re-executing which resulted in all components to be restart just by changing the log level.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #1896

### CODE REVIEW

File: pkg/component/runtime/log_writer.go [hunk 1]
```diff
@@ -21,22 +22,47 @@ type zapcoreWriter interface {
...
 type logWriter struct {
-	loggerCore zapcoreWriter
-	logCfg     component.CommandLogSpec
-	remainder  []byte
+	loggerCore   zapcoreWriter
+	logCfg       component.CommandLogSpec
+	logLevel     zap.AtomicLevel
+	unitLevels   map[string]zapcore.Level
+	levelMx      sync.RWMutex
+	inheritLevel zapcore.Level
```
Comment (cmacknz) [inline pkg/component/runtime/log_writer.go:41]: What is inheritLevel? It still isn't very clear to me after reading the implementation. Cloud you add a comment?

File: internal/pkg/agent/application/actions/handlers/handler_action_settings.go [hunk 2]
```diff
@@ -53,6 +50,12 @@ func (h *Settings) Handle(ctx context.Context, a fleetapi.Action, acker acker.Ac
 		return fmt.Errorf("invalid log level, expected debug|info|warning|error and received '%s'", action.LogLevel)
 	}
 
+	lvl := logp.InfoLevel
```
Comment (AndersonQ) [inline internal/pkg/agent/application/actions/handlers/handler_action_settings.go:53]: [Blockerish]
Would you mind adding a type alias on `github.com/elastic/elastic-agent/pkg/core/logger` for the log level? It'd be better not leak this as none of these files were importing `logp`. Besides it's passing a `logp.Level` to a seemingly unrelated package, it's confusing at first glace.

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 3]
```diff
@@ -166,6 +169,8 @@ type Coordinator struct {
 
 	specs component.RuntimeSpecs
 
+	llCh chan logp.Level
```
Comment (AndersonQ) [inline internal/pkg/agent/application/coordinator/coordinator.go:172]: [Suggestion]
I might be wrong, but I don't think it's so obvious that `ll` stands for LogLevel
```suggestion
	logLevelCh chan logp.Level
```

File: internal/pkg/agent/cmd/inspect.go [hunk 4]
```diff
@@ -333,58 +333,76 @@ func getMonitoringFn(cfg map[string]interface{}) (component.GenerateMonitoringCf
...
+		return logp.InfoLevel, errors.New(err,
+			fmt.Sprintf("could not parse configuration file %s", cfgPath),
+			errors.TypeFilesystem,
+			errors.M(errors.MetaKeyPath, cfgPath))
+	}
+	if cfg.Settings.LoggingConfig != nil {
+		return cfg.Settings.LoggingConfig.Level, nil
 	}
-	return m, nil
+	return logp.InfoLevel, nil
```
[the remark this answers is not in the document]
Comment (AndersonQ) [reply internal/pkg/agent/cmd/inspect.go:405]: +1
having the default on `logger` package would be better

File: pkg/component/runtime/command.go [hunk 5]
```diff
@@ -460,21 +471,64 @@ func (c *CommandRuntime) getCommandSpec() *component.CommandSpec {
...
+		"type":    typeStr,
+		"binary":  binaryName,
+		"dataset": dataset,
+	})
+	return newLogWriter(logger.Core(), cmdSpec.Log, ll, unitLevels, src)
+}
+
+// getLogLevels returns the lowest log level and a mapping between each unit and its defined log level.
+func getLogLevels(comp component.Component) (zapcore.Level, map[string]zapcore.Level) {
+	baseLevel := zapcore.ErrorLevel
```
Comment (AndersonQ) [inline pkg/component/runtime/command.go:502]: [Blockerish]
`zapcore`? don't [pkg](https://github.com/elastic/elastic-agent/tree/main/pkg)/[core](https://github.com/elastic/elastic-agent/tree/main/pkg/core)/[logger](https://github.com/elastic/elastic-agent/tree/main/pkg/core/logger)/logger.go abstract it already? Now there are 2 different packages used to define the log level of `pkg/core/logger`. I'd be better to avoid this abstraction leak.

**Review by AndersonQ — CHANGES_REQUESTED** [review]

File: pkg/component/runtime/log_writer.go (hunk 1 above)
Comment (blakerouse) [reply pkg/component/runtime/log_writer.go:41]: inheritLevel is the level that will be used for a log message in the case it doesn't define a log level for stdout it is INFO and for stderr it is ERROR.

I have added that comment in the code.

File: internal/pkg/agent/application/actions/handlers/handler_action_settings.go (hunk 2 above)
Comment (blakerouse) [reply internal/pkg/agent/application/actions/handlers/handler_action_settings.go:53]: `logp.Level` is used through out the entire code base. I agree it might be nice to make this change, but doing in a PR for something that needs to be fixed in 8.6 is not the correct place. Currently the `logp.` is referenced 72 times across 31 different files in the elastic-agent repository.

File: internal/pkg/agent/application/actions/handlers/handler_action_settings.go [hunk 6]
```diff
@@ -53,6 +50,12 @@ func (h *Settings) Handle(ctx context.Context, a fleetapi.Action, acker acker.Ac
...
+	err := lvl.Unpack(action.LogLevel)
+	if err != nil {
+		return errors.New("failed to unpack log level", err)
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply internal/pkg/agent/application/actions/handlers/handler_action_settings.go:56]: Updated.

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 3 above)
Comment (blakerouse) [reply internal/pkg/agent/application/coordinator/coordinator.go:172]: Updated.

File: pkg/component/runtime/command.go (hunk 5 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:502]: The entire `logWriter` works on zapcore. The `logWriter` must work with `zapcore` because it need to bypass log level checking for `logp`.

Please see implementation of `logWriter` for information on why this needs to be done, or the PR where it was implemented.

File: pkg/core/logger/logger.go [hunk 7]
```diff
@@ -105,6 +105,11 @@ func toCommonConfig(cfg *Config) (*config.C, error) {
 	return commonLogp, nil
 }
 
+// SetLevel changes the overall log level of the global logger.
+func SetLevel(lvl logp.Level) {
+	logp.SetLevel(lvl.ZapLevel())
+}
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/core/logger/logger.go:111]: See above for reason this is not the time or PR to perform this type of change.

File: internal/pkg/agent/application/actions/handlers/handler_action_settings.go (hunk 2 above)
Comment (cmacknz) [reply internal/pkg/agent/application/actions/handlers/handler_action_settings.go:52]: I agree with Blake on this, we can do this as a follow up if we feel it is important enough to address. It shouldn't block this PR, it isn't a bug or flaw in the implementation.

Comment (AndersonQ) [reply internal/pkg/agent/application/actions/handlers/handler_action_settings.go:52]: ok, makes sense :)

**Review by AndersonQ — APPROVED** [review]
