### PR TITLE
Spawn the watcher of the new binary vs the current running version.

### LINKED ISSUE #2873: When upgrading, the elastic-agent watch command should be invoked using the new agent binary
When the agent upgrades it launches an instance of the `elastic-agent watch` command to ensure that the new version of the elastic agent remains healthy and does not crash within 10 minutes of being started.

The `elastic-agent` version invoked is the old version we are upgrading *from*, not the new version we are upgrading *to*:

https://github.com/elastic/elastic-agent/blob/9c062312d1952e68cd928b12d49dde8ec16865cb/internal/pkg/agent/application/upgrade/rollback.go#L109-L118

The `elastic-agent watch` command should instead be invoked using the new version of the elastic-agent binary we are upgrading to. For example, in an upgrade from 8.7.1 to 8.8.2 we should invoke the `elastic-agent watch` command using the 8.8.2 `elastic-agent` binary.

1. This means the upgrade watcher can be aware of any changes in the Elastic Agent that are introduced in the new version of the upgrade, for example the changes in https://github.com/elastic/elastic-agent/issues/2579
2. This protects from the situation where there is a bug in the upgrade watcher by allowing us to solve it by upgrading to a different version. Today a bug in the upgrade watcher that would prevent a successful upgrade cannot be fixed without a reinstall of the existing agent.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Spawns the new version of the Elastic Agent watcher when upgrading versus using the current running Elastic Agent version to perform the watch.

## Why is it important?

The upgrade watcher can be aware of any changes in the Elastic Agent that are introduced in the new version of the upgrade. Protects from the situation where there is a bug in the upgrade watcher by allowing us to solve it by upgrading to a different version. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Related issues

- Closes #2873

### CODE REVIEW

File: internal/pkg/agent/application/upgrade/rollback.go [hunk 1]
```diff
@@ -108,14 +109,18 @@ func Cleanup(log *logger.Logger, currentHash string, removeMarker bool, keepLogs
...
 	}
 
-	versionedHome := paths.VersionedHome(paths.Top())
-	cmd := invokeCmd(versionedHome)
+	if targetHash == "" {
+		// when targetHash is not provided then we use the current running hash
+		targetHash = release.ShortCommit()
+	}
+	hashedDir := fmt.Sprintf("%s-%s", agentName, targetHash)
+	cmd := invokeCmd(filepath.Join(paths.Top(), "data", hashedDir))
```
Comment (pchila) [inline internal/pkg/agent/application/upgrade/rollback.go:123]: This clashes with https://github.com/elastic/elastic-agent/issues/2579
Since by the time we invoke the watcher we already switched the symlink, can't we just call the watcher from home ?

**Review by pchila — APPROVED** [review]
LGTM

**Comment by pchila** [comment]
I just noticed that some integration tests failed but buildkite is green... THere is something wrong in the integration test script...

**Comment by blakerouse** [comment]
@pchila That is interesting, we need to fix that.

**Comment by blakerouse** [comment]
buildkite test this
