### PR TITLE
Container entrypoint retrieves policy and enrollment token when more than 20 are present

### LINKED ISSUE #12069: Elastic Agent Enrollment Fails for Policies Not on First Page of API Results
Issue detected on version 9.1.8

**Description:**

During the deployment of Elastic Agents on Kubernetes platform, an issue was identified in which the agent was unable to locate the specified agent policy by name. This occurred because the policy was not included in the first page (first 20 agent policies) of the agent policies query API response. Although the policy exists and is correctly configured in Kibana, the agent enrollment process fails due to this limitation.

**Steps to Reproduce:**

1. Deploy an Elastic agent using the following manifest (snippet):

    ```yaml
    apiVersion: agent.k8s.elastic.co/v1alpha1
    kind: Agent
    metadata:
      name: fleet-agent-name
      namespace: fleet-test-namespace
    spec:
      fleetServerEnabled: false
      mode: fleet
      policyID: policy-id
      statefulSet:
        podTemplate:
          spec:
            automountServiceAccountToken: true
            containers:
              - env:
                  - name: FLEET_ENROLL
                    value: '1'
                  - name: FLEET_URL
                    value: 'https://fleet-server.example.com'
                  - name: KIBANA_FLEET_HOST
                    value: 'https://kibana.example.com'
                  - name: FLEET_TOKEN_POLICY_NAME
                    value: Agent Test Policy
                  - name: KIBANA_FLEET_USERNAME
                    value: fleet-username
                  - name: KIBANA_FLEET_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: password
                        name: fleet-password
                name: agent
                version: 9.1.8
    ```

2. Observe the following error during agent initialization:

    ```
    agent container initialisation - chown paths
    Error: unable to find policy named "Agent Test Policy"
    For help, please see our troubleshooting guide at https://www.elastic.co/docs/troubleshoot/ingest/fleet/common-problems
    ```

**Expected Behavior:**

The agent should be able to locate and enroll with the specified policy name, regardless of its position in the paginated list of policies.

**Actual Behavior:**

The agent fails to enroll because it only checks the first page (first 20 agent policies) of agent policies returned by the `/api/fleet/agent_policies` endpoint. The policy is found on the second page of results, but the agent does not iterate through all pages to find it.

**Additional Information:**

- The code responsible for this behavior is located in the Elastic agent source code, specifically in the `findPolicy` function ([source](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/cmd/container.go#L573:L580)).
- When manually querying the `/api/fleet/agent_policies` endpoint, the policy is found on the second page of results.

**Proposed Solution:**

Modify the Elastic agent code to iterate through all pages of agent policies when enrolling by name, ensuring that policies not on the first page can be found and used for enrollment.

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Add kuery based searches when retrieving the policy id by name to the container entrypoint, and kuery+paging when retrieving the associated enrolment token.

## Why is it important?

Configurations with many policies, using a username+password and fleet token policy name will fail to start.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
-  [x] I have added an integration test or an E2E test

## Disruptive User Impact

N/A

## Related issues

- Closes #12069

### CODE REVIEW

File: internal/pkg/agent/cmd/container.go [hunk 1]
```diff
@@ -572,11 +573,39 @@ func buildFleetServerConnStr(cfg fleetServerConfig) (string, error) {
...
 	var policies kibanaPolicies
-	err := performGET(cfg, client, "/api/fleet/agent_policies", &policies, streams.Err, "Kibana fetch policy")
-	if err != nil {
-		return nil, err
+	params := url.Values{}
+	page := 1
+	attempt := 0
+	for {
+		params.Set("page", strconv.Itoa(page))
+		code, result, err := client.Request(http.MethodGet, "/api/fleet/agent_policies", params, nil, nil)
```
Comment (cmacknz) [inline internal/pkg/agent/cmd/container.go]: Why can't this use `performGET` so we don't have to duplicate the retries?

If you want to add query params but not touch the other calls, add a base function like performGetWithParams with more args and then call it in the existing `performGET`.

File: internal/pkg/agent/cmd/container_test.go [hunk 2]
```diff
@@ -694,3 +694,79 @@ func TestShouldEnroll(t *testing.T) {
...
+		if r.URL.Query().Get("page") == "1" {
+			resp = []byte(`{"items": [{
+                      "id": "test-id-1",
+		      "name": "Policy 1",
+		      "status": "active",
+		      "is_default": false,
+		      "is_default_fleet_server": false
+		    }], "total": 2, "page": 1, "perPage": 1}`)
+		} else {
+			resp = []byte(`{"items": [{
```
Comment (cmacknz) [inline internal/pkg/agent/cmd/container_test.go]: Let's put more than one agent policy in this list just to make sure we test multiple policies per page properly.

**Comment by michel-laterman** [comment]
buildkite test this

File: internal/pkg/agent/cmd/container.go [hunk 3]
```diff
@@ -572,11 +572,23 @@ func buildFleetServerConnStr(cfg fleetServerConfig) (string, error) {
 
 func kibanaFetchPolicy(cfg setupConfig, client *kibana.Client, streams *cli.IOStreams) (*kibanaPolicy, error) {
 	var policies kibanaPolicies
-	err := performGET(cfg, client, "/api/fleet/agent_policies", &policies, streams.Err, "Kibana fetch policy")
-	if err != nil {
-		return nil, err
+	params := url.Values{}
+	page := 1
+	for {
+		params.Set("page", strconv.Itoa(page))
```
Comment (ycombinator) [inline internal/pkg/agent/cmd/container.go:631]: Now that we are paginating, Agent could make multiple HTTP requests to Kibana. Should we consider passing the `per_page` parameter in the request with a value something higher than the default (20) to reduce the number of pagination requests?  I looked at telemetry data and 99% of Fleet deployments have < 35 policies ([viz](https://stack-telemetry.elastic.dev/app/r/s/KdU6Z)).  So maybe we should pass `per_page=35` as part of this request?

Alternatively, we should probably add a Kibana Fleet API that allows finding a policy by name to avoid requesting all policies and then trying to find one that matches the name?  That would push the search burden to Elasticsearch, which would be way more efficient.

Comment (ycombinator) [reply internal/pkg/agent/cmd/container.go:631]: cc: @kpollich @cmacknz

Comment (nimarezainia) [reply internal/pkg/agent/cmd/container.go:631]: Agree with @ycombinator here. Asking for a list of policies to search for a name is probably left over from the early days. It make more sense now to add the API which does a lookup by name which would be much more efficient overall.

@kpollich @cmacknz @nchaulet is this Fleet API challenging to add?

Comment (nimarezainia) [reply internal/pkg/agent/cmd/container.go:631]: btw despite officially supporting only 1000 polices we see user with upwards of 10s of thousands of these policies configured.

Comment (cmacknz) [reply internal/pkg/agent/cmd/container.go:631]: I would bump the policies per page to 50, and we can separately expose the ability to use https://www.elastic.co/docs/api/doc/kibana/operation/operation-get-fleet-agent-policies-agentpolicyid to get the policy by ID.

We want to make sure the fix here lands in 8.19.10 with FF EOD tomorrow Jan 6 to solve a SEV-1 support case.

Comment (cmacknz) [reply internal/pkg/agent/cmd/container.go:631]: > we can separately expose the ability to use https://www.elastic.co/docs/api/doc/kibana/operation/operation-get-fleet-agent-policies-agentpolicyid to get the policy by ID.

To be extra clear - this can be a separate PR if adding this is not completely trivial e.g. if @michel-laterman  can wire it up in an hour and still hit FF it is worth doing here but if it's more than that we'll do it separately.

Comment (nchaulet) [reply internal/pkg/agent/cmd/container.go:631]: > Agree with @ycombinator here. Asking for a list of policies to search for a name is probably left over from the early days. It make more sense now to add the API which does a lookup by name which would be much more efficient overall.
@kpollich @cmacknz @nchaulet is this Fleet API challenging to add?

It should already possible to do using the `kuery` and a kql search in here, but if the search need to be on the id using the get by id API seems a better option

Comment (michel-laterman) [reply internal/pkg/agent/cmd/container.go:631]: I've changed to using `kuery` for most searches; fleet-server uses the get by id API - but falls back to a `kuery` search for the default fleet-server policy if it fails (including a 404 response)

**Review by ycombinator — DISMISSED** [review]

File: internal/pkg/agent/cmd/container.go [hunk 4]
```diff
@@ -570,25 +571,37 @@ func buildFleetServerConnStr(cfg fleetServerConfig) (string, error) {
...
-		}
-		policy, err := findPolicy(cfg, policies.Items)
-		if err == nil {
-			return policy, nil
-		}
-		if page*policies.PerPage > policies.Total {
-			return nil, err
-		}
-		page++
+	params.Set("kuery", "name: "+cfg.Fleet.TokenPolicyName)
```
Comment (nchaulet) [inline internal/pkg/agent/cmd/container.go]: I think we want to search for exact match in that case the name should be quoted `name:"NAME_SEARCH"`

File: internal/pkg/agent/cmd/container.go [hunk 5]
```diff
@@ -570,25 +571,37 @@ func buildFleetServerConnStr(cfg fleetServerConfig) (string, error) {
...
+	if err != nil {
+		return nil, err
+	}
+	// successful lookup
+	if len(policies.Items) > 0 {
+		return &policies.Items[0], nil
 	}
+
+	// fallback to default flag
+	params.Set("kuery", "is_default: true")
```
Comment (nchaulet) [inline internal/pkg/agent/cmd/container.go]: Should we search for `is_default_fleet_server: true` first?

Comment (michel-laterman) [reply internal/pkg/agent/cmd/container.go]: No, the `findPolicy` method we're replacing matches by name, then falls back; we want to keep the same behaviour

Comment (nchaulet) [reply internal/pkg/agent/cmd/container.go]: For the fallback should it search for is_default_fleet_server too? 
```
} else if cfg.FleetServer.Enable {
			if policy.IsDefaultFleetServer {
				return &policy, nil
			}
		} else {
```

Comment (michel-laterman) [reply internal/pkg/agent/cmd/container.go]: Already handled in `kibanaFetchFleetServerPolicy`

Comment (cmacknz) [reply internal/pkg/agent/cmd/container.go]: Also, we should log or print that we are falling back to the default policy

Comment (michel-laterman) [reply internal/pkg/agent/cmd/container.go]: I'll add statements

File: changelog/fragments/1767391687-Container-entrypoint-searches-for-policy.yaml [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+# - enhancement: extends functionality but does not break or fix existing behavior
+# - feature: new functionality
+# - known-issue: problems that we are aware of in a given version
+# - security: impacts on the security of a product or a user’s deployment.
+# - upgrade: important information for someone upgrading from a prior version
+# - other: does not fit into any of the other categories
+kind: bug-fix
+
+# Change summary; a 80ish characters long description of the change.
+summary: Container entrypoint searches for Kibana policy
```
Comment (cmacknz) [inline changelog/fragments/1767391687-Container-entrypoint-searches-for-policy.yaml]:
```suggestion
summary: Fix FLEET_TOKEN_POLICY_NAME environment variable for the container command to handle cases where there are more than 25 agent policies available.
```

**Comment by cmacknz** [comment]
Now that we've fixed this, I think we are going to have the exact same bug with the call to get the enrollment token which is also paginated and there is one per policy.

https://github.com/elastic/elastic-agent/blob/4ddf10a43841b3e19f111f63baf6c3cf538c07ae/internal/pkg/agent/cmd/container.go#L607-L612

https://www.elastic.co/docs/api/doc/kibana/operation/operation-get-fleet-enrollment-api-keys

File: internal/pkg/agent/cmd/container.go [hunk 7]
```diff
@@ -1226,3 +1233,46 @@ func ackFleet(ctx context.Context, client fleetclient.Sender, agentID string) er
 		}
 	}, &backoff.ConstantBackOff{Interval: retryInterval})
 }
+
+// kibanaFetchFleetServerPolicy is used to gather the fleet-server policy from Kibana, first by a direct ID, lookup and if that fails by checking the is_default_fleet_server flag.
+func kibanaFetchFleetServerPolicy(cfg setupConfig, client *kibana.Client, errOut io.Writer) (*kibanaPolicy, error) {
```
Comment (cmacknz) [inline internal/pkg/agent/cmd/container.go]: Why does this need to be duplicated? It looks very similar in implementation to the main `kibanaFetchPolicies`?

Comment (cmacknz) [reply internal/pkg/agent/cmd/container.go]: Just the 404 part of it could be a function argument if that is the only difference.

**Comment by cmacknz** [comment]
The definition of done for this needs to be that we can enroll a containerized agent into an agent policy specified by name when we have manually ensured there are 25+ agent policies in the target cluster.

File: internal/pkg/agent/cmd/container.go [hunk 8]
```diff
@@ -601,21 +602,23 @@ func kibanaFetchPolicy(cfg setupConfig, client *kibana.Client, streams *cli.IOSt
...
 	}
+	fmt.Fprintf(streams.Out, "Fallback search for default policy found id: %s\n", policies.Items[0].ID)
 	return &policies.Items[0], nil
 }
 
 func kibanaFetchToken(cfg setupConfig, client *kibana.Client, policy *kibanaPolicy, streams *cli.IOStreams, tokenName string) (string, error) {
 	var keys kibanaAPIKeys
-	err := performGET(cfg, client, "/api/fleet/enrollment_api_keys", &keys, streams.Err, "Kibana fetch token")
+	params := url.Values{}
+	params.Set("kuery", fmt.Sprintf("name: %q and policy_id: %q", tokenName, policy.ID))
```
Comment (nchaulet) [inline internal/pkg/agent/cmd/container.go]: I think there may be an issue searching by name like this, token name contains a uuid to avoid conflict, that was stripped in the previous logic not sure, this is doable with a kuery

Comment (michel-laterman) [reply internal/pkg/agent/cmd/container.go]: I'm not able to get kuery working with the `/api/fleet/enrollment_api_keys` endpoint at all manually

File: testing/integration/ess/container_cmd_test.go [hunk 9]
```diff
@@ -811,3 +811,72 @@ func setAgentMonitoringRuntime(t *testing.T, info *define.Info, policyID string,
...
+		"KIBANA_FLEET_USERNAME=" + info.KibanaClient.Connection.Username,
+		"KIBANA_FLEET_PASSWORD=" + info.KibanaClient.Connection.Password,
+		"STATE_PATH=" + agentFixture.WorkDir(),
+	}
+	cmd, agentOutput := prepareAgentCMD(t, ctx, agentFixture, []string{"container"}, env)
+	t.Logf(">> running binary with: %v", cmd.Args)
+	err = cmd.Start()
+	require.NoError(t, err)
+
+	require.Eventuallyf(t, func() bool {
```
Comment (cmacknz) [inline testing/integration/ess/container_cmd_test.go]: Can you add a stronger success criteria than just being healthy? For example this would succeed if the agent remained standalone.

We can at least verify the agent is managed from the status output, it'd be ideal if we can verify the policy ID too but I don't want to scope creep this anymore by adding that into status.

File: changelog/fragments/1767391687-Container-entrypoint-searches-for-policy.yaml [hunk 10]
```diff
@@ -0,0 +1,32 @@
...
+# - enhancement: extends functionality but does not break or fix existing behavior
+# - feature: new functionality
+# - known-issue: problems that we are aware of in a given version
+# - security: impacts on the security of a product or a user’s deployment.
+# - upgrade: important information for someone upgrading from a prior version
+# - other: does not fit into any of the other categories
+kind: bug-fix
+
+# Change summary; a 80ish characters long description of the change.
+summary: Fix FLEET_TOKEN_POLICY_NAME environment variable for the container command to handle cases where there are more than 20 agent policies available.
```
Comment (cmacknz) [inline changelog/fragments/1767391687-Container-entrypoint-searches-for-policy.yaml:14]:
```suggestion
summary: Fix FLEET_TOKEN_POLICY_NAME environment variable for the container command to handle cases where there are more than 25 agent policies available.
```

I'm pretty sure this is my own typo 🙃

Comment (michel-laterman) [reply changelog/fragments/1767391687-Container-entrypoint-searches-for-policy.yaml:14]: Nope, you put 25, however the default page size is 20

File: internal/pkg/agent/cmd/container.go [hunk 11]
```diff
@@ -1226,3 +1258,62 @@ func ackFleet(ctx context.Context, client fleetclient.Sender, agentID string) er
 		}
 	}, &backoff.ConstantBackOff{Interval: retryInterval})
 }
+
+// kibanaFetchFleetServerPolicy is used to gather the fleet-server policy from Kibana, first by a direct ID, lookup and if that fails by checking the is_default_fleet_server flag.
+func kibanaFetchFleetServerPolicy(cfg setupConfig, client *kibana.Client, streams *cli.IOStreams) (*kibanaPolicy, error) {
```
Comment (cmacknz) [inline internal/pkg/agent/cmd/container.go:1276]: I would still like less duplication between this and the non-Fleet Server case if we can manage it. The integration test doesn't cover any of this code as is.

File: testing/integration/ess/container_cmd_test.go (hunk 9 above)
Comment (michel-laterman) [reply testing/integration/ess/container_cmd_test.go]: Easy to do fleet-connection, but I don't see policy_id as a part of the `status` output

**Comment by michel-laterman** [comment]
When I 1st ran the integration test locally, and had the token fetching using `name:` within the kuery the test test failed, so we know that if the enrollment fails the test fails. But i'm adding stronger verification.

I'll try to deduplicate a bit of the stuff around fetching the fleet-server policy ID, but I don't see a simple way to refactor the specific call to gey by policy id out (unless we're OK with having a few repeated 404s)

**Comment by BasileMartin** [comment]
Hello team, on the Internal Escalation Slack channel related to this Bug, @cmacknz commented that it would be possible to have a snapshot for the customer to test. Would this snapshot work for version 9.X?

**Comment by michel-laterman** [comment]
@BasileMartin, once the relevant backport has been merged the next produced snapshot will have the change
