### PR TITLE
Fix state store SetAction panic

### LINKED ISSUE #5434: Agent panics when trying to persist a `nil` action
When the agent tries to auto unenroll due too many authentication failures, the unenroll handler sets the action to `nil` before saving it. However the state store panics when setting a `nil` action.

 - the handler sets the action to `nil`:
   - https://github.com/elastic/elastic-agent/blob/b4877f52a39c53591634394be57e156d79ed57e0/internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go#L86-L89
 - the handler tries to save the action
   - https://github.com/elastic/elastic-agent/blob/b4877f52a39c53591634394be57e156d79ed57e0/internal/pkg/agent/application/actions/handlers/handler_action_unenroll.go#L95-L101
 - the store tries to access properties of a `nil` pointer
   - https://github.com/elastic/elastic-agent/blob/b4877f52a39c53591634394be57e156d79ed57e0/internal/pkg/agent/storage/store/state_store.go#L183-L188

### PR DESCRIPTION
**Pull request by AndersonQ**
The state store SetAction did not correctly cover the case where a nil action is passed as parameter. The unenroll handler might pass a nil action if the unenroll is a auto-unenroll, that means, it does not come from fleet

Also the unenroll handler does checks for a nil state store anymore, it assumes it's valid just as it does for all other dependencies

## What does this PR do?

Fixes the state store panicking when receiving an `nil` action

## Why is it important?

Panic is bad, the agent should not panic
Also the unenroll handler sets an `nil` action on the state store if the unenroll is self-inflicted. The agent auto unenroll after the 7th authentication failure against fleet.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~

## Disruptive User Impact

- N/A

## How to test this PR locally

run the tests added on the PR, all work
keep the tests, rever the changes on the state store, they will panic

## Related issues

- Closes #5434

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: internal/pkg/agent/storage/store/state_store.go [hunk 1]
```diff
@@ -169,6 +170,18 @@ func (s *StateStore) SetAction(a fleetapi.Action) {
 	s.mx.Lock()
 	defer s.mx.Unlock()
 
+	if a == nil || reflect.ValueOf(a).IsNil() {
+		s.log.Debugf("trying to set an nil '%T' action, ignoring the action", a)
```
Comment (pchila) [inline internal/pkg/agent/storage/store/state_store.go:174]: Shouldn't this rather be an error log ? We're never gonna see this in logs collected via diagnostics otherwise...

**Review by pchila — COMMENTED** [review]
Left a comment about the log level used to signal the error in action store when trying to save a nil action.
Moreover if the unenroll action is generated internally, shouldn't we fix that too somehow ?

File: internal/pkg/agent/storage/store/state_store.go (hunk 1 above)
Comment (AndersonQ) [reply internal/pkg/agent/storage/store/state_store.go:174]: no, we're supposed to ignore `nil`. I'm just fixing the panic, not changing the behaviour . We have another issue to deal with the self-unenroll https://github.com/elastic/elastic-agent/issues/5428. We can address that there

**Review by pchila — APPROVED** [review]
