### PR TITLE
make policy change handler try all fleet hosts before failing

### LINKED ISSUE #1328: Agent fails to update new Fleet Server hosts if the first host fails
The Elastic Agent fails to update the fleet-server hosts when the first host is unreachable.

### Steps to Reproduce:

1. configure fleet-server hosts to have 2 hosts. The first must NOT work, the second should work. (Suggestion, make the first host be `https://localhost:8220`)
1. I enroll agent by using the working fleet-server URL, the second one
1. the agent successfully installs
2. The agent shows unhealthy on fleet-ui
3. in the agent logs, a error log like the following is found
```
{"log.level":"error","@timestamp":"2022-09-27T13:38:46.667Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":202},"message":"failed to dispatch actions, error: fail to communicate with updated API client hosts: Get \"https://localhost:8220/api/status?\": dial tcp 127.0.0.1:8220: connect: connection refused","ecs.version":"1.6.0"}
```

### Affected versions

- Version: 8.2.2, 8.6-SNAPSHOT (2b6cfdc0a764529633f55ea51cd3405232af3ebe)
- Operating System: all
- Discuss Forum URL: N/A

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Fix how the agent handles fleet-server hosts.

**It changes the fleet-server client to:**
 - when creating a new client:
   - succeed if at least one host is health
   - shuffle the hosts, avoiding all the agents reacing to the same fleet-server on the first request
 - makes `(remote.*Client).Send` try all the hosts before failing, returning the last error if all hosts fail
   - if debug logs are enabled, `Send` will log each error as with debug level
 - modifies `remopte.requestClient`:
   - now `requestClient` holds its host
   - remove `requestFunc`
   - `(remopte.requestClient).newRequest uses the new `host` property to build the final URL for the request

## Why is it important?

Right now, when creating a new fleet API client it only verifies if one new host is reachable, therefore if the first isn't reachable, it ignore the others.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Check https://github.com/elastic/elastic-agent/issues/1328 to see how to reproduce the issue.

## Related issues

- Fixes #1328

### CODE REVIEW

File: internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go [hunk 1]
```diff
@@ -142,30 +143,50 @@ func (h *PolicyChange) handleFleetServerHosts(ctx context.Context, c *config.Con
...
+
 	ctx, cancel := context.WithTimeout(ctx, apiStatusTimeout)
 	defer cancel()
-	resp, err := client.Send(ctx, "GET", "/api/status", nil, nil, nil)
+
+	// The new client might have several fleet hosts, we need to try all of them before failing.
+	// As it's a new client, just trying
+	hostsCount := len(h.config.Fleet.Client.Hosts)
+	var resp *http.Response
+	for i := 0; i < hostsCount; i++ {
```
Comment (michalpristas) [inline internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go:154]: bringing slack discussion here:
what would you say about preferring last working fleet server first to save roundtrips.

there's also concern about making last working a bottleneck,
i think current approach makes first one bottleneck as all instances are trying to check it first. 
maybe we could just cache hosts and reshuffle on failed. e.g
if you have hosts 1,2,3,4 and 1st and 2nd fails then you create a new cached hosts array with 3,4,1,2
this would be less a bottleneck as last working may be different for every instance.

Comment (AndersonQ) [reply internal/pkg/agent/application/pipeline/actions/handlers/handler_action_policy_change.go]: I ended up sorting the list instead of making it into a queue. A Queue is a good idea though. However as it's local to each agent, and a rather small list I don't think the refactor is worth it now

File: internal/pkg/fleetapi/client/client.go [hunk 2]
```diff
@@ -87,7 +87,7 @@ func NewWithConfig(log *logger.Logger, cfg remote.Config) (*remote.Client, error
 
 // ExtractError extracts error from a fleet-server response
 func ExtractError(resp io.Reader) error {
-	// Lets try to extract a high level fleet-server error.
+	// Let's try to extract a high level fleet-server error.
```
Comment (michalpristas) [inline internal/pkg/fleetapi/client/client.go:90]: 🤣

File: internal/pkg/remote/client.go [hunk 3]
```diff
@@ -26,26 +30,25 @@ const (
...
+// stay simple and specifics should be implemented in external action instead of adding new methods
+// to the client. For authenticated calls or sending fields on every request, create a custom RoundTripper
+// implementation that will take care of the boilerplate.
 type Client struct {
-	log     *logger.Logger
-	lock    sync.Mutex
-	clients []*requestClient
-	config  Config
+	log      *logger.Logger
+	clientMu sync.Mutex
```
Comment (michalpristas) [inline internal/pkg/remote/client.go:49]: nit: Mu is the sound cow makes, i'd prefer clientLock

File: internal/pkg/remote/client.go [hunk 4]
```diff
@@ -97,9 +100,12 @@ func NewWithConfig(log *logger.Logger, cfg Config, wrapper wrapperFunc) (*Client
 	}
 
 	hosts := cfg.GetHosts()
-	clients := make([]*requestClient, len(hosts))
-	for i, host := range cfg.GetHosts() {
-		connStr, err := urlutil.MakeURL(string(cfg.Protocol), p, host, 0)
+	hostCount := len(hosts)
+	log.With("hosts", hosts).Debugf(
+		"creating remote client with %d hosts", hostCount, hosts)
```
Comment (michalpristas) [inline internal/pkg/remote/client.go:105]: no placeholder for hosts it will be appended in an ugly way, they are also included in a separate field, so maybe we could save some bytes

File: internal/pkg/remote/client.go [hunk 5]
```diff
@@ -155,45 +161,58 @@ func (c *Client) Send(
...
+	var req *http.Request
+	var resp *http.Response
 
-	// Add generals headers to the request, we are dealing exclusively with JSON.
-	// Content-Type / Accepted type can be override from the called.
-	req.Header.Set("Content-Type", "application/json")
-	req.Header.Add("Accept", "application/json")
-	// This header should be specific to fleet-server or remove it
-	req.Header.Set("kbn-xsrf", "1") // Without this Kibana will refuse to answer the request.
+	c.sortClients()
```
Comment (michalpristas) [inline internal/pkg/remote/client.go:171]: not sure we should shuffle arrays with each request, it adds unnecessary CPU cycles. maybe it would be better to shuffle on error

File: internal/pkg/remote/client.go [hunk 6]
```diff
@@ -155,45 +161,58 @@ func (c *Client) Send(
...
-	requester.lastUsed = time.Now().UTC()
+		requester.lastUsed = time.Now().UTC()
+
+		resp, err = requester.client.Do(req.WithContext(ctx))
+		if err != nil {
+			requester.lastErr = err
+			requester.lastErrOcc = time.Now().UTC()
+
+			// Using debug level as the error is only relevant if all clients fail.
+			c.log.With("error", err).Debugf("requester %d/%d to host %s errored",
```
Comment (michalpristas) [inline internal/pkg/remote/client.go:205]: this approach is fine, we could also do multiple errors and return if all fails so we have context right away without a need to ask for debug logs.
last error may not be the one which moves us forward with SDH investigation

**Review by michalpristas — APPROVED** [review]
Change looks good, 
please address issues as you like some are just nits, but shuffling i see as something worth thinking about. You can also do benchmark to see the impact

File: internal/pkg/remote/client.go (hunk 5 above)
Comment (AndersonQ) [reply internal/pkg/remote/client.go:172]: Sorting on each request will ensure we keep the previous behavior, preferring the no-error last used host to use next. Besides the number of fleet-server hosts are so small, that it's negligible the overhead to sort them.

Comment (aleksmaus) [reply internal/pkg/remote/client.go:172]: Could possibly optimize skipping sorting if already known to be sorted before.

File: internal/pkg/remote/client.go [hunk 7]
```diff
@@ -201,9 +202,12 @@ func (c *Client) Send(
 			requester.lastErr = err
 			requester.lastErrOcc = time.Now().UTC()
 
-			// Using debug level as the error is only relevant if all clients fail.
-			c.log.With("error", err).Debugf("requester %d/%d to host %s errored",
+			msg := fmt.Sprintf("requester %d/%d to host %s errored",
 				i, len(c.clients), requester.host)
+			multiErr = fmt.Errorf("%s: %s: %s", msg, err, multiErr)
```
Comment (michalpristas) [inline internal/pkg/remote/client.go:207]: this feels hacky, i'd prefer https://github.com/hashicorp/go-multierror

**Review by michalpristas — APPROVED** [review]
i'd still prefer less frequent sorting but i don't put it as a blocker.
also please consider using go-multierror as mentioned in a comment

other than that :shipit:

File: internal/pkg/remote/client.go (hunk 5 above)
Comment (AndersonQ) [reply internal/pkg/remote/client.go:172]: it needs to be sorted every time because the sorting conditions change. Every time a host is used it loses priority, thus a new sorting is required.

It isn't much different from the original code that would do extensive search on each call to `Send`. Besides the host list is so small that i's negligible the impact on performance.
