### PR TITLE
otel(elasticmonitoringreceiver): account for HTTP request-level retry errors in docs failed metric

### LINKED ISSUE #12522: [Elasticsearch exporter] Elasticsearch exporter doesn't report retries for http status errors
When a bulk request returns an http error status (e.g. 502) that is listed in the `retry_on_status` configuration field, the exporter appears to retry the request, but the metric `otelcol.elasticsearch.docs.retried` does not report any documents retried. (When a retryable error is returned as a _document_-level status of a successful bulk request, then it is included in the metrics as expected.)

### PR DESCRIPTION
**Pull request by mauri870**
## What does this PR do?

Adds `otelcol.elasticsearch.docs.retried_http_request` to the set of OTel metrics that map to `beat.stats.libbeat.output.events.failed` in the monitoring receiver. This new metric comes from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/46770 that landed in contrib v0.149.0.

Previously, only `otelcol.elasticsearch.docs.retried` (document-level retries) contributed to the `failed` field. HTTP request-level failures such as a 429 or similar error causes the entire bulk request to be retried, but the total count of retried events were not included in the beats metric. This left the `failed` counter at zero even when the exporter was actively retrying due to HTTP-level errors.

The distinction between the two failure types is the following:
- `dropped` (`otelcol_exporter_send_failed_*`) = permanent document-level failures, data loss
- `failed` (`otelcol.elasticsearch.docs.retried_http_request` + `otelcol.elasticsearch.docs.retried`) = retry attempts, no data loss but indicates pressure

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

The `failed` counter in `beat.stats.libbeat.output.events` will now be non-zero when the exporter retries due to HTTP-level errors, where it was previously always zero in that scenario. Monitoring dashboards or alerts that assumed `failed=0` means no retries will need to account for this but that assumption was incorrect to begin with.

## How to test this PR locally

```bash
cd internal/edot
GOTOOLCHAIN=go1.25.9 go test -tags integration -run TestMonitoringReceiverRequestLevelErrors ./otelcol -v
```

The test starts a real OTel collector with a mock Elasticsearch server that rejects the first three bulk requests with HTTP 429, then verifies the resulting monitoring event reflects the correct retry and delivery counts.

## Related issues

- Closes https://github.com/elastic/elastic-agent/issues/12522.

### CODE REVIEW

File: internal/edot/receivers/elasticmonitoring/convert.go [hunk 1]
```diff
@@ -106,6 +107,8 @@ func addValue(metrics *exporterMetrics, name string, value int64) {
 		add(&metrics.failedMetrics, &value)
 	case otelDocsProcessedKey:
 		add(&metrics.docsProcessed, &value)
+	case otelDocsRetriedHTTPRequest:
+		fallthrough
 	case otelDocsRetriedKey:
```
Comment (swiatekm) [inline internal/edot/receivers/elasticmonitoring/convert.go]: Why not

```suggestion
    case otelDocsRetriedKey, otelDocsRetriedHTTPRequest:
```

**Review by swiatekm — DISMISSED** [review]
LGTM, one nit about fallthrough in a switch statement.

File: internal/edot/receivers/elasticmonitoring/convert.go (hunk 1 above)
Comment (mauri870) [reply internal/edot/receivers/elasticmonitoring/convert.go]: Forgot that we can do it this way, thanks!

**Review by swiatekm — DISMISSED** [review]

**Review by michel-laterman — APPROVED** [review]
