### PR TITLE
Ensure current runtime stops before new runtime starts

### LINKED ISSUE #13336: [coordinator-status-accuracy] Late STOPPED event can evict active runtime and corrupt reported agent health
### 1. Late `STOPPED` from an old runtime can delete the active runtime entry for the same component ID (high)

**Priority:** 1 (permanent/incorrect state risk)

**Location**
- `pkg/component/runtime/manager.go:906-914`
- `pkg/component/runtime/manager.go:782-800`
- `pkg/component/runtime/runtime.go:135-147`
- `pkg/component/runtime/manager.go:672-675`
- `pkg/component/runtime/manager.go:949-962`

**Evidence**
`stateChanged` deletes from `m.current` by component ID only when `shuttingDown && latest.State == STOPPED`:

```go
// pkg/component/runtime/manager.go:906-914
shutdown := state.shuttingDown.Load()
if shutdown && latest.State == client.UnitStateStopped {
    m.currentMx.Lock()
    delete(m.current, state.id)
    m.currentMx.Unlock()
    exit = true
}
```

`update` waits for stop completion, then starts new components:

```go
// pkg/component/runtime/manager.go:782-800
for _, existing := range stop {
    _ = existing.stop(teardown, model.Signed)
    go func(state *componentRuntimeState) {
        err := m.waitForStopped(state)
        ...
        stoppedWg.Done()
    }(existing)
}
stoppedWg.Wait()
// then starts new components
```

A runtime state watcher can still process events while shutdown is in progress:

```go
// pkg/component/runtime/runtime.go:140-147
case componentState := <-s.runtime.Watch():
    ...
    if s.manager.stateChanged(s, componentState) {
        runtimeRunner.Stop()
    }
```

**What is wrong**
Deletion is keyed only by `state.id`, not by runtime instance identity. If a late `STOPPED` event is delivered from an older/shutting-down runtime instance after a replacement instance has already been stored in `m.current[state.id]`, the late event can remove the new active entry.

**Why it matters (user-visible impact)**
When the active runtime entry is removed, manager lookups used by normal operations fail (`invalid token`/`ErrNoUnit`) via paths like `getRuntimeFromToken` and `getRuntimeFromUnit` (`manager.go:672-675`, `949-962`). This can surface as incorrect coordinator health (degraded/failed/updating behavior) and inconsistent status for `elastic-agent status`/Fleet during policy changes or component restarts.

**State transition sequence (normal operations)**
1. Policy change triggers component restart/replacement flow.
2. Old runtime enters shutdown and eventually emits `STOPPED`.
3. New runtime instance for same component ID becomes current.
4. Late `STOPPED` from old instance is processed.
5. `delete(m.current, state.id)` removes current entry for that ID, even if it belongs to the new instance.
6. Follow-on check-ins/actions/lookup paths observe missing runtime and health becomes incorrect/degraded.

**Suggested fix direction**
Guard deletion by ownership/identity before removing map entry (delete only when `m.current[state.id]` still points to the same `state` instance). Example approach:
- hold `m.currentMx`
- compare `curr := m.current[state.id]`
- `if curr == state { delete(m.current, state.id) }`

This preserves cleanup for the old instance while preventing eviction of a newer active instance.

**Failing test to add (repro)**
Add a unit test under `pkg/component/runtime/manager_test.go` that simulates two runtime state objects with the same component ID and a late `STOPPED` from the old one:

```go
func TestStateChanged_DoesNotDeleteNewInstanceOnLateStopped(t *testing.T) {
    m := &Manager{
        current:       map[string]*componentRuntimeState{},
        subscriptions: map[string][]*Subscription{},
    }

    old := &componentRuntimeState{id: "comp-a"}
    old.shuttingDown.Store(true)
    oldComp := component.Component{ID: "comp-a"}
    old.currComp.Store(&oldComp)

    neu := &componentRuntimeState{id: "comp-a"}
    newComp := component.Component{ID: "comp-a"}
    neu.currComp.Store(&newComp)

    m.current["comp-a"] = neu

    _ = m.stateChanged(old, ComponentState{State: client.UnitStateStopped})

    require.Same(t, neu, m.current["comp-a"]) // should remain; currently can be deleted
}
```

## Audited paths that looked correct
- `internal/pkg/agent/application/coordinator/coordinator_state.go:160-165` correctly ignores older component updates using `LastConfiguredAt` ordering guard.
- `internal/pkg/agent/application/coordinator/coordinator_state.go:182-189` removes stopped components from coordinator aggregate state.
- `internal/pkg/agent/application/monitoring/readiness.go` and `/liveness` coordinator-activity checks are internally consistent with their endpoint contracts.

## Notes on de-duplication
- Checked `/tmp/previous-findings.json` (contains only #13305, different issue).
- Checked existing open `"[coordinator-status-accuracy]"` issue titles; this finding is distinct from #13305.

> [!NOTE]
> <details>
> <summary>🔒 Integrity filtering filtered 14 items</summary>
>
> Integrity filtering activated and filtered the following items during workflow execution.
> This happens when a tool call accesses a resource that does not meet the required integrity or secrecy level of the workflow.
>
> - resource:search_pull_requests (`search_pull_requests`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#12511](https://github.com/elastic/elastic-agent/issues/12511) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#13082](https://github.com/elastic/elastic-agent/issues/13082) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#12486](https://github.com/elastic/elastic-agent/issues/12486) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#12885](https://github.com/elastic/elastic-agent/issues/12885) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#8341](https://github.com/elastic/elastic-agent/issues/8341) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#5386](https://github.com/elastic/elastic-agent/issues/5386) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#6800](https://github.com/elastic/elastic-agent/issues/6800) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#13191](https://github.com/elastic/elastic-agent/issues/13191) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#9259](https://github.com/elastic/elastic-agent/issues/9259) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#11037](https://github.com/elastic/elastic-agent/issues/11037) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#6784](https://github.com/elastic/elastic-agent/issues/6784) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - [#8064](https://github.com/elastic/elastic-agent/issues/8064) (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
> - issue:elastic/elastic-agent#unknown (`search_issues`: has lower integrity than agent requires. The agent cannot read data with integrity below "approved".)
>
> </details>

---
[What is this?](https://ela.st/github-ai-tools) | [From workflow: Sweeper: Coordinator and Health Status Accuracy](https://github.com/elastic/elastic-agent/actions/runs/23639526954)

Give us feedback! React with 🚀 if perfect, 👍 if helpful, 👎 if not.
> - [x] expires  on Apr 3, 2026, 9:39 AM UTC

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Ensures that when components transition between runtimes (process↔OTel), the old runtime fully stops the component before the new runtime starts it.
                                                                                                                          
Previously, `updateManagersWithConfig` sent updates to both the runtime manager and OTel manager simultaneously. When a component moved from process to OTel (or vice versa), the old instance and new instance would run concurrently for up to 30 seconds until the old one was killed. Both instances would compete over shared resources like the filestream registry, log file cursors, and network ports.

This PR changes `updateManagersWithConfig` to detect cross-runtime transitions and defer the receiving manager's update. Both managers receive an immediate update that excludes the transitioning components (stopping the old instances without starting new ones). A `pendingManagerUpdate` is stored for each transition direction. When the coordinator's main loop processes the STOPPED state for the old instance, it applies the deferred update to start the new instance.

## Why is it important?

When both old and new instances of the same component run simultaneously during a runtime transition, the filestream input's registry state becomes corrupted, the new instance reads a stale cursor position from disk and re-ingests log lines that the old instance already published but hadn't flushed. This was observed as 41+ duplicate monitoring log documents on Windows in `TestMonitoringNoDuplicates`.

The fix also eliminates the race condition described in #13336, where a late STOPPED event from an old runtime instance could delete the new active instance from the runtime manager's map. By guaranteeing the old instance is fully stopped before the new one is created, there is no window where both exist with the same component ID.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~ (unit test coverage)

## Disruptive User Impact

None

## How to test this PR locally

1. Run filestream in the process runtime (default currently, will change soon)
2. Update the configuration to switch filestream to the OTEL runtime
3. Observe the logs and also see that no duplicate logs occur (does require logs to be concurrently written while the transition is happening).

## Related issues

- Closes #13336

### CODE REVIEW

**Comment by swiatekm** [comment]
This looks like a lot of additional complexity to cover a relatively rare case. Couldn't we simply restart instead if we detect this situation? The existing runtime will shut down in an orderly manner, and the new one will start after the agent restart.

**Comment by blakerouse** [comment]
@swiatekm We cannot do that. This is required to allow switching between process runtime and OTEL runtime. Without it there is no guarantee that the process runtime as completely stopped and flushed it registry to the disk. Only once that has happened will the OTEL filebeat receiver start to read the registry. This is clear to see in my PR that enables filebeat and `TestMonitoringNoDuplicates` fails consistently. It is also the case going from OTEL back to process, same issue of registry access.

I actually don't think this adds much complexity, being that it happens in the same flow as the update config. No new locks or anything needed to be added. It just a matter of waiting until the current one stops and then a new one is started.

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 1]
```diff
@@ -1937,21 +1958,136 @@ func (c *Coordinator) refreshComponentModel(ctx context.Context) (err error) {
...
-	c.logger.With("components", runtimeModel.Components).Debug("Updating runtime manager model")
-	c.runtimeMgr.Update(*runtimeModel)
-	c.logger.With("components", otelModel.Components).Debug("Updating otel manager model")
-	if len(otelModel.Components) > 0 {
-		componentIDs := make([]string, 0, len(otelModel.Components))
-		for _, comp := range otelModel.Components {
+
+	// Detect components moving between runtimes and build current models
+	// that exclude the transitioning components in a single pass per model.
+	currentRuntime := make(map[string]component.RuntimeManager, len(c.state.Components))
```
Comment (swiatekm) [inline internal/pkg/agent/application/coordinator/coordinator.go:2084]: This is a pretty long function in terms of line count, so it'd be nice if all this slice and map shuffling could be put into a helper.

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 2]
```diff
@@ -379,6 +388,18 @@ type Coordinator struct {
 	// value that is sent to the runtime manager).
 	componentModel []component.Component
 
+	// pendingManagerUpdates holds deferred manager updates waiting for
+	// components in the old runtime to reach STOPPED before the new runtime
+	// starts them. There can be up to two entries when components move in
+	// both directions (process-to-OTel and OTel-to-process) simultaneously.
+	pendingManagerUpdates []pendingManagerUpdate
```
Comment (swiatekm) [inline internal/pkg/agent/application/coordinator/coordinator.go]: If I understand this correctly, we can only have at most two of these at any given time - one for each runtime. Could we make this a map keyed by runtime to make this clearer? Without looking at the logic, you might expect that more updates could accumulate in this slice.

**Review by swiatekm — COMMENTED** [review]
This doesn't look too bad after all. I have a question about tracking pending updates and a nitpick about function size.

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 2 above)
Comment (cmacknz) [reply internal/pkg/agent/application/coordinator/coordinator.go]: +1 I had the same thought reading the description

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 3]
```diff
@@ -1937,21 +1958,136 @@ func (c *Coordinator) refreshComponentModel(ctx context.Context) (err error) {
...
+			movingToProcess[comp.ID] = true
+		} else {
+			currentRuntimeComponents = append(currentRuntimeComponents, comp)
+		}
+	}
+	currentRuntimeModel.Components = currentRuntimeComponents
+
+	// Send current models to both managers — this stops old instances
+	// without starting new ones for transitioning components.
+	c.logger.With("components", currentRuntimeModel.Components).Debug("Updating runtime manager model")
```
Comment (cmacknz) [inline internal/pkg/agent/application/coordinator/coordinator.go]: The full components list includes the source config doesn't it? That can contain secrets so we can't log it. You can log the component IDs which is probably all you need to debug this, maybe that plus the target runtimes.

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 4]
```diff
@@ -1937,21 +1958,136 @@ func (c *Coordinator) refreshComponentModel(ctx context.Context) (err error) {
...
+				c.logger.Infof("All OTel-to-process transitioning components have stopped, applying runtime update: %v", maps.Keys(movingToProcess))
+				c.runtimeMgr.Update(fullRuntimeModel)
+			},
+		})
+	}
+}
+
+// applyOTelUpdate sends an update to the OTel manager.
+func (c *Coordinator) applyOTelUpdate(components []component.Component) {
+	c.logger.With("components", components).Debug("Updating otel manager model")
```
Comment (cmacknz) [inline internal/pkg/agent/application/coordinator/coordinator.go]: Same here, we can't log all the components and their configurations safely

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 5]
```diff
@@ -1937,21 +1958,136 @@ func (c *Coordinator) refreshComponentModel(ctx context.Context) (err error) {
...
+// instances reach STOPPED, it applies the full model to the receiving
+// manager. If a new config arrives while transitions are in progress,
+// it is queued and applied once all current transitions complete.
 func (c *Coordinator) updateManagersWithConfig(model *component.Model) {
+	// Cancel any pending updates from a previous call. A new model supersedes
+	// whatever was waiting.
+	// If there are pending transitions from a previous update, queue this
+	// model to be applied once they complete. Applying it now could start
+	// new instances while old ones are still shutting down.
+	if len(c.pendingManagerUpdates) > 0 {
```
Comment (cmacknz) [inline internal/pkg/agent/application/coordinator/coordinator.go]: This doesn't cancel pending updates, it leaves `pendingManagerUpdates` alone and updates the queued model to apply the end. I only ever see `pendingManagerUpdates` get appended to with the slice replaced when something reaches the STOPPED state.

Is there a situation where we'd have a pending update for a component that would never stop? For example if someone manages to quickly go `process -> otel -> process` can we be left with a pending update that will never happen?

Comment (cmacknz) [reply internal/pkg/agent/application/coordinator/coordinator.go]: This maybe gets clarified if you moved pendingManagerUpdates to be a map as suggested by Mikolaj below, then you'd be replacing the updates per runtime most likely instead of appending to a slice.

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 1 above)
Comment (blakerouse) [reply internal/pkg/agent/application/coordinator/coordinator.go:2084]: I moved this to a helper that returns a struct.

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 2 above)
Comment (blakerouse) [reply internal/pkg/agent/application/coordinator/coordinator.go]: I switched to a defined struct, being there is only two types (no need for a map either).

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 3 above)
Comment (blakerouse) [reply internal/pkg/agent/application/coordinator/coordinator.go]: Sorry, forgot about that. Fixed.

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 4 above)
Comment (blakerouse) [reply internal/pkg/agent/application/coordinator/coordinator.go]: Fixed.

File: internal/pkg/agent/application/coordinator/coordinator.go (hunk 5 above)
Comment (blakerouse) [reply internal/pkg/agent/application/coordinator/coordinator.go]: I did tow things to easy the worry. I clear the state when transitioning to the pending model. I also added a deadline check that is based off the StopTimeout plus a buffer. So if the transition takes longer than the deadline, then it will transition anyway. Removing in chance of it never continuing. Added a unit test to cover this as well.

**Review by swiatekm — APPROVED** [review]
