### PR TITLE
Fix clean stopping of beats on windows

### LINKED ISSUE #7756: Elastic-Agent does not allow child process to clean up during shutdown
When the Elastic-Agent is shutting down it does not wait for its child process to gracefully exit, thus not allowing the to perform the necessary clean up, which can leave active resources after all process have exited (see related issues). This happens in most, if not all platforms.

## TL;DR
When starting child process, the Elastic-Agent configures them to be forcefully killed once it's own process exits, alongside with that the shutdown process for child process is fully asynchronous, thus even if the Elastic-Agent correctly signals child process to exit, they do not have enough time to shutdown because the Elastic-Agent process exits, which makes the OS to kill all of its child process.

## The long version
When creating child process the Elastic-Agent configures them to be killed once it exits, this is handled differently on each OS, then when exiting the Elastic-Agent asynchronously signals the child process to exit and do not wait for their process to return.

When a shutdown signal is received by the Elastic-Agent, it signals the components/child process to exit:

https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/manager.go#L784-L799

The `stoppedWg` created only waits for the components to be in a stopped state, not for their actual process to exit.
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/manager.go#L845-L854

And the component gets removed from `m.current` when it starts its shutdown
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/manager.go#L906-L916

Following the code we can see `s.shuttingDown` being set to `true` and afterwards the shutdown signal being sent to the process

https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/runtime.go#L179-L188
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/command.go#L307-L315

The channel is read and the stop method called
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/command.go#L167-L170

https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/component/runtime/command.go#L412-L440

`proc.Stop()` calls `terminateCmd` that only sends the correct signal, but does not wait for the process to return
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/core/process/cmd_linux.go#L55-L57
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/core/process/cmd.go#L34-L36
There is a fix to send the correct signal on Windows instead of already killing the child process, see https://github.com/elastic/elastic-agent/pull/7738
https://github.com/elastic/elastic-agent/blob/e59769c04412df6bc9cfd645445aa81e1ee10ae2/pkg/core/process/cmd.go#L52-L58

### Linux
This is handled by setting [`Pdeathsig` in `syscall.SysProcAttr`](https://cs.opensource.google/go/go/+/refs/tags/go1.24.2:src/syscall/exec_linux.go;l=96) to `syscall.SIGKILL`. Which makes the OK send a `SIGKILL` to the child process once the parent exits.

There is an open issue in Go stating this happens when the thread that created the process exits, not the main process: https://github.com/golang/go/issues/27505

### Windows
On Windows things are a little more complicated, first a global JobObject is created at startup
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/main.go#L24
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/core/process/job_windows.go#L29-L35

Then all new process are associated with the JobObject
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/core/process/process.go#L169-L176
https://github.com/elastic/elastic-agent/blob/1e2a3872afd01de88cf1a29e9fdca3d170048246/pkg/core/process/job_windows.go#L76-L99

So once the Elastic-Agent exits, all child process are killed.

## Related issues
- https://github.com/elastic/elastic-agent/issues/6875
- Draft PR with a lot of debug code and history: https://github.com/elastic/elastic-agent/pull/7624
- Draft PR to send the correct signal on Windows: https://github.com/elastic/elastic-agent/pull/7738/

## References
- https://docs.microsoft.com/en-us/windows/win32/procthread/job-objects
- https://devblogs.microsoft.com/oldnewthing/20131209-00/?p=2433
- https://stackoverflow.com/questions/34730941/ensure-executables-called-in-go-process-get-killed-when-process-is-killed
- https://gist.github.com/hallazzang/76f3970bfc949831808bbebc8ca15209
- https://learn.microsoft.com/en-us/windows/console/generateconsolectrlevent
- https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
- https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa
- https://pkg.go.dev/golang.org/x/sys/windows
- https://pkg.go.dev/os/exec
- https://cs.opensource.google/go/go/+/refs/tags/go1.24.2:src/syscall/exec_windows.go;l=245

### LINKED ISSUE #13314: [EDOT] Switching from OTEL to Process monitoring runtime on Windows causes Agent Unhealthy state
- Version: 9.2.5
- Operating System: Windows
- Discuss Forum URL:
- Steps to Reproduce
According to the SDH:
  - Windows host
  - Enroll the host with Fleet-managed Elastic Agent.
  - Enable logs and metrics monitoring for the agent host.
  - Monitoring runtime set to otel
  - Switch monitoring runtime to process

## Observed behavior

Switching monitoring from OTEL runtime to Process runtime on a Windows host causes the Elastic Agent to become Unhealthy and disables Agent logs and metrics.

In the affected environment:

- Elastic Agent is initially running with OTEL runtime monitoring without issues.
- After switching to Process runtime monitoring, Agent logs and metrics are turned off.
- The Agent reports an **Unhealthy** state and does not recover, even if moved to a different policy.
- Monitoring components fail to stop correctly, producing repeated errors.
- The only way to recover is to switch back to OTEL runtime monitoring.

## Error details

From diagnostics, multiple monitoring components fail with similar errors:

```json
[
    {
        "id": "filestream-monitoring",
        "type": "filestream",
        "status": "FAILED",
        "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${FILEBEAT_GOGC:100} -E filebeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///xTEtpJ7117ppc6OYvJCaYHbDW8mLjXGe.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\filestream-monitoring: The handle is invalid.",
        "units": [
            {
                "id": "filestream-monitoring-filestream-monitoring-agent",
                "type": "input",
                "status": "FAILED",
                "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${FILEBEAT_GOGC:100} -E filebeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///xTEtpJ7117ppc6OYvJCaYHbDW8mLjXGe.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\filestream-monitoring: The handle is invalid."
            },
            {
                "id": "filestream-monitoring",
                "type": "output",
                "status": "FAILED",
                "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${FILEBEAT_GOGC:100} -E filebeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///xTEtpJ7117ppc6OYvJCaYHbDW8mLjXGe.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\filestream-monitoring: The handle is invalid."
            }
        ]
    },
    {
        "id": "beat/metrics-monitoring",
        "type": "beat/metrics",
        "status": "FAILED",
        "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///Hk6rvk9TDibMPcDvpl0jkLE-qDsHWVYL.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\beat\\metrics-monitoring: The handle is invalid.",
        "units": [
            {
                "id": "beat/metrics-monitoring",
                "type": "output",
                "status": "FAILED",
                "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///Hk6rvk9TDibMPcDvpl0jkLE-qDsHWVYL.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\beat\\metrics-monitoring: The handle is invalid."
            },
            {
                "id": "beat/metrics-monitoring-metrics-monitoring-beats",
                "type": "input",
                "status": "FAILED",
                "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///Hk6rvk9TDibMPcDvpl0jkLE-qDsHWVYL.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\beat\\metrics-monitoring: The handle is invalid."
            }
        ]
    },
    {
        "id": "http/metrics-monitoring",
        "type": "http/metrics",
        "status": "FAILED",
        "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///akSPbdqgaHaTY0_J01-dsfYK6JpMz2zn.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\http\\metrics-monitoring: The handle is invalid.",
        "units": [
            {
                "id": "http/metrics-monitoring-metrics-monitoring-agent",
                "type": "input",
                "status": "FAILED",
                "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///akSPbdqgaHaTY0_J01-dsfYK6JpMz2zn.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\http\\metrics-monitoring: The handle is invalid."
            },
            {
                "id": "http/metrics-monitoring",
                "type": "output",
                "status": "FAILED",
                "message": "Failed: failed to stop process C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\components\\agentbeat.exe metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.enabled=true -E management.restart_on_output_change=true -E logging.level=info -E logging.to_stderr=true -E gc_percent=${METRICBEAT_GOGC:100} -E metricbeat.config.modules.enabled=false -E logging.event_data.to_stderr=true -E logging.event_data.to_files=false -E http.enabled=true -E http.host=npipe:///akSPbdqgaHaTY0_J01-dsfYK6JpMz2zn.sock -E path.data=C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.2.5-df1a8d\\run\\http\\metrics-monitoring: The handle is invalid."
            }
        ]
    }
]
```

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes graceful shutdown of component processes (beats) on Windows when elastic-agent runs as a Windows service.

When the agent runs as a service, there is no console attached to the process. GenerateConsoleCtrlEvent(CTRL_BREAK_EVENT) silently fails in this case, so component processes never receive the shutdown signal. They're eventually killed after the 30-second grace timeout, exiting with code 1 instead of shutting down gracefully.

## Why is it important?

Without graceful shutdown, component processes (filebeat, metricbeat) are forcefully killed during runtime transitions and agent restarts on Windows. This causes the filestream registry to not be flushed to disk, which leads to duplicate log ingestion when the replacement instance re-reads from a stale cursor position.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~ (unit test coverage)

## Disruptive User Impact

None

## Related issues

- Closes #7756
- Closes #13314

### CODE REVIEW

File: pkg/core/process/cmd.go [hunk 1]
```diff
@@ -43,16 +58,97 @@ func getCmd(ctx context.Context, path string, env []string, uid, gid int, arg ..
...
+	// Attach to the child's console so we can send it CTRL_BREAK_EVENT.
+	r1, _, err := procAttachConsole.Call(uintptr(pid))
+	if r1 == 0 {
+		return fmt.Errorf("AttachConsole(%d) failed: %w", pid, err)
+	}
+
+	sendErr := windows.GenerateConsoleCtrlEvent(windows.CTRL_BREAK_EVENT, pid)
+
+	// Detach from the child's console.
+	_, _, _ = procFreeConsole.Call()
```
Comment (swiatekm) [inline pkg/core/process/cmd.go:151]: Shouldn't we log something here? Is it even possible that detaching fails?

**Review by swiatekm — APPROVED** [review]
LGTM, one question about error handling.

File: pkg/core/process/cmd.go (hunk 1 above)
Comment (blakerouse) [reply pkg/core/process/cmd.go:151]: I don't think so, being that the process is being stopped it doesn't really matter.
