### PR TITLE
fix(6023): replace list with items

### LINKED ISSUE #6023: Fleet deprecated `list` property when retrieving enrollment api keys
The `list` property in `GET /api/fleet/enrollment_api_keys` as been deprecated since 8.0.0 in favor of the `items` property

This should be changed in:

https://github.com/elastic/elastic-agent/blob/4b15e1afa8de457fe34ce35d2215180d625b4fe0/internal/pkg/agent/cmd/container.go#L954`

Related to https://github.com/elastic/ingest-dev/issues/4459

### PR DESCRIPTION
**Pull request by kaanyalti**
- Bug

## What does this PR do?

Replaces `list` with `items` from from `kibanaFetchToken` as the `list` is deprecated in the api response and will be removed.

## Why is it important?

The `list` in the api response is going to be removed in favor of `item`

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

 There shouldn't be any user impact

## How to test this PR locally

- Deploy ESS
- Build the agent by running the following command
```
SNAPSHOT=true PLATFORMS="linux/arm64" PACKAGES="docker" EXTERNAL=true mage -v package
```
- Then get the image id for any of the created elastic-agent images and run the following command
```
docker run \
  --env FLEET_ENROLL=1 \
  --env KIBANA_HOST=<KIBANA HOST> \
  --env KIBANA_USERNAME=<KIBANA USER NAME> \
  --env KIBANA_PASSWORD=<KIBANA PASSWORD> \
  --env FLEET_TOKEN_POLICY_NAME=<POLICY NAME> \
  --env FLEET_URL=<FLEET URL> \
  --rm <IMAGE ID>
```
- Validate that the agent is able to enroll

## Related issues

- Closes #6023 
- Creates #6451

### CODE REVIEW

File: testing/integration/validate_items_deprecated_list_test.go [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+type deprecatedBody struct {
+	List []testKibanaApiKey `json:"list"`
+}
+
+type newBody struct {
+	Items []testKibanaApiKey `json:"items"`
+}
+
+// TODO: Remove test after list deprecation is complete
```
Comment (kaanyalti) [inline testing/integration/validate_items_deprecated_list_test.go:29]: I would like to add an issue link to remove the link from the kibana api, if anyone knows of such an issue please comment here.

Comment (michalpristas) [reply testing/integration/validate_items_deprecated_list_test.go:36]: let's crete an issue in our repo. this change is breaking and will be removed in 9.0 
we can create a PR targeting main with skip backport right away after this one is merge, removing this test

**Review by michalpristas — APPROVED** [review]

File: testing/integration/validate_items_deprecated_list_test.go (hunk 1 above)
Comment (kaanyalti) [reply testing/integration/validate_items_deprecated_list_test.go:36]: Created this issue https://github.com/orgs/elastic/projects/979/views/23?pane=issue&itemId=92232925&issue=elastic%7Celastic-agent%7C6451
