### PR TITLE
Write internal logs under versioned home logs folder

### LINKED ISSUE #2470: Logs are missing from diagnostics bundle
For confirmed bugs, please report:
- Version: `8.8.0-SNAPSHOT` built from ff5964f57081f87c969aea47e411fd68da865731.
   ```
   $ sudo elastic-agent version
   ```

- Operating System: Linux
- Steps to Reproduce:
1. Install Agent in Standalone mode.
   ```
   sudo ./elastic-agent install
   ```

2. Get diagnostics bundle.
   ```
   sudo ./elastic-agent diagnostics
   ```
3. Look at the logs folder in the diagnostics bundle. It should contain at least one `.ndjson` log file but it is empty.
   ```
   unzip elastic-agent-diagnostics-*.zip -d diag
   ls -al diag/logs
   ```

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

This PR ensures that Elastic Agent writes its internal logs to its versioned home's `logs` folder.

## Why is it important?

When `elastic-agent diagnostics` is run, it tries to collect logs from the versioned home logs folder.  Before this PR logs were not being written to this folder so `elastic-agent diagnostics` was not collecting any Elastic Agent logs. 

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~I have commented my code, particularly in hard-to-understand areas~
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have made corresponding change to the default configuration files~
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [ ] ~I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~
- [ ] ~I have added an integration test or an E2E test~ Will be covered by https://github.com/elastic/elastic-agent/issues/1789#issuecomment-1499998621.

## Author's Checklist

Since this PR is a follow up to https://github.com/elastic/elastic-agent/pull/2456, I did test with this PR that enrolling the Elastic Agent in Fleet and changing the log level there still works as expected.  In other words, I verified that the change in this PR will not cause a regression in the bug fixed by https://github.com/elastic/elastic-agent/pull/2456.

## How to test this PR locally

1. Install Agent in Standalone mode.
   ```
   sudo ./elastic-agent install
   ```

2. Get diagnostics bundle.
   ```
   sudo ./elastic-agent diagnostics
   ```
3. Look at the logs folder in the diagnostics bundle. It should contain at least one `.ndjson` log file but it is empty.
   ```
   unzip elastic-agent-diagnostics-*.zip -d diag
   ls -al diag/logs
   ```

## Related issues

- Fixes #2470
- Follow up to https://github.com/elastic/elastic-agent/pull/2456

### CODE REVIEW

File: pkg/core/logger/logger.go [hunk 1]
```diff
@@ -140,7 +140,7 @@ func makeInternalFileOutput(cfg *Config) (zapcore.Core, error) {
 	// defaultCfg is used to set the defaults for the file rotation of the internal logging
 	// these settings cannot be changed by a user configuration
 	defaultCfg := logp.DefaultConfig(logp.DefaultEnvironment)
-	filename := filepath.Join(paths.Logs(), cfg.Beat)
+	filename := filepath.Join(paths.Home(), DefaultLogDirectory, cfg.Beat)
```
Comment (michalpristas) [inline pkg/core/logger/logger.go:143]: change line 129 as well
`cfg.Files.Path = filepath.Join(paths.Home(), DefaultLogDirectory)` may be conflicting
not sure why you have no logs though, i tested it and had logs at both location,
internal output is not listening to logging config aside from log level.
non internal is altering behavior on other logging settings

**Review by michalpristas — APPROVED** [review]
left a comment, other than that it seems ok

File: pkg/core/logger/logger.go (hunk 1 above)
Comment (ycombinator) [reply pkg/core/logger/logger.go:143]: Sorry, but what is the change that should be made to line 129?  And what's the reason for it?

> internal output is not listening to logging config aside from log level.
> non internal is altering behavior on other logging settings.

This is not strictly related to the change you're suggesting above but I'm asking more for my own understanding because I have to admit, I'm a bit confused by the terminology:

What is the purpose of the internal log output?  When is it supposed to be used and when is it not supposed to be used?  That is, when creating a logger using the `logger.New` or `logger.NewFromConfig` constructors, when is it appropriate to pass the `logInternal` argument as `true` and when should it be `false`?

Comment (ycombinator) [reply pkg/core/logger/logger.go:143]: > Sorry, but what is the change that should be made to line 129? And what's the reason for it?

@michalpristas Thanks for making the change via a3524db285e04ae832bf979059fe0d7d062d461b.  I'd like to understand the reason for it and also the other question I asked about the internal log output but that can wait until after this PR is merged.
