### PR TITLE
V2 command work dir

### LINKED ISSUE #997: V2: Agent starting multiple instances of filebeat or metricbeat and goes into tight restart loop for the beat process
Agent starting multiple instances of filebeat or metricbeat and goes into tight restart loop for the beat process.
More than 50% of agent runs fail while starting multiple beats processes due to the conflict on data path, which results in the tight restart loop for the beat.
```
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
```

This is documented here as well:
https://github.com/elastic/beats/pull/32673#issuecomment-1224863904

Running off of the latest V2 branch:
https://github.com/elastic/elastic-agent/tree/feature-arch-v2

Steps to reproduce:
1. Enroll the agent from the command line
2. Run the agent from the command line

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Includes many fixes for running the V2 architecture:

- Fix issue where a unique word directory is not used when spawning a component
- Add permissions check to spawning a component (Windows is a TODO)
- Add `user.root` variable to runtime prevention checks
- Use `user.root` variable in runtime check for Endpoint Security (as it requires root access for it to run)
- Fix log message about artifact checking to only be for upgrade (which is all artifact download is used for in V2)
- Fix quick restart of failing binaries in the command runtime (now a delay of 10 seconds is used, and can be changed in the specification for the input)
- Fix the constant logging a configuration change at INFO level (its redundant and creates un-need log messages all the time, it is now at DEBUG level)
- Don't require an input to have to have an ID defined (use type as fallback)
- Add check that input ID are unique (needed because of the type fallback)
- Add `AGENT_COMPONENT_ID` and `AGENT_COMPONENT_INPUT_TYPE` to environment when spawning command binaries. Allows early logging of a binary before it connects to the control protocol to report the component and input type in the log message.

## Why is it important?

Work towards a working V2 architecture and overall improvements of the Elastic Agent.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #997

### CODE REVIEW

File: pkg/component/component.go [hunk 1]
```diff
@@ -96,6 +103,11 @@ func (r *RuntimeSpecs) ToComponents(policy map[string]interface{}) ([]Component,
 			"major":    r.platform.Major,
 			"minor":    r.platform.Minor,
 		},
+		"user": map[string]interface{}{
```
Comment (cmacknz) [inline pkg/component/component.go:106]: Out of curiosity, what are we still using the transpiler for if we aren't doing config transformations anymore? Do we just need to do follow up surgery to completely remove it or does it need to stick around as an implementation detail?

File: pkg/component/runtime/command.go [hunk 2]
```diff
@@ -243,11 +257,26 @@ func (c *CommandRuntime) start(comm Communicator) error {
 		return nil
 	}
 	cmdSpec := c.current.Spec.Spec.Command
-	env := make([]string, 0, len(cmdSpec.Env))
+	env := make([]string, 0, len(cmdSpec.Env)+2)
```
Comment (cmacknz) [inline pkg/component/runtime/command.go:260]: Why the magic +2? Can you add a comment or make it a constant?

Comment (cmacknz) [reply pkg/component/runtime/command.go:260]: Probably the component ID and type being added below?

File: pkg/component/runtime/command.go [hunk 3]
```diff
@@ -243,11 +257,26 @@ func (c *CommandRuntime) start(comm Communicator) error {
...
 	for _, e := range cmdSpec.Env {
 		env = append(env, fmt.Sprintf("%s=%s", e.Name, e.Value))
 	}
-	proc, err := process.Start(c.current.Spec.BinaryPath, os.Geteuid(), os.Getgid(), cmdSpec.Args, env, attachOutErr)
+	env = append(env, fmt.Sprintf("%s=%s", envAgentComponentID, c.current.ID))
+	env = append(env, fmt.Sprintf("%s=%s", envAgentComponentInputType, c.current.Spec.InputType))
+	uid, gid := os.Geteuid(), os.Getgid()
+	workDir, err := c.workDir(uid, gid)
```
Comment (cmacknz) [inline pkg/component/runtime/command.go:267]: Do these paths get cleaned up somewhere?

File: pkg/utils/perm_windows.go [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+
+//go:build windows
+// +build windows
+
+package utils
+
+// HasStrictExecPerms ensures that the path is executable by the owner and that the owner of the file
+// is the same as the UID or root.
+func HasStrictExecPerms(path string, uid int) error {
+	// TODO: Need to add check on Windows to ensure that the ACL are correct for the binary before execution.
```
Comment (cmacknz) [inline pkg/utils/perm_windows.go:13]: Is this coming in this PR or do we need a follow up issue to do this?

**Review by cmacknz — COMMENTED** [review]
Looks reasonable, a few questions

File: pkg/component/component.go (hunk 1 above)
Comment (blakerouse) [reply pkg/component/component.go:106]: We need to do a cleanup to remove the transpiler rules and steps (neither are no longer used in V2). But the transpiler is still required as it performs all the variable substitution inside of the configuration for the dynamic inputs.

File: pkg/component/runtime/command.go (hunk 2 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:260]: Yes its from the extra 2 added below. I think making it a constant would pull the reason for the additional space away from the code.

File: pkg/component/runtime/command.go (hunk 3 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:267]: I forgot to add cleanup. Will add before merge.

File: pkg/utils/perm_windows.go (hunk 4 above)
Comment (blakerouse) [reply pkg/utils/perm_windows.go:13]: I will file a follow up issue so we can add it in a follow up issue. The windows code is very windows specific and will require some time with me actually on Windows to develop it.

File: pkg/component/component.go (hunk 1 above)
Comment (blakerouse) [reply pkg/component/component.go:106]: I have cleaned up the transpiler rules and steps in the latest commit.

File: pkg/component/runtime/command.go (hunk 3 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:268]: I have added the cleanup of the work directory.

File: pkg/component/component.go [hunk 5]
```diff
@@ -96,6 +103,11 @@ func (r *RuntimeSpecs) ToComponents(policy map[string]interface{}) ([]Component,
...
+			"uid":  os.Geteuid(),
+			"gid":  os.Getgid(),
```
Comment (michalpristas) [inline pkg/component/component.go:108]: dont we want `Getegid`?

File: pkg/component/runtime/command.go [hunk 6]
```diff
@@ -20,8 +25,14 @@ import (
 type actionMode int
 
 const (
-	actionStart = actionMode(0)
-	actionStop  = actionMode(1)
+	actionStart    = actionMode(0)
```
Comment (michalpristas) [inline pkg/component/runtime/command.go:28]: default uninitialized value for actionMode is start, not sure if this is ok but i don't like it tbh

File: pkg/component/runtime/command.go [hunk 7]
```diff
@@ -69,6 +80,7 @@ func NewCommandRuntime(comp component.Component) (ComponentRuntime, error) {
 // ever be called again.
 func (c *CommandRuntime) Run(ctx context.Context, comm Communicator) error {
 	checkinPeriod := c.current.Spec.Spec.Command.Timeouts.Checkin
+	restartPeriod := c.current.Spec.Spec.Command.Timeouts.Restart
```
Comment (michalpristas) [inline pkg/component/runtime/command.go:83]: can we run into nil pointer somewhere here?

File: pkg/component/runtime/command.go [hunk 8]
```diff
@@ -81,25 +93,22 @@ func (c *CommandRuntime) Run(ctx context.Context, comm Communicator) error {
 			switch as {
 			case actionStart:
 				if err := c.start(comm); err != nil {
-					c.forceCompState(client.UnitStateFailed, err.Error())
+					c.forceCompState(client.UnitStateFailed, fmt.Sprintf("Failed: %s", err))
```
Comment (michalpristas) [inline pkg/component/runtime/command.go:96]: can we add even more context?

File: pkg/component/runtime/command.go [hunk 9]
```diff
@@ -243,11 +260,26 @@ func (c *CommandRuntime) start(comm Communicator) error {
...
 	cmdSpec := c.current.Spec.Spec.Command
-	env := make([]string, 0, len(cmdSpec.Env))
+	env := make([]string, 0, len(cmdSpec.Env)+2)
 	for _, e := range cmdSpec.Env {
 		env = append(env, fmt.Sprintf("%s=%s", e.Name, e.Value))
 	}
-	proc, err := process.Start(c.current.Spec.BinaryPath, os.Geteuid(), os.Getgid(), cmdSpec.Args, env, attachOutErr)
+	env = append(env, fmt.Sprintf("%s=%s", envAgentComponentID, c.current.ID))
+	env = append(env, fmt.Sprintf("%s=%s", envAgentComponentInputType, c.current.Spec.InputType))
+	uid, gid := os.Geteuid(), os.Getgid()
```
Comment (michalpristas) [inline pkg/component/runtime/command.go:269]: again: getegid vs getgid

File: pkg/component/runtime/command.go [hunk 10]
```diff
@@ -243,11 +260,26 @@ func (c *CommandRuntime) start(comm Communicator) error {
...
+	workDir, err := c.workDir(uid, gid)
+	if err != nil {
+		return err
```
Comment (michalpristas) [inline pkg/component/runtime/command.go:272]: more context please.

File: pkg/component/runtime/command.go (hunk 7 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:83]: This is checked in the initialization of the struct. The depth after that does not have any pointers.

```
if comp.Spec.Spec.Command == nil {
		return nil, errors.New("must have command defined in specification")
	}
```

File: pkg/component/runtime/command.go (hunk 6 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:28]: Changed it to be 0 for stop, -1 for teardown, and 1 for start.

File: pkg/component/component.go (hunk 5 above)
Comment (blakerouse) [reply pkg/component/component.go:108]: Yes we do. Changed it.

File: pkg/component/component.go [hunk 11]
```diff
@@ -6,8 +6,11 @@ package component
 
 import (
 	"fmt"
+	"os"
 	"strings"
 
+	"github.com/elastic/elastic-agent/pkg/utils"
+
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/component/component.go:13]: Yes its nice, but also a pain. Fixed.

File: pkg/component/runtime/command.go (hunk 8 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:96]: All the context should already be coming from the `c.start()`. It adds extra data in those error messages.

File: pkg/component/runtime/command.go (hunk 9 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:269]: Fixed.

File: pkg/component/runtime/command.go (hunk 10 above)
Comment (blakerouse) [reply pkg/component/runtime/command.go:272]: `workDir` already adds the context information to the error.

File: pkg/utils/root_unix.go [hunk 12]
```diff
@@ -5,7 +5,7 @@
 //go:build !windows
 // +build !windows
 
-package install
+package utils
```
Comment (AndersonQ) [inline pkg/utils/root_unix.go:8]: I'm not really in favour of a utils package, as it does not say much. I rather have a few small, more meaningful packages. Perhaps it could be called `permissions` or `perms`

File: pkg/component/runtime/command.go [hunk 13]
```diff
@@ -243,11 +260,26 @@ func (c *CommandRuntime) start(comm Communicator) error {
...
+	if err != nil {
+		return fmt.Errorf("failed to determine absolute path: %w", err)
+	}
+	err = utils.HasStrictExecPerms(path, uid)
+	if err != nil {
+		return fmt.Errorf("execution of component prevented: %w", err)
+	}
+	proc, err := process.Start(path, uid, gid, cmdSpec.Args, env, attachOutErr, dirPath(workDir))
 	if err != nil {
 		return err
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/component/runtime/command.go:284]: `process.Start` already adds lots of context to the error, any extra here would be redundant.

File: pkg/component/runtime/command.go [hunk 14]
```diff
@@ -261,7 +293,14 @@ func (c *CommandRuntime) start(comm Communicator) error {
 
 func (c *CommandRuntime) stop(ctx context.Context) error {
 	if c.proc == nil {
-		// already stopped
+		// already stopped ensure that state of the component is also stopped
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/component/runtime/command.go]: Fixed

File: pkg/component/runtime/command.go [hunk 15]
```diff
@@ -306,16 +345,51 @@ func (c *CommandRuntime) handleProc(state *os.ProcessState) bool {
...
+	if runtime.GOOS == component.Windows {
+		return path, nil
+	}
+	err = os.Chown(path, uid, gid)
+	if err != nil {
+		return "", fmt.Errorf("failed to chown %s: %w", path, err)
+	}
+	err = os.Chmod(path, runDirMod)
+	if err != nil {
+		return "", fmt.Errorf("failed to chmod: %s, %w", path, err)
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/component/runtime/command.go]: Fixed

File: pkg/component/component.go [hunk 16]
```diff
@@ -260,12 +272,16 @@ func toIntermediate(policy map[string]interface{}) (map[string]outputI, error) {
...
-			return nil, fmt.Errorf("invalid 'inputs.%d', 'id' missing", idx)
+			// no ID; fallback to type
+			idRaw = t
 		}
 		id, ok := idRaw.(string)
 		if !ok {
 			return nil, fmt.Errorf("invalid 'inputs.%d.id', expected a string not a %T", idx, idRaw)
 		}
+		if hasDuplicate(outputsMap, id) {
+			return nil, fmt.Errorf("invalid 'inputs.%d.id', has a duplicate id (id is required to be unique)", idx)
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/component/component.go]: Added

File: pkg/component/runtime/command.go [hunk 17]
```diff
@@ -306,16 +345,51 @@ func (c *CommandRuntime) handleProc(state *os.ProcessState) bool {
...
 
+func (c *CommandRuntime) workDirPath() string {
+	return filepath.Join(paths.Run(), c.current.ID)
+}
+
+func (c *CommandRuntime) workDir(uid int, gid int) (string, error) {
+	path := c.workDirPath()
+	err := os.MkdirAll(path, runDirMod)
+	if err != nil {
+		return "", fmt.Errorf("failed to create path: %s, %w", path, err)
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/component/runtime/command.go]: Fixed.

File: pkg/utils/root_unix.go (hunk 12 above)
Comment (blakerouse) [reply pkg/utils/root_unix.go:8]: We can look at that in a later time.

**Review by cmacknz — APPROVED** [review]
Approving, outstanding comments don't seem blocking to me.

File: pkg/utils/perm_windows.go (hunk 4 above)
Comment (cmacknz) [reply pkg/utils/perm_windows.go:13]: Added this as a TODO on the V2 tracking issue with a link to this comment
