### PR TITLE
Fix filesource provider with kubernetes symlink

### LINKED ISSUE #11051: filesource provider does re-read kubernetes mounted secrets
Created a PR here to test a theory that it doesn't work properly when it comes to kubernetes secret mounts. https://github.com/elastic/elastic-agent/pull/11050

The PR is failing highlighting that the logic is flawed and needs to be fixed.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Currently the `filesource` provider does not handle watching the correct paths because of how Kubernetes handles mounting sercrets into a container.

Adds a unit test to validate the filesource provider works with secret replacement from Kubernetes.

## Why is it important?

Ensures that secret replacement changes are noticed by the filesource provider.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

None

## How to test this PR locally

`mage unitTest`

## Related issues

- Closes #11051

### CODE REVIEW

File: internal/pkg/composable/providers/filesource/filesource.go [hunk 1]
```diff
@@ -284,3 +309,66 @@ func drainQueue(e <-chan fsnotify.Event) {
...
+			if runtime.GOOS == "windows" {
+				cleanPath = strings.ToLower(cleanPath)
+			}
+			intermediates = append(intermediates, cleanPath)
+		}
+	}
+
+	// Also check if the final target file exists and is a symlink (nested symlinks)
+	finalTarget := filepath.Join(targetDir, targetBase)
+	_, err = os.Readlink(finalTarget)
```
Comment (ycombinator) [inline internal/pkg/composable/providers/filesource/filesource.go]: Isn't this just `target`?
```suggestion
	_, err = os.Readlink(target)
```

Comment (blakerouse) [reply internal/pkg/composable/providers/filesource/filesource.go]: You are correct. I updated the code.

**Comment by blakerouse** [comment]
@ycombinator If I could get another +1 that would be great. Just updated the code with your comment.
