### PR TITLE
Fix flaky TestCoordinatorReportsInvalidPolicy

### LINKED ISSUE #4117: [Flaky Test]: TestCoordinatorReportsInvalidPolicy – Vars change should cause state update
### Failing test case

TestCoordinatorReportsInvalidPolicy

### Error message

Vars change should cause state update

### Build

https://buildkite.com/elastic/elastic-agent/builds/6447#018d322c-0022-432b-971f-7a2eabc3fb5d

2024-02-22: https://buildkite.com/elastic/elastic-agent/builds/7395#018dd0cc-694f-401c-bbf1-23a3aa70d353

### OS

Mac

### Stacktrace and notes

```markdown
2024-01-22 12:39:10 EST	=== Failed
2024-01-22 12:39:10 EST	=== FAIL: internal/pkg/agent/application/coordinator TestCoordinatorReportsInvalidPolicy (1.17s)
2024-01-22 12:39:10 EST	    coordinator_unit_test.go:416:
2024-01-22 12:39:10 EST	        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1705943780109969315/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator_unit_test.go:416
2024-01-22 12:39:10 EST	        	Error:      	Vars change should cause state update
2024-01-22 12:39:10 EST	        	Test:       	TestCoordinatorReportsInvalidPolicy
2024-01-22 12:39:10 EST	    coordinator_unit_test.go:426:
2024-01-22 12:39:10 EST	        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1705943780109969315/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator_unit_test.go:426
2024-01-22 12:39:10 EST	        	Error:      	Received unexpected error:
2024-01-22 12:39:10 EST	        	            	failed to reload upgrade manager configuration: invalid config: can not convert 'object' into 'string' accessing 'agent.download.sourceURI' accessing 'agent.download'
2024-01-22 12:39:10 EST	        	Test:       	TestCoordinatorReportsInvalidPolicy
2024-01-22 12:39:10 EST	        	Messages:   	Valid policy change should clear configErr
2024-01-22 12:39:10 EST	    coordinator_unit_test.go:432:
2024-01-22 12:39:10 EST	        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1705943780109969315/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator_unit_test.go:432
2024-01-22 12:39:10 EST	        	Error:      	Policy change should cause state update
2024-01-22 12:39:10 EST	        	Test:       	TestCoordinatorReportsInvalidPolicy
```
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Fixes flakyness of `TestCoordinatorReportsInvalidPolicy` by increasing the state change timeout, failing fast and having better error messages and printing the coordinator logs if the test fails.

## Why is it important?

The test is flaky

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

 - N/A

## Related issues

- Closes #4117 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: internal/pkg/agent/application/coordinator/coordinator_unit_test.go [hunk 1]
```diff
@@ -398,11 +409,9 @@ agent.download.sourceURI:
 		// The component model update happens on a goroutine, thus the new state
 		// might not have been sent yet. Therefore, a timeout is required.
 	case <-time.After(time.Second):
-		assert.Fail(t, "Coordinator's state didn't change")
+		t.Fatalf("timedout after %s waiting Coordinator's state to change", stateChangeTimeout)
```
Comment (cmacknz) [inline internal/pkg/agent/application/coordinator/coordinator_unit_test.go:412]: > case <-time.After(time.Second):

The log message doesn't match the case statement.

**Comment by AndersonQ** [comment]
@cmacknz I fixed the case statement, could you re-review it?

**Review by cmacknz — APPROVED** [review]
