### PR TITLE
Fix zombie processes when components fail to shutdown

### LINKED ISSUE #13272: elastic-agent restart fails to reap unresponsive components
The `elastic-agent restart` command may leave behind zombie processes if elastic-agent has components which are unresponsive.

This is likely due to the manager shutdown timer being set to 5s with no ability to configure, or warnings if there was no response:
https://github.com/elastic/elastic-agent/blob/bb0c75590ac559ea24a6e20281713a5bf3a03841/internal/pkg/agent/application/coordinator/coordinator.go#L232-L239

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Prevents zombie processes when a component subprocess fails to shut down within the coordinator's timeout window (e.g. during `elastic-agent restart` or upgrades).
Coordinator timeout window is now aware of component shutdown limits, with an additional 5s buffer time that caps to 30s as to not exceed external process manager defaults.

## Why is it important?

Linux systems have an issue where components may be left on systems as zombies.
This can occur during the agent upgrade process when `elastic-agent restart` is ran, ~~or if a unresponsive component fails to check in and needs to be stopped by the agent~~.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

Systems with unresponsive components may take longer to shut down as the coordinator timeout has increase from the previous default of 5s too 30s. However it should terminate before an external service manager (such as systemd) times out.

## Related issues

- Relates #2190
- Closes #13272

### CODE REVIEW

File: pkg/component/runtime/runtime.go [hunk 1]
```diff
@@ -132,11 +132,31 @@ func (s *componentRuntimeState) runLoop() {
...
+	if s.manager.runCtx != nil {
+		managerDone = s.manager.runCtx.Done()
+	}
+
 	for {
 		select {
 		case <-runtimeRunner.Done():
 			// Exit from the watcher loop only when the runner is done
 			return
+		case <-managerDone:
```
[the remark this answers is not in the document]
Comment (michel-laterman) [reply pkg/component/runtime/runtime.go]: fix it for me

File: pkg/component/runtime/command.go [hunk 2]
```diff
@@ -457,6 +459,62 @@ func (c *commandRuntime) startWatcher(info *process.Info, comm Communicator) {
...
+// this amount so the entire cleanup completes before external process managers
+// (systemd, Kubernetes) forcibly kill the agent.
+const ShutdownBuffer = 5 * time.Second
+
+// cleanupProcess gracefully stops a running managed process and waits
+// for the startWatcher goroutine to reap it, preventing zombie processes
+// on context cancellation. It first sends SIGTERM and waits, if the
+// process takes too long to exit it  sends SIGKILL to force termination.
+// An unresponsive process should be killed and reaped within 30s.
+func (c *commandRuntime) cleanupProcess() {
```
Comment (swiatekm) [inline pkg/component/runtime/command.go]: I don't fully understand why we're adding a new function for cleanup, when we already have `stop`. Intuitively, when the context is cancelled, we should call `stop()`, and then a new function that waits for the stop to complete or for a timeout.

**Comment by cmacknz** [comment]
I don't see how this closes https://github.com/elastic/elastic-agent/issues/2190 which is about the watch sub-process we spawn that lives across the upgrade re-exec, and it should be unlinked as closing.

Likely we want a new public issue for this problem.

Edit: updated the PR to have this as related and not closing for https://github.com/elastic/elastic-agent/issues/2190

**Comment by michel-laterman** [comment]
Thank's i'll create a new public bug and implement @swiatekm's suggestion

File: pkg/component/runtime/command.go [hunk 3]
```diff
@@ -457,6 +462,55 @@ func (c *commandRuntime) startWatcher(info *process.Info, comm Communicator) {
...
+// (systemd, Kubernetes) forcibly kill the agent.
+const ShutdownBuffer = 5 * time.Second
+
+// killReapTime is timeout after a SIGKILL is sent to wait for the process to be reaped.
+const killReapTime = 3 * time.Second
+
+// waitOrKill waits after a SIGTERM for the process to be stopped.
+// if process takes too long to exit it sends SIGKILL to force termination.
+// An unresponsive process should be killed and reaped within 30s.
+func (c *commandRuntime) waitOrKill() {
```
Comment (cmacknz) [inline pkg/component/runtime/command.go]: This same logic should be available for the OTel manager to use when supervising the collector, which does not use the command runtime. 

Somewhere around here https://github.com/elastic/elastic-agent/blob/1583c0ee474c544b6d3d4bfb9280fbdda9084c73/internal/pkg/otel/manager/execution_subprocess.go#L430

Comment (cmacknz) [reply pkg/component/runtime/command.go]: Otherwise you've only fixed this when we aren't using beat receivers (which eventually will be nowhere).

File: pkg/component/runtime/manager.go [hunk 4]
```diff
@@ -108,6 +109,13 @@ type Manager struct {
 	monitor    MonitoringManager
 	grpcConfig *configuration.GRPCConfig
 
+	// runCtx is the context from Run(). It is cancelled when the coordinator
+	// shuts down the manager. Component runtimes use this so their runner
+	// context is also cancelled on shutdown, allowing cleanup (e.g. killing
+	// child processes) even when the component has not reached Stopped.
+	// Stored atomically so runLoop() goroutines can read it without a mutex.
+	runCtx atomic.Pointer[context.Context]
```
Comment (cmacknz) [inline pkg/component/runtime/manager.go]: Why is this wrapped in an atomic? That is highly unusual for a context, since they are goroutine safe.

File: pkg/component/runtime/runtime.go [hunk 5]
```diff
@@ -132,11 +132,46 @@ func (s *componentRuntimeState) runLoop() {
...
+			done := runtimeRunner.Done()
+			for {
+				select {
+				case <-done:
+					s.manager.currentMx.Lock()
+					delete(s.manager.current, s.id)
+					s.manager.currentMx.Unlock()
+					return
+				case <-s.runtime.Watch():
+					// drain to unblock any in-flight sendObserved() call
```
Comment (cmacknz) [inline pkg/component/runtime/runtime.go]: You are throwing away the state we receive, is this safe to do?

File: pkg/core/process/external_linux.go [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+}
+
+// isZombie checks if the process with the given PID is in zombie state
+// by reading /proc/<pid>/stat. The format is:
+//
+//	<pid> (<comm>) <state> ...
+//
+// where <state> is a single character. 'Z' indicates zombie state.
+// We use LastIndex for ") " to handle process names containing parentheses.
+func isZombie(pid int) bool {
```
Comment (cmacknz) [inline pkg/core/process/external_linux.go]: 90% the same as the assertProcessReaped implementation, can probably be reused.

File: pkg/core/process/external_linux.go [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+// externalProcess is a watch mechanism used in cases where OS requires a process to be a child
+// for waiting for process. We need to be able to await any process.
+func externalProcess(proc *os.Process) {
+	if proc == nil {
+		return
+	}
+
+	for {
+		<-time.After(1 * time.Second)
+		if proc.Signal(syscall.Signal(0)) != nil {
```
Comment (cmacknz) [inline pkg/core/process/external_linux.go:27]: Is there a reason to do this instead of just going straight into the PID file? What does this save you?

File: testing/integration/ess/zombie_helpers_linux_test.go [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+
+	// Check if the process is still alive via kill(pid, 0).
+	if err := unix.Kill(pid, 0); err != nil {
+		t.Logf("process %d is gone (kill returned: %v)", pid, err)
+		return
+	}
+
+	// Process is still alive — also check if it's a zombie.
+	state := "alive"
+	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/stat", pid))
```
Comment (cmacknz) [inline testing/integration/ess/zombie_helpers_linux_test.go]: 3rd time I've read this code in this PR :)

File: testing/integration/ess/zombie_helpers_linux_test.go [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+	// Check if still alive first.
+	if err := unix.Kill(pid, 0); err != nil {
+		return // already gone
+	}
+
+	t.Logf("cleanup: killing leftover component process %d", pid)
+	_ = syscall.Kill(pid, syscall.SIGKILL)
+
+	// Reap if we're the parent (unlikely, but handle it).
+	syscall.Wait4(pid, nil, syscall.WNOHANG, nil) //nolint:errcheck
```
Comment (cmacknz) [inline testing/integration/ess/zombie_helpers_linux_test.go]: Is this necessary? Are you the parent in the test? I ask because this is esoteric enough that it will potentially never be removed so let's explain why we need it now.

File: pkg/component/fake/component/pdeathsig_linux.go [hunk 10]
```diff
@@ -0,0 +1,16 @@
...
+
+//go:build linux
+
+package main
+
+import "golang.org/x/sys/unix"
+
+// clearPdeathsig clears the parent-death signal so this process survives its
+// parent exiting. Used in tests to verify the agent actively kills components
+// during shutdown rather than relying on Pdeathsig.
```
Comment (cmacknz) [inline pkg/component/fake/component/pdeathsig_linux.go]: Does this survive the parent exiting? Is it not sent SIGKILL which you can't ignore when the parent dies?

I think ignoring sigterm is fine, this makes it read like a variant of detaching from your parent process which I thought was more involved than this.

Comment (cmacknz) [reply pkg/component/fake/component/pdeathsig_linux.go]: If this does allow you to survive the parent exiting we probably want to do it in the upgrade watcher, since re-parenting that to the OS supervisor would fix the zombie in https://github.com/elastic/elastic-agent/issues/2190 and also make the upgrade process even more robust.

Comment (cmacknz) [reply pkg/component/fake/component/pdeathsig_linux.go]: Why do you need this and the `signal.Ignore(syscall.SIGTERM)` call?

File: pkg/core/process/external_linux.go (hunk 7 above)
Comment (michel-laterman) [reply pkg/core/process/external_linux.go:27]: For managing the `elastic-agent restart` command, we already know the pid, signal(0) works for windows/mac; but using a pid file based approach can make it easier to address #2190 as a followup, i'll move this back to a draft to see if I can get something that works

File: pkg/component/runtime/runtime.go (hunk 5 above)
Comment (michel-laterman) [reply pkg/component/runtime/runtime.go]: This occurs during shutdown, so it should be ok

File: pkg/core/process/external_linux.go (hunk 6 above)
Comment (michel-laterman) [reply pkg/core/process/external_linux.go]: I'll export this, good catch(es)

File: pkg/component/fake/component/pdeathsig_linux.go (hunk 10 above)
Comment (michel-laterman) [reply pkg/component/fake/component/pdeathsig_linux.go]: ignore sigterm allows the component to ignore the graceful shutdown signal, `Pdeathsig` detches it from the agent lifecycle

We probably don't need `Pdeathsig` for the restart test; but as you said it can be used in the future to validate watcher fixes.

I'll make sure comments are very clear about the distinction

File: pkg/component/runtime/command.go (hunk 3 above)
Comment (michel-laterman) [reply pkg/component/runtime/command.go]: I've changed the otel manager to have consistent reap wait times and log levels to the component manager (1s->3s, warn->error), as it already had a SIGTERM->wait->SIGKILL->wait execution flow for stopping

File: pkg/component/fake/component/pdeathsig_linux.go (hunk 10 above)
Comment (cmacknz) [reply pkg/component/fake/component/pdeathsig_linux.go]: It turns out we already use this in the upgrade watcher

https://github.com/elastic/elastic-agent/blob/5458c7fda99d259cc5e367ebbfc0f02ea3428829/internal/pkg/agent/cmd/watch_signals_linux.go#L15-L17

File: testing/integration/ess/zombie_helpers_linux_test.go (hunk 9 above)
Comment (cmacknz) [reply testing/integration/ess/zombie_helpers_linux_test.go]: The manpage for this even says don't use it https://man7.org/linux/man-pages/man2/wait3.2.html

> These functions are nonstandard; in new programs, the use of
       [waitpid(2)](https://man7.org/linux/man-pages/man2/waitpid.2.html) or [waitid(2)](https://man7.org/linux/man-pages/man2/waitid.2.html) is preferable.

File: pkg/core/process/external_linux.go (hunk 7 above)
Comment (cmacknz) [reply pkg/core/process/external_linux.go:27]: This is fine to do first, it's not causing any harm

File: pkg/component/runtime/command.go [hunk 11]
```diff
@@ -49,6 +49,25 @@ func (m actionMode) String() string {
 	return ""
 }
 
+const (
+	// ShutdownBuffer is the time reserved for SIGKILL delivery, process reaping,
+	// and coordinator shutdown overhead. The SIGTERM grace period is reduced by
+	// this amount so the entire cleanup completes before external process managers
+	// (systemd, Kubernetes) forcibly kill the agent.
+	ShutdownBuffer = 5 * time.Second
```
Comment (cmacknz) [inline pkg/component/runtime/command.go]: This should probably be KillReapTime + 2s to avoid them becoming out of sync, looking at the way KillReapTime is used.

File: pkg/component/runtime/manager_fake_input_test.go [hunk 12]
```diff
@@ -2170,6 +2172,132 @@ LOOP:
...
+	// path in commandRuntime.Run(), which must reap the child process so it
+	// does not become a zombie.
+	subCancel()
+	cancel()
+
+	err = <-errCh
+	require.NoError(t, err)
+
+	// Give a short time for the process to be fully reaped.
+	require.Eventually(t, func() bool { return process.IsReaped(runningPID) }, process.KillReapTime, 100*time.Millisecond, "Process may still be running as a zombie")
```
Comment (cmacknz) [inline pkg/component/runtime/manager_fake_input_test.go]: What's the difference between this test and the integration test in zombie_process_test.go?

Comment (cmacknz) [reply pkg/component/runtime/manager_fake_input_test.go]: It looks like this one doesn't force the component to ignore SIGTERM?

Does this need a separate test, I assume the fake component stops in all these tests?

File: pkg/component/runtime/runtime.go [hunk 13]
```diff
@@ -119,24 +119,55 @@ func newComponentRuntimeState(m *Manager, logger *logger.Logger, monitor Monitor
...
+			// forever and Run() never returns to its select to see
+			// ctx.Done() — a deadlock. Draining here unblocks any
+			// in-flight send so Run() can exit cleanly.
+			runtimeRunner.Stop()
+			done := runtimeRunner.Done()
+			for {
+				select {
+				case <-done:
+					s.manager.currentMx.Lock()
+					delete(s.manager.current, s.id)
```
Comment (cmacknz) [inline pkg/component/runtime/runtime.go]: Why do we need to delete this? Having to hold `currentMx` creates another opportunity for deadlock, it's not clear to me we'll always be able to grab it under every circumstance once the parent context has been cancelled.

File: testing/integration/ess/zombie_helpers_linux_test.go (hunk 9 above)
Comment (michel-laterman) [reply testing/integration/ess/zombie_helpers_linux_test.go]: I've change the cleanup approach to avoid this

File: pkg/component/runtime/runtime.go (hunk 13 above)
Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: It is weird that the the component has to reach into the managers global state at all

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: The mutex here doesn't influence the timing of when the manager might also be looking at it's list of components, it just prevents concurrent modification.

What is preventing a race between the manager shutdown executing which is also triggered by `ctx.Done()`? This looks into `manager.current` several times. I don't think we are guaranteed that this deletion happens before manager has looked at this component (really all the components).

https://github.com/elastic/elastic-agent/blob/47699bdf379def1df5c9ac5821757eff2fa81353/pkg/component/runtime/manager.go#L864-L876

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: OK I think this is working off of this block that has been around for some time, where `shutdown` polls for component removal:

https://github.com/elastic/elastic-agent/blob/47699bdf379def1df5c9ac5821757eff2fa81353/pkg/component/runtime/manager.go#L845-L854

File: pkg/component/runtime/manager_fake_input_test.go (hunk 12 above)
Comment (michel-laterman) [reply pkg/component/runtime/manager_fake_input_test.go]: no, i'll remove this test

File: pkg/component/runtime/runtime.go (hunk 13 above)
Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: This code block is to handle another deadlock https://github.com/elastic/elastic-agent/pull/2729

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: So I think the main problem is that depending on the exact timing of when we remove the component from the manager's map of components, it's possible it gets removed before the manager expects it to be stopped and then we don't wait for it which could cause some weirdness.

https://github.com/elastic/elastic-agent/blob/47699bdf379def1df5c9ac5821757eff2fa81353/pkg/component/runtime/manager.go#L770-L780

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: It looks like we should potentially be forcing `UnitStateStopped` to hit the polling for that instead, which doesn't have the limitation that we could remove the component before the manager is ready to stop it.

https://github.com/elastic/elastic-agent/blob/47699bdf379def1df5c9ac5821757eff2fa81353/pkg/component/runtime/manager.go#L838-L843

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: This will have the consequence that we report stopped immediately, before the component has had a chance to tear itself down.

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: But we are doing that anyway

Comment (michel-laterman) [reply pkg/component/runtime/runtime.go]: The waitForStopped method already accounts for components that dissapear before reporting the stopped state: https://github.com/elastic/elastic-agent/blob/47699bdf379def1df5c9ac5821757eff2fa81353/pkg/component/runtime/manager.go#L849-L852

The shutdown method that occurs when the context has been cancelled (for a restart) sends the stop states, and eventually reaches a select where it either handles the context, or the action (then the context):
https://github.com/elastic/elastic-agent/blob/8139dd5de4b7d02d1a2810568c0b8a141daab82c/pkg/component/runtime/command.go#L171-L178

The stop action runs with a cancelled context meaning that:
https://github.com/elastic/elastic-agent/blob/8139dd5de4b7d02d1a2810568c0b8a141daab82c/pkg/component/runtime/command.go#L442-L457
only sends a SIGTERM then returns, and the `ctx` case would be handled (sending another SIGTERM then waiting)

After `commandRuntime.Run` returns, the `<-done` case in the initial comment triggers deleting the component from the map, allowing `waitForStopped` to proceed

Comment (cmacknz) [reply pkg/component/runtime/runtime.go]: > The waitForStopped method already accounts for components that dissapear before reporting the stopped state:

Yes it does, but there are various blocks before we get there that also look into the map, and those are mutex protected but in separate critical sections. There is no guaranteed ordering guaranteeing that the component goroutine only deletes from the manager map at the moment we intend it to.

The block you linked in the command runtime sending SIGTERM doesn't set the STOPPED state, and the component isn't guaranteed to set it either, so we maybe need to rely on deleting the component because nothing would ever set the stopped state.

Also the SIGTERM on stop won't apply to the service runtime and we need to make sure we haven't created any service related race conditions out of this.

File: pkg/component/runtime/runtime.go [hunk 14]
```diff
@@ -119,24 +119,57 @@ func newComponentRuntimeState(m *Manager, logger *logger.Logger, monitor Monitor
...
+			for {
+				select {
+				case <-done:
+					s.manager.currentMx.Lock()
+					// Deletion is required for deadlock avoidance, see:
+					// https://github.com/elastic/elastic-agent/pull/2729
+					delete(s.manager.current, s.id)
+					s.manager.currentMx.Unlock()
+					return
+				case <-s.runtime.Watch():
```
Comment (swiatekm) [inline pkg/component/runtime/runtime.go]: Do we have a guarantee that we won't go into the `<-done` branch while there's still state updates pending?

File: pkg/component/runtime/runtime.go (hunk 13 above)
Comment (swiatekm) [reply pkg/component/runtime/runtime.go]: I think you don't technically have a guarantee that you're deleting your own entry here, as opposed to a new component with the same ID. It'd take a pretty specific sequence of events to get there, and you can guard against it by checking if you're really removing your own entry.

In general, even if there's a race condition here, we're still shutting down, so incorrect status isn't that impactful. The worst we can do is what we're trying to fix - not waiting for a process we should wait for. I don't think we can deadlock with this code.

I'm ok merging it as-is and refactoring in a follow-up so the flow is clearer.

**Comment by ebeahan** [comment]
Force merging do to a known issue with the Win 11 CI runner causing one of the unit tests to fail.
