### PR TITLE
Fix flakiness on enrollment integration test and rename it

### LINKED ISSUE #3081: TestEnrollAndLog/TestEnroll  test is flaky
## Flaky Test

* **Test Name:** TestEnrollAndLog/TestEnroll 
* **Link:** https://github.com/elastic/elastic-agent/blob/123579115ad7a330779c2f9b5b9e719f98282dc4/testing/integration/enroll_test.go#L117
* **Branch:** [Git branch the test was seen in. If a PR, the branch the PR was based off.](https://github.com/elastic/elastic-agent/pull/3071)

### Stack Trace

```
enroll_test.go:189: --- debugging: results from ES --- END ---
    enroll_test.go:106: metricbeat: Got 10 documents
    enroll_test.go:109: Making sure there are no error logs
    enroll_test.go:185: --- debugging: results from ES --- START ---
    enroll_test.go:187: map[string]interface {}{"@timestamp":"2023-07-12T23:58:08.805Z", "address":"127.0.0.1:9200", "agent":map[string]interface {}{"ephemeral_id":"27b2ee5c-a601-412c-8dd9-bf069ecaf1ea", "id":"8129be2d-bd95-412f-a91e-1d94a8c29764", "name":"ogc-cinjkvvqfsgpnvqf9lr0-3011", "type":"filebeat", "version":"8.10.0"}, "cloud":map[string]interface {}{"account":map[string]interface {}{"id":"elastic-platform-ingest"}, "availability_zone":"us-central1-a", "instance":map[string]interface {}{"id":"2851333541445403722", "name":"ogc-cinjkvvqfsgpnvqf9lr0-3011"}, "machine":map[string]interface {}{"type":"t2a-standard-2"}, "project":map[string]interface {}{"id":"elastic-platform-ingest"}, "provider":"gcp", "region":"us-central1", "service":map[string]interface {}{"name":"GCE"}}, "component":map[string]interface {}{"binary":"metricbeat", "dataset":"elastic_agent.metricbeat", "id":"system/metrics-default", "type":"system/metrics"}, "data_stream":map[string]interface {}{"dataset":"elastic_agent.metricbeat", "namespace":"q49ily4xofxhfz0rsujmobuotbwk5yer7hfczxcrs", "type":"logs"}, "ecs":map[string]interface {}{"version":"8.0.0"}, "elastic_agent":map[string]interface {}{"id":"8129be2d-bd95-412f-a91e-1d94a8c29764", "snapshot":true, "version":"8.10.0"}, "event":map[string]interface {}{"agent_id_status":"verified", "dataset":"elastic_agent.metricbeat", "ingested":"2023-07-12T23:58:15Z"}, "host":map[string]interface {}{"architecture":"aarch64", "containerized":false, "hostname":"ogc-cinjkvvqfsgpnvqf9lr0-3011", "id":"bb1f9231036ddf511f603b0dac92e7bc", "ip":[]interface {}{"10.128.0.51", "fe80::4001:aff:fe80:33"}, "mac":[]interface {}{"42-01-0A-80-00-33"}, "name":"ogc-cinjkvvqfsgpnvqf9lr0-3011", "os":map[string]interface {}{"codename":"jammy", "family":"debian", "kernel":"5.19.0-1027-gcp", "name":"Ubuntu", "platform":"ubuntu", "type":"linux", "version":"22.04.2 LTS (Jammy Jellyfish)"}}, "input":map[string]interface {}{"type":"filestream"}, "log":map[string]interface {}{"file":map[string]interface {}{"path":"/opt/Elastic/Agent/data/elastic-agent-b3f64a/logs/elastic-agent-20230712.ndjson"}, "offset":59544, "source":"system/metrics-default"}, "log.level":"error", "log.logger":"esclientleg", "log.origin":map[string]interface {}{"file.line":38, "file.name":"transport/logging.go"}, "message":"Error dialing dial tcp 127.0.0.1:9200: connect: connection refused", "network":"tcp", "service.name":"metricbeat"}
    enroll_test.go:189: --- debugging: results from ES --- END ---
    enroll_test.go:113: errors: Got 1 documents
    enroll_test.go:115: map[string]interface {}{"@timestamp":"2023-07-12T23:58:08.805Z", "address":"127.0.0.1:9200", "agent":map[string]interface {}{"ephemeral_id":"27b2ee5c-a601-412c-8dd9-bf069ecaf1ea", "id":"8129be2d-bd95-412f-a91e-1d94a8c29764", "name":"ogc-cinjkvvqfsgpnvqf9lr0-3011", "type":"filebeat", "version":"8.10.0"}, "cloud":map[string]interface {}{"account":map[string]interface {}{"id":"elastic-platform-ingest"}, "availability_zone":"us-central1-a", "instance":map[string]interface {}{"id":"2851333541445403722", "name":"ogc-cinjkvvqfsgpnvqf9lr0-3011"}, "machine":map[string]interface {}{"type":"t2a-standard-2"}, "project":map[string]interface {}{"id":"elastic-platform-ingest"}, "provider":"gcp", "region":"us-central1", "service":map[string]interface {}{"name":"GCE"}}, "component":map[string]interface {}{"binary":"metricbeat", "dataset":"elastic_agent.metricbeat", "id":"system/metrics-default", "type":"system/metrics"}, "data_stream":map[string]interface {}{"dataset":"elastic_agent.metricbeat", "namespace":"q49ily4xofxhfz0rsujmobuotbwk5yer7hfczxcrs", "type":"logs"}, "ecs":map[string]interface {}{"version":"8.0.0"}, "elastic_agent":map[string]interface {}{"id":"8129be2d-bd95-412f-a91e-1d94a8c29764", "snapshot":true, "version":"8.10.0"}, "event":map[string]interface {}{"agent_id_status":"verified", "dataset":"elastic_agent.metricbeat", "ingested":"2023-07-12T23:58:15Z"}, "host":map[string]interface {}{"architecture":"aarch64", "containerized":false, "hostname":"ogc-cinjkvvqfsgpnvqf9lr0-3011", "id":"bb1f9231036ddf511f603b0dac92e7bc", "ip":[]interface {}{"10.128.0.51", "fe80::4001:aff:fe80:33"}, "mac":[]interface {}{"42-01-0A-80-00-33"}, "name":"ogc-cinjkvvqfsgpnvqf9lr0-3011", "os":map[string]interface {}{"codename":"jammy", "family":"debian", "kernel":"5.19.0-1027-gcp", "name":"Ubuntu", "platform":"ubuntu", "type":"linux", "version":"22.04.2 LTS (Jammy Jellyfish)"}}, "input":map[string]interface {}{"type":"filestream"}, "log":map[string]interface {}{"file":map[string]interface {}{"path":"/opt/Elastic/Agent/data/elastic-agent-b3f64a/logs/elastic-agent-20230712.ndjson"}, "offset":59544, "source":"system/metrics-default"}, "log.level":"error", "log.logger":"esclientleg", "log.origin":map[string]interface {}{"file.line":38, "file.name":"transport/logging.go"}, "message":"Error dialing dial tcp 127.0.0.1:9200: connect: connection refused", "network":"tcp", "service.name":"metricbeat"}
    enroll_test.go:117: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/enroll_test.go:117
        	Error:      	Should be empty, but was [{.ds-logs-elastic_agent.metricbeat-q49ily4xofxhfz0rsujmobuotbwk5yer7hfczxcrs-2023.07.12-000001 4.4011974 map[@timestamp:2023-07-12T23:58:08.805Z address:127.0.0.1:9200 agent:map[ephemeral_id:27b2ee5c-a601-412c-8dd9-bf069ecaf1ea id:8129be2d-bd95-412f-a91e-1d94a8c29764 name:ogc-cinjkvvqfsgpnvqf9lr0-3011 type:filebeat version:8.10.0] cloud:map[account:map[id:elastic-platform-ingest] availability_zone:us-central1-a instance:map[id:2851333541445403722 name:ogc-cinjkvvqfsgpnvqf9lr0-3011] machine:map[type:t2a-standard-2] project:map[id:elastic-platform-ingest] provider:gcp region:us-central1 service:map[name:GCE]] component:map[binary:metricbeat dataset:elastic_agent.metricbeat id:system/metrics-default type:system/metrics] data_stream:map[dataset:elastic_agent.metricbeat namespace:q49ily4xofxhfz0rsujmobuotbwk5yer7hfczxcrs type:logs] ecs:map[version:8.0.0] elastic_agent:map[id:8129be2d-bd95-412f-a91e-1d94a8c29764 snapshot:true version:8.10.0] event:map[agent_id_status:verified dataset:elastic_agent.metricbeat ingested:2023-07-12T23:58:15Z] host:map[architecture:aarch64 containerized:false hostname:ogc-cinjkvvqfsgpnvqf9lr0-3011 id:bb1f9231036ddf511f603b0dac92e7bc ip:[10.128.0.51 fe80::4001:aff:fe80:33] mac:[42-01-0A-80-00-33] name:ogc-cinjkvvqfsgpnvqf9lr0-3011 os:map[codename:jammy family:debian kernel:5.19.0-1027-gcp name:Ubuntu platform:ubuntu type:linux version:22.04.2 LTS (Jammy Jellyfish)]] input:map[type:filestream] log:map[file:map[path:/opt/Elastic/Agent/data/elastic-agent-b3f64a/logs/elastic-agent-20230712.ndjson] offset:59544 source:system/metrics-default] log.level:error log.logger:esclientleg log.origin:map[file.line:38 file.name:transport/logging.go] message:Error dialing dial tcp 127.0.0.1:9200: connect: connection refused network:tcp service.name:metricbeat]}]
        	Test:       	TestEnrollAndLog/TestEnroll
    enroll_test.go:84: Cleanup: unenrolling agent
--- FAIL: TestEnrollAndLog/TestEnroll (148.38s)
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Fix flakiness on enrollment integration test and rename it so it better reflects what is tested by it.

I continually run the test for 20h and it did not fail.

## Why is it important?

The test was flaky and the name was misleading. It could lead one to believe the test was just the enrollement, when it actually tests the enrollment and the monitoring is shipping logs.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

Run it continuously, it should not fail.

```sh
AGENT_VERSION=8.10.0-SNAPSHOT AGENT_KEEP_INSTALLED=true TEST_RUN_UNTIL_FAILURE=true mage integration:single TestMonitoringLogsShipped
```

I run it for 20h, no issues.

## Related issues

- Closes #3081 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by cmacknz — CHANGES_REQUESTED** [review]
This test is intentionally testing that we can ship Beat logs to Fleet.

Otherwise we have no test coverage for the monitoring Filebeat instance and its configuration. See https://github.com/elastic/elastic-agent/issues/2402.

The test name is just not specific enough to communicate this.

If we do have this functionality covered somewhere else we can keep the deletion, but we can't just delete it completely.

File: testing/integration/monitoring_logs_test.go [hunk 1]
```diff
@@ -15,49 +15,34 @@ import (
...
-}
-
-func (runner *EnrollRunner) SetupTest() {}
 
-func (runner *EnrollRunner) TestEnroll() {
-	t := runner.T()
-	info := runner.requirementsInfo
-
-	kibClient := info.KibanaClient
+	t.Logf("In SetupSuite")
```
Comment (ycombinator) [inline testing/integration/monitoring_logs_test.go:43]: I think this line can be removed now?

File: testing/integration/monitoring_logs_test.go [hunk 2]
```diff
@@ -92,15 +79,15 @@ func (runner *EnrollRunner) TestEnroll() {
 		require.NoError(t, err)
 	})
 
-	t.Logf("sleeping for one minute...")
-	time.Sleep(time.Second * 60)
+	AssertConnectedToFleet(t, agentFixture)
```
Comment (ycombinator) [inline testing/integration/monitoring_logs_test.go:82]: Now that this helper function is being used by multiple tests, could we move it's definition out of `proxy_url_test.go` and into somewhere under https://github.com/elastic/elastic-agent/tree/main/pkg/testing/tools?

File: testing/integration/monitoring_logs_test.go [hunk 3]
```diff
@@ -111,16 +98,16 @@ func (runner *EnrollRunner) TestEnroll() {
...
-	// Stage 4: make sure we have no errors
-	t.Log("Making sure there are no error logs")
-	docs = findESDocs(t, func() (tools.Documents, error) {
-		return tools.CheckForErrorsInLogs(info.ESClient, info.Namespace, []string{})
-	})
-	t.Logf("errors: Got %d documents", len(docs.Hits.Hits))
-	for _, doc := range docs.Hits.Hits {
-		t.Logf("%#v", doc.Source)
+	// Stage 4: make sure all components are health
+	t.Log("Making sure all components are health")
```
Comment (ycombinator) [inline testing/integration/monitoring_logs_test.go:102]: Typo.

```suggestion
	t.Log("Making sure all components are healthy")
```

File: testing/integration/monitoring_logs_test.go [hunk 4]
```diff
@@ -111,16 +98,16 @@ func (runner *EnrollRunner) TestEnroll() {
...
+	status, err := agentFixture.ExecStatus(ctx)
+	require.NoError(t, err,
+		"could not get agent status to verify all components are health")
```
Comment (ycombinator) [inline testing/integration/monitoring_logs_test.go:105]: Typo.
```suggestion
		"could not get agent status to verify all components are healthy")
```

File: testing/integration/proxy_url_test.go [hunk 5]
```diff
@@ -392,19 +392,29 @@ func TestProxyURL_RemoveProxyFromThePolicy(t *testing.T) {
 	p.assertConnectedFleet(t)
 }
 
+// assertConnectedFleet is deprecated, use AssertConnectedToFleet instead
+// Deprecated.
 func (p *ProxyURL) assertConnectedFleet(t *testing.T) {
+	AssertConnectedToFleet(t, p.fixture)
+}
+
```
Comment (ycombinator) [inline testing/integration/proxy_url_test.go:400]: Why not just remove this function and replace all its calls with `AssertConnectedToFleet`? From what I can tell, this method is only being called from within `proxy_url_test.go`. Is it to keep the size of this PR small? In that case I'd do this cleanup in an immediate follow up PR so we don't forget about it.

File: testing/integration/proxy_url_test.go [hunk 6]
```diff
@@ -392,19 +392,29 @@ func TestProxyURL_RemoveProxyFromThePolicy(t *testing.T) {
...
-	}, 5*time.Minute, 5*time.Second,
+	}
+
+	connected := assert.Eventually(t, assertFn, 5*time.Minute, 5*time.Second,
 		"want fleet state %s, got %s. agent status: %v",
-		cproto.State_HEALTHY, cproto.State(agentStatus.FleetState), agentStatus) {
+		cproto.State_HEALTHY, cproto.State(agentStatus.FleetState), agentStatus)
+
+	if !connected {
 		if err != nil {
```
Comment (ycombinator) [inline testing/integration/proxy_url_test.go:416]: Nit: could be simplified.
```suggestion
	if !connected && err != nil {
```

File: testing/integration/proxy_url_test.go (hunk 5 above)
Comment (AndersonQ) [reply testing/integration/proxy_url_test.go:400]: it was temporary while I was checking exactly what the test was intended to do and if my fix worked. I'm fixing it all now

**Comment by AndersonQ** [comment]
@cmacknz I restored the test, changed its name to better reflect what it tests and fixed the issue. Could you re-review it?

@ycombinator, I applied your suggestions

**Review by ycombinator — APPROVED** [review]
LGTM.

File: testing/integration/monitoring_logs_test.go [hunk 7]
```diff
@@ -15,49 +15,34 @@ import (
...
 	"github.com/elastic/elastic-agent/pkg/testing/tools"
+	"github.com/elastic/elastic-agent/pkg/testing/tools/check"
 )
 
-func TestEnrollAndLog(t *testing.T) {
+func TestMonitoringLogsShipped(t *testing.T) {
 	info := define.Require(t, define.Requirements{
 		OS: []define.OS{
-			{Type: define.Linux},
+			{Type: define.Linux,
```
Comment (cmacknz) [inline testing/integration/monitoring_logs_test.go:32]: FYI the framework now supports doing this from the command line https://github.com/elastic/elastic-agent/blob/main/docs/test-framework-dev-guide.md#selecting-specific-platform

File: testing/integration/monitoring_logs_test.go [hunk 8]
```diff
@@ -111,21 +98,22 @@ func (runner *EnrollRunner) TestEnroll() {
 	require.NotZero(t, len(docs.Hits.Hits))
 	t.Logf("metricbeat: Got %d documents", len(docs.Hits.Hits))
 
-	// Stage 4: make sure we have no errors
-	t.Log("Making sure there are no error logs")
-	docs = findESDocs(t, func() (tools.Documents, error) {
-		return tools.CheckForErrorsInLogs(info.ESClient, info.Namespace, []string{})
```
Comment (cmacknz) [inline testing/integration/monitoring_logs_test.go:117]: What were the error logs this was failing on? Should they exist or are we just ignoring a bug with this? It may be better to filter out known false positives than to remove this. 

There have been a lot of problems in the logs that are hidden because we have no automation that can detect them, this is one of the few places that can do that for us.

I am worried we are "fixing" the test by making it a worse test.

Comment (AndersonQ) [reply testing/integration/monitoring_logs_test.go:117]: It's not the case here. The error logs were from the agent trying to connect to the default ES, `localhost:9200`. Besides using the health of the agent and its components makes the test better, the test won't be affected by changes in the log messages and transient/recoverable errors.

This tests want to ensure the agent enrolls and the monitoring works. If any issue happens and the agent is capable of recovering and reaches the final desired state, it's not an issue. It shows the "self-healing" strategies we have work. Also taking into consideration it's an e2e test we cannot control every single aspect of the process, what we need to ensure is the final state, the agent is enrolled and monitoring is working, what is being done by this test.

**Comment by AndersonQ** [comment]
@cmacknz could you review this PR again?
