### PR TITLE
increase internal/pkg/agent/install.RemovePath arbitrary timeout

### LINKED ISSUE #3221: [Flaky Test] TestRemovePath (internal/pkg/agent/install)
## Flaky Test

* **Test Name:** TestRemovePath (internal/pkg/agent/install).
* **Link:** [Link to file/line number in github.](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/install/uninstall_windows_test.go#L54)
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
   - https://github.com/elastic/elastic-agent/pull/3214
   - main
* **Artifact Link:** https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/PR-3214/4/pipeline/1973
* **Notes:** Perhaps the time between starting the binary and trying to remove it is, sometimes, so short windows considers other process is using it.

### Stack Trace

```
[2023-08-10T08:08:27.569Z] === Failed

[2023-08-10T08:08:27.569Z] === FAIL: internal/pkg/agent/install TestRemovePath (0.62s)

[2023-08-10T08:08:27.569Z]     uninstall_windows_test.go:54: 

[2023-08-10T08:08:27.569Z]         	Error Trace:	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall_windows_test.go:54

[2023-08-10T08:08:27.569Z]         	Error:      	Received unexpected error:

[2023-08-10T08:08:27.569Z]         	            	failed to open handle for "C:\\Users\\jenkins\\AppData\\Local\\Temp\\TestRemovePath1878842873\\001\\subdir\\main.exe": The process cannot access the file because it is being used by another process.

[2023-08-10T08:08:27.569Z]         	Test:       	TestRemovePath

[2023-08-10T08:08:27.569Z] 

```

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

increases internal/pkg/agent/install.RemovePath arbitraty timeout.

## Why is it important?

On non-CI machine 2s is enough, as it keeps failing on CI, let's increase it.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## How to test this PR locally

run the test, it should be skipped

## Related issues

- Closes #3221 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by blakerouse — CHANGES_REQUESTED** [review]
This is a code is a core path to uninstall. I do not believe we should just skip this test. See my comment on the issue filed for this test here on the testing that I did before merging it - https://github.com/elastic/elastic-agent/issues/3221#issuecomment-1673236802

Possible solution is to just adjust the time to ensure it keeps passing on the Windows runner.

**Comment by AndersonQ** [comment]
@blakerouse, done.

**Review by blakerouse — APPROVED** [review]
Thanks for adjusting the timeout instead of skipping the test. Hopefully this solves the problem on the Windows runner.

File: internal/pkg/agent/install/uninstall.go [hunk 1]
```diff
@@ -97,8 +97,8 @@ func Uninstall(cfgFile, topPath, uninstallToken string) error {
 // to an ERROR_SHARING_VIOLATION. RemovePath will retry up to 2
 // seconds if it keeps getting that error.
 func RemovePath(path string) error {
-	const arbitraryTimeout = 2 * time.Second
-	var start time.Time
+	const arbitraryTimeout = 5 * time.Second
```
Comment (pchila) [inline internal/pkg/agent/install/uninstall.go:100]: Sorry to be "that guy" but why are we spinning in this for loop instead of sleeping between iterations?

Reading the code I thought we would sleep between attempts until we would exceed the timeout...

File: internal/pkg/agent/install/uninstall.go [hunk 2]
```diff
@@ -97,8 +97,8 @@ func Uninstall(cfgFile, topPath, uninstallToken string) error {
...
+	start := time.Now()
```
Comment (pchila) [inline internal/pkg/agent/install/uninstall.go:101]: Not sure if it's relevant but before the change we would start counting time from the first error, now we do it even before the first attempt...

One possible side effect is that if the first `os.RemoveAll` takes longer than than the timeout we would not retry this.
