### PR TITLE
Better error handling for flavor detection

### LINKED ISSUE #6729: [Flaky Test]: TestStandaloneUpgradeSameCommit – Error: Failed trigger upgrade of daemon: open : The system cannot find the file specified.
### Failing test case

TestStandaloneUpgradeSameCommit/Upgrade_on_a_repackaged_version_of_agent_9.0.0-SNAPSHOT_(unprivileged)

### Error message

Error: Failed trigger upgrade of daemon: open : The system cannot find the file specified.

### Build

https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/1350#0194daae-65c2-4d84-83d3-99c13e0c7e13

### OS

Windows

### Stacktrace and notes

```markdown
It seems that the agent fails to unpack the local repackaged artifact (but the download step seems to pass, which is weird).
```

### LINKED ISSUE #6731: [Flaky Test]: TestStandaloneUpgradeRetryDownload – Error: Failed trigger upgrade of daemon: open : The system cannot find the file specified.
### Failing test case

TestStandaloneUpgradeRetryDownload

### Error message

Error: Failed trigger upgrade of daemon: open : The system cannot find the file specified.

### Build

https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/1350#0194daae-65c2-4d84-83d3-99c13e0c7e13

### OS

Windows

### Stacktrace and notes

```markdown
The agent tries to download the archive twice before giving up (the requests are denied both times on purpose as we can see from the test logs), hence the failure
```

### LINKED ISSUE #6732: [Flaky Test]: TestStandaloneUpgradeWithGPGFallbackOneRemoteFailing – Error: Failed trigger upgrade of daemon: open : The system cannot find the file specified.
### Failing test case

TestStandaloneUpgradeWithGPGFallbackOneRemoteFailing

### Error message

Error: Failed trigger upgrade of daemon: open : The system cannot find the file specified.

### Build

https://buildkite.com/elastic/elastic-agent-extended-testing-bk/builds/1350#0194daae-65c2-4d84-83d3-99c13e0c7e13

### OS

Windows

### Stacktrace and notes

```markdown
Very similar failure to TestStandaloneUpgradeSameCommit: it seems like the agent is able to pick up the archive but then it fails to unpack
```

### PR DESCRIPTION
**Pull request by michalpristas**
This PR adds better error handling for flavor detection when manifest file is not found during extracting tar/zip packages.
Backward upgrade tests now working, un-skipping them

## Related issues
Closes #6731
Closes #6729 
Closes #6732

### CODE REVIEW

File: internal/pkg/agent/application/upgrade/step_unpack.go [hunk 1]
```diff
@@ -219,19 +219,26 @@ func getPackageMetadataFromZip(archivePath string) (packageMetadata, error) {
...
-			return func(relPath string) bool { return false }, nil
+			return acceptAllFn, nil
 		}
 		return nil, err
 	}
+
+	// no flavor loaded
+	if flavor.Name == "" {
+		return acceptAllFn, nil
+	}
```
Comment (swiatekm) [inline internal/pkg/agent/application/upgrade/step_unpack.go:240]: How does this actually happen? Is there a flavor in the registry with an empty name? Intuitively, it makes more sense to me to try to prevent this occurrence in the first place instead of handling it downstream like this.

Comment (swiatekm) [reply internal/pkg/agent/application/upgrade/step_unpack.go:240]: Maybe add a comment if you want to keep it? Right now, it suggests this can actually happen.

File: internal/pkg/agent/application/upgrade/step_unpack.go [hunk 2]
```diff
@@ -219,19 +219,26 @@ func getPackageMetadataFromZip(archivePath string) (packageMetadata, error) {
...
 	}
 
 	flavor, err := install.Flavor(detectedFlavor, "", registry)
 	if err != nil {
 		if errors.Is(err, install.ErrUnknownFlavor) {
 			// unknown flavor fallback to copy all
-			return func(relPath string) bool { return false }, nil
+			return acceptAllFn, nil
 		}
 		return nil, err
```
Comment (pkoutsovasilis) [inline internal/pkg/agent/application/upgrade/step_unpack.go:234]: since I was part of the initial investigation of why these tests were failing, something that was clearly missing from this code, is error wrapping with distinguishable messages. Could you please introduce proper error wrapping in the returned errors? 🙂

Comment (pchila) [reply internal/pkg/agent/application/upgrade/step_unpack.go:234]: This is an important bit that would allow us to have a better error than "open : The system cannot find the file specified."

File: internal/pkg/agent/install/flavors.go [hunk 3]
```diff
@@ -55,11 +55,15 @@ func Flavor(detectedFlavor string, registryPath string, flavorsRegistry map[stri
 	if flavorsRegistry == nil {
 		f, err := os.Open(registryPath)
 		if err != nil {
-			return FlavorDefinition{}, err
+			if os.IsNotExist(err) {
```
[the remark this answers is not in the document]
Comment (michalpristas) [reply internal/pkg/agent/install/flavors.go:58]: previously it was used by other code path where registry was not opened before. yes this can be cleaned up now

[the remark this answers is not in the document]
Comment (michalpristas) [reply internal/pkg/agent/install/flavors.go:58]: but as this does not address the bugs and alters a behavior i will address it separately
