### PR TITLE
Fix flaky test `TestActionDispatcher/Cancel_queued_action`

### LINKED ISSUE #3137: [Flaky test] TestActionDispatcher/Cancel_queued_action
## Flaky Test

* **Test Name:** TestActionDispatcher/Cancel_queued_action
* **Link:** https://github.com/elastic/elastic-agent/blob/274a347f7ada81bc5a3658268457c1c9d3e254ff/internal/pkg/agent/application/dispatcher/dispatcher_test.go#L260.
* **Branch:** main / #2834.
* **Artifact Link:** https://fleet-ci.elastic.co/job/elastic-agent/job/elastic-agent-mbp/job/PR-2834/48/artifact/tests-errors.json/*view*
* **Notes:** N/A

### Stack Trace

Failure 1:
```
=== RUN   TestActionDispatcher/Cancel_queued_action
    dispatcher_test.go:255: PASS:	Handle(string,string,string)
    dispatcher_test.go:256: FAIL:	Save()
        		at: [/var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-2859/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/dispatcher/dispatcher_test.go:233]
    dispatcher_test.go:256: PASS:	DequeueActions()
    dispatcher_test.go:256: FAIL: 1 out of 2 expectation(s) were met.
        	The code you are testing needs to make 1 more call(s).
        	at: [/var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-2859/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/dispatcher/dispatcher_test.go:256]
    --- FAIL: TestActionDispatcher/Cancel_queued_action (0.00s)
```

Failure 2:
```
[2023-07-27T13:20:44.703Z] === FAIL: internal/pkg/agent/application/dispatcher TestActionDispatcher/Cancel_queued_action (0.00s)
[2023-07-27T13:20:44.703Z]     dispatcher_test.go:259: PASS:	Handle(string,string,string)
[2023-07-27T13:20:44.703Z]     dispatcher_test.go:260: FAIL:	Save()
[2023-07-27T13:20:44.703Z]         		at: [/var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-2834/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/dispatcher/dispatcher_test.go:236]
[2023-07-27T13:20:44.703Z]     dispatcher_test.go:260: FAIL:	DequeueActions()
[2023-07-27T13:20:44.703Z]         		at: [/var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-2834/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/dispatcher/dispatcher_test.go:237]
[2023-07-27T13:20:44.703Z]     dispatcher_test.go:260: FAIL: 0 out of 2 expectation(s) were met.
[2023-07-27T13:20:44.703Z]         	The code you are testing needs to make 2 more call(s).
[2023-07-27T13:20:44.703Z]         	at: [/var/lib/jenkins/workspace/_agent_elastic-agent-mbp_PR-2834/src/github.com/elastic/elastic-agent/internal/pkg/agent/application/dispatcher/dispatcher_test.go:260]
[2023-07-27T13:20:44.703Z] 
[2023-07-27T13:20:44.703Z] === FAIL: internal/pkg/agent/application/dispatcher TestActionDispatcher (0.44s)
```

### PR DESCRIPTION
**Pull request by andrzej-stencel**
## What does this PR do?

Fixes flaky test `TestActionDispatcher/Cancel_queued_action`.

## Why is it important?

We don't want flaky tests.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Related issues

- Fixes #3137

The issue was closed as the test in question stopped failing. The thing is, the test stopped failing only because the flaky assertion had been commented out.

## Details

When I first read the test's body, I wasn't sure what the test's purpose was. Here's what I understood from it:

```
When I create a dispatcher with a default handler
And I dispatch an action of type Cancel
Then the handler is called for the action of type Cancel
And the Dispatch function returns without blocking on the error channel
```

The test is pretty low level and I'm not quite certain of the test's usefulness. Nevertheless, I believe I know why the test was flaky and I believe I was able to fix the flakiness. See individual commits:
- [Fix flaky test](https://github.com/elastic/elastic-agent/commit/a0fc98eb25b4451a89e238b24df93275cb5478b2) has the actual test fix with a detailed description in the commit message.
- [Remove unnecessary handler registration](https://github.com/elastic/elastic-agent/commit/32964e35e976667750e5aa38ed6e5f43ccc3ba67) removes two lines of the test's code that I believe change nothing other than introducing unnecessary confusion.
- [Narrow down mock parameters](https://github.com/elastic/elastic-agent/commit/cd410d52bb9217e366025030a7d60a61d0ec91fc) improves the test by replacing `mock.Anything` parameters in the `Handle` method mock with actual variables `dispatchCtx`, `action`, `ack`.

### CODE REVIEW

**Review by pchila — APPROVED** [review]
LGTM

File: internal/pkg/agent/application/dispatcher/dispatcher_test.go [hunk 1]
```diff
@@ -231,41 +231,38 @@ func TestActionDispatcher(t *testing.T) {
...
+
 		select {
 		case err := <-d.Errors():
 			t.Fatalf("Unexpected error: %v", err)
-		case <-calledCh:
-			// Handle was called, expected
-		case <-time.After(1 * time.Second):
-			t.Fatal("mock Handle never called")
+		case <-dispatchCompleted:
+			// OK, expected to complete the dispatch without blocking on the errors channel
```
Comment (blakerouse) [inline internal/pkg/agent/application/dispatcher/dispatcher_test.go:261]: If this never happens and nothing ever comes over `d.Errors()` doesn't this mean this test is now stuck?

I believe the `case <-time.After(1 * time.Second)` was added to fail in this case. Possible this should be kept, but maybe with a longer time? Even if its bumped to 10 seconds, just to prevent it from deadlocking here.

Comment (andrzej-stencel) [reply internal/pkg/agent/application/dispatcher/dispatcher_test.go:261]: The test timeout should take care of this scenario.

I believe the current test timeout is the [default](https://pkg.go.dev/cmd/go#hdr-Testing_flags) 10 minutes, which is a bit lengthy for actual unit tests.
