### PR TITLE
Return actionable error message when enrolling

### LINKED ISSUE #4889: Actionable error message when attempting to `enroll` an unprivileged Agent as a privileged user
**Version: 8.14.0**
**Operating System: Ubuntu 24.04 LTS**
**Platform: arm64**

While working on [this issue](https://github.com/elastic/elastic-agent/issues/4705) comparing root and unprivileged elastic agents, I encountered an error with the `enroll` command when using unprivileged agent.

**Steps to Reproduce:**
1. Deploy ESS v8.14.0
2. Create agent policy with system integration
3. Install fleet managed agent with the unprivileged flag `sudo ./elastic-agent install --unprivileged --url=<fleet url> --enrollment-token=<token>` 
4. Unenroll the agent 
5. Enroll the agent `sudo elastic-agent enroll --url=<fleet url> --enrollment-token=<token>`
6. Agent enrollment gets confirmed, but incoming data does not get confirmed
7. Agent status in fleet ui is stuck in `updating`
8. Running `sudo elastic-agent status` we get the following error

```
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /opt/Elastic/Agent/elastic-agent.sock: connect: connection refused"
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.14/fleet-troubleshooting.html
```

## Definition of Done

_Based on discussion in the comments:_

* [ ] When a user `install`s an Agent using `--unprivileged`, then tries to `enroll` this Agent with a privileged user, an error message with the suggestions in https://github.com/elastic/elastic-agent/issues/4889#issuecomment-2158635347 is shown to the user.

### PR DESCRIPTION
**Pull request by kaanyalti**
- Enhancement

## What does this PR do?

This PR adds checks to the enroll command to respond with an error message in case the user executing the command and the user that's the owner of the elastic program files don't match. Replaces #6038 based on the [following comment](https://github.com/elastic/elastic-agent/pull/6038#discussion_r1850253347) 

## Why is it important?

Currently there are no checks in place to prevent or correct the situation where a user who is not the owner of the program files executes enroll. This leads to a broken state.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## How to test this PR locally

**The testing steps are only for linux and mac**
- Deploy ess, install agent in unprivileged mode and enroll into fleet
- Unenroll the agent from the fleet ui
- Run the enroll command as root user and validate the error message
## Related issues

- Closes #4889

### CODE REVIEW

File: internal/pkg/agent/cmd/enroll_match_fileowner_unix.go [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+func getCurrentUser() (string, error) {
+	return strconv.Itoa(os.Geteuid()), nil
+}
+
+func isFileOwner(curUser string, fileOwner string) (bool, error) {
+	return curUser == fileOwner, nil
+}
+
+func isEnroll() (bool, error) {
```
Comment (michalpristas) [inline internal/pkg/agent/cmd/enroll_match_fileowner_unix.go:37]: i don't think `isEnroll` is a proper name for this. not sure it captures properly what this func is doing

Comment (kaanyalti) [reply internal/pkg/agent/cmd/enroll_match_fileowner_unix.go:37]: I can also split this function into its constituent functions. It would be more readable. All the steps would be clearly outlined. I couldn't come up with a reasonably short function name that describes exactly what's happening.

If I split it, these functions will be called in order in enroll.go
- getFileOwner
- getCurrentUser
- isFileOwner

File: internal/pkg/agent/cmd/enroll.go [hunk 2]
```diff
@@ -351,6 +353,20 @@ func enroll(streams *cli.IOStreams, cmd *cobra.Command) error {
...
+	if err != nil {
+		return fmt.Errorf("checking if running with root/Administrator privileges: %w", err)
+	}
+	if hasRoot && !fromInstall {
+		isEnroll, err := isEnroll()
+		if err != nil {
+			return fmt.Errorf("ran into an error while figuring out if user is allowed to execute the enroll command")
+		}
+		if !isEnroll {
+			return UserOwnerMismatchError
```
Comment (blakerouse) [inline internal/pkg/agent/cmd/enroll.go:366]: On Windows you cannot actually open a shell as the `elastic-agent-user` so how would they be able to run enroll command on Windows as the `elastic-agent-user`.

File: internal/pkg/agent/cmd/enroll_match_fileowner_unix.go (hunk 1 above)
Comment (blakerouse) [reply internal/pkg/agent/cmd/enroll_match_fileowner_unix.go:37]: I agree with @michalpristas here, this is not the proper name for this function. It is just verifying that the executing users is the same as the owner of the executable.

To me the better name would be `isOwnerExec`?

File: internal/pkg/agent/cmd/enroll.go (hunk 2 above)
Comment (kaanyalti) [reply internal/pkg/agent/cmd/enroll.go:366]: I can return an error message stating the fact that user cannot execute the command as admin for windows. Linux/mac error message will can still mention running the command as the elastic-agent-user

File: changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+# - enhancement: extends functionality but does not break or fix existing behavior
+# - feature: new functionality
+# - known-issue: problems that we are aware of in a given version
+# - security: impacts on the security of a product or a user’s deployment.
+# - upgrade: important information for someone upgrading from a prior version
+# - other: does not fit into any of the other categories
+kind: enhancement
+
+# Change summary; a 80ish characters long description of the change.
+summary: Elastic agent returns an actionable error message when a root user tries to enroll an unprivileged agent that has been unenrolled via the fleet ui
```
Comment (michalpristas) [inline changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml:14]: `has been unenrolled` - really?

File: changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+component: elastic-agent
+
+# PR URL; optional; the PR number that added the changeset.
+# If not present is automatically filled by the tooling finding the PR where this changelog fragment has been added.
+# NOTE: the tooling supports backports, so it's able to fill the original PR number instead of the backport PR number.
+# Please provide it if you are adding a fragment for a different PR.
+pr: https://github.com/elastic/elastic-agent/pull/6144
+# Issue URL; optional; the GitHub issue related to this changeset (either closes or is part of).
+# If not present is automatically filled by the tooling with the issue linked to the PR number.
+#issue: https://github.com/owner/repo/1234
```
Comment (michalpristas) [inline changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml:31]: please incude issue as well, we have a public one

File: internal/pkg/agent/cmd/enroll.go [hunk 5]
```diff
@@ -351,6 +351,24 @@ func enroll(streams *cli.IOStreams, cmd *cobra.Command) error {
...
+	hasRoot, err := utils.HasRoot()
+	if err != nil {
+		return fmt.Errorf("checking if running with root/Administrator privileges: %w", err)
+	}
+	if hasRoot && !fromInstall {
+		binPath, err := os.Executable()
+		if err != nil {
+			return fmt.Errorf("error while getting executabel path: %w", err)
+		}
+		oe, err := isOwnerExec(binPath)
```
Comment (michalpristas) [inline internal/pkg/agent/cmd/enroll.go:363]: `oe` naming is unreadable further in the code. try something more self-describing

File: internal/pkg/agent/cmd/enroll.go [hunk 6]
```diff
@@ -351,6 +351,24 @@ func enroll(streams *cli.IOStreams, cmd *cobra.Command) error {
...
+		if err != nil {
+			return fmt.Errorf("ran into an error while figuring out if user is allowed to execute the enroll command")
```
Comment (michalpristas) [inline internal/pkg/agent/cmd/enroll.go:365]: wrap an error, we are hiding it now, don't know the underlying issue. then you can simplify wrapped text

File: internal/pkg/agent/cmd/enroll_match_fileowner_unix.go [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+
+func getCurrentUser() (string, error) {
+	return strconv.Itoa(os.Geteuid()), nil
+}
+
+func isFileOwner(curUser string, fileOwner string) (bool, error) {
+	return curUser == fileOwner, nil
+}
+
+func isOwnerExec(filePath string) (bool, error) {
```
Comment (michalpristas) [inline internal/pkg/agent/cmd/enroll_match_fileowner_unix.go:41]: please add a single line comment describing that this evaluates if current user is an owner of a file

File: internal/pkg/agent/cmd/enroll_match_fileowner_unix.go [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+	if err != nil {
+		return false, fmt.Errorf("failed to get current user: %w", err)
+	}
+
+	isOwner, err := isFileOwner(curUser, owner)
+	if err != nil {
+		return false, fmt.Errorf("error while checking if current user is the file owner: %w", err)
+	}
+
+	if !isOwner {
```
Comment (michalpristas) [inline internal/pkg/agent/cmd/enroll_match_fileowner_unix.go:57]: can be `return isOwner, nil`

File: testing/integration/enroll_unprivileged_test.go [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+
+		if runtime.GOOS != "windows" {
+			out, err := exec.CommandContext(ctx, "elastic-agent", enrollArgs...).CombinedOutput()
+			require.Error(t, err)
+			require.Contains(t, string(out), cmd.UserOwnerMismatchError.Error())
+		} else {
+			out, err := exec.CommandContext(ctx, "C:\\Program Files\\Elastic\\Agent\\elastic-agent.exe", enrollArgs...).CombinedOutput()
+			require.Error(t, err)
+			require.Contains(t, string(out), cmd.UserOwnerMismatchError.Error())
+		}
```
Comment (pchila) [inline testing/integration/enroll_unprivileged_test.go:84]: This command should work correctly on multiple OSes you use `fixture.Exec()`, something like:
```suggestion
		out, err := fixture.Exec(ctx, enrollArgs...)
		require.Error(t, err)
		require.Contains(t, string(out), cmd.UserOwnerMismatchError.Error())
```

**Review by pchila — COMMENTED** [review]
Looks good overall, some refactoring may be needed on the tests to make sure we keep relevant behavior tests rather than unit tests that are too small and too fine-grained

A couple of comments about error handling to avoid swallowing inner errors that should be addressed before merging though

File: changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml (hunk 3 above)
Comment (kaanyalti) [reply changelog/fragments/1732656422-add-actionable-error-message-for-enroll-command.yaml:14]: This indeed is not the case, it is all enroll commands except for the one initiated by the install command. Updating right away

File: internal/pkg/agent/cmd/enroll_match_fileowner_windows_test.go [hunk 10]
```diff
@@ -0,0 +1,104 @@
...
+
+	tokenUser, err := token.GetTokenUser()
+	require.NoError(t, err)
+
+	tStr := tokenUser.User.Sid.String()
+
+	eq, err := isFileOwner(tStr, tStr)
+	require.NoError(t, err)
+	require.True(t, eq, fmt.Sprintf("expected \"true\" received \"%v\"", eq))
+}
```
[the remark this answers is not in the document]
Comment (kaanyalti) [reply internal/pkg/agent/cmd/enroll_match_fileowner_windows_test.go:69]: I mainly added the unit tests to satisfy sonarqube requirements. I think the integration test covers the behaviour well enough. That being said, the `TestGetFileOwner` and `TestIsFileOwner` tests are redundant when `TestIsOwnerExec` already covers what the other two tests cover. I will remove the unnecessary tests right away. When it comes to having a single test file, unfortunately as you suspected, windows does not set the file ownership correctly when. I have to explicitly have to set it. So I don't think I can combine them both, unless I go with `runtime.GOOS` check.

**Review by michalpristas — APPROVED** [review]
tested on darwin and windows. works ok

thanks for addressing all the comments

**Comment by kaanyalti** [comment]
buildkite test this

**Comment by jlind23** [comment]
@kaanyalti shall we backport this to 8.17 too? For now by backporting to 8.x it will only be included in 8.18

**Comment by kaanyalti** [comment]
@jlind23  I think we can, I don't see any reason not to backport it to 8.17.
