### PR TITLE
Fix troubleshooting message URL for versions after 9.x

### LINKED ISSUE #10119: Troubleshooting message generates invalid URL in 9.x
Elastic Agent can return a troubleshooting message with a link to the docs: 

```
Error: unable to perform install command, not executed with root permissions
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/9.1/fleet-troubleshooting.html
````

Prior to 9.0, the Elastic docs created a new section for each minor: `https://www.elastic.co/guide/en/fleet/<version>/fleet-troubleshooting.html`.

The docs for 9.0+ don't refer to a specific version: https://www.elastic.co/docs/troubleshoot/ingest/fleet/common-problems, so the URL returned to the user in the error output is invalid.

### PR DESCRIPTION
**Pull request by straistaru**
## What does this PR do?

Ensure the docs URL in the troubleshoot message matches the correct release version.
The docs for 9.0+ don't refer to a specific version anymore: https://www.elastic.co/docs/troubleshoot/ingest/fleet/common-problems, so the URL returned to the user in the error output is invalid.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~

## Related issues

- Closes #10119

### CODE REVIEW

**Comment by straistaru** [comment]
Noticed that `release.Version()` will try to use the version from the `package.version` file instead of just a hard-coded value in the agent binary.

Is it a supported scenario for an elastic-agent build above `9.x` to read a `package.version` file with a version different from its build version? Would a user ever be expected to encounter this, or is it considered unsupported?
If it's not, the function can be simplified to a const with the new docs URL, and we wouldn’t backport the fix to pre-9.x branches.

EDIT: Answer below from Paolo.

File: internal/pkg/agent/cmd/common.go [hunk 1]
```diff
@@ -23,8 +24,19 @@ import (
...
+	docsURL := "https://www.elastic.co/docs/troubleshoot/ingest/fleet/common-problems"
+
+	// Use versioned docs for releases before 9.x. Fall back to unversioned docs on parse errors
+	// or when the version string is not in the expected format.
+	if len(v) >= 2 {
+		major, err := strconv.Atoi(v[0])
+		if err == nil && major < 9 {
+			ver := strings.Join(v[:2], ".")
+			docsURL = fmt.Sprintf("https://www.elastic.co/guide/en/fleet/%s/fleet-troubleshooting.html", ver)
+		}
```
Comment (pchila) [inline internal/pkg/agent/cmd/common.go]: As discussed, it should be simpler to just handle the new url for  >=9.0.0 and not backport the change on any 8.x branch

File: internal/pkg/agent/cmd/run.go [hunk 2]
```diff
@@ -715,12 +716,23 @@ func initTracer(agentName, version string, mcfg *monitoringCfg.MonitoringConfig)
...
+	}
+
+	if err = report.SetupMetricsOptions(report.MetricOptions{
+		Name:           agentName,
+		Version:        version.GetDefaultVersion(),
+		EphemeralID:    ephemeralID.String(),
+		Logger:         logger,
+		SystemMetrics:  monitoringLib.Default.GetOrCreateRegistry("system"),
+		ProcessMetrics: monitoringLib.Default.GetOrCreateRegistry("beat"),
+	}); err != nil {
```
Comment (pchila) [inline internal/pkg/agent/cmd/run.go]: This is here to fix the deprecation of report.SetupMetrics ? 

Would it be possible to take this out of this PR and substitute with a `//nolint` comment ? 

Asking mostly because the way of removing the deprecation warning is not documented and I am not comfortable just pasting here the implementation of `report.SetupMetrics` with an ephemeral UUID

Comment (straistaru) [reply internal/pkg/agent/cmd/run.go]: > This is here to fix the deprecation of report.SetupMetrics ?

Yes

> Would it be possible to take this out of this PR and substitute with a //nolint comment ?

Sure, I can do that.
