### PR TITLE
Fix RPM prefix installation to copy service file instead of symlink.

### LINKED ISSUE #13283: RPM installation should not use a symlink in /etc/systemd/system
The RPM installation of the Elastic Agent places a symlink in `/etc/systemd/system` to the service file at `{prefix}/Agent/lib/systemd/system/elastic-agent.service`. When `{prefix}` is on another mount, there is no guarantee that it will be mounted before systemd goes to read the service files on startup.

The Elastic Agent RPM should just install the service file at `/etc/systemd/system` always. `/etc/systemd/system` must be mounted correctly for systemd to even work so placing it in this location removes this edge case.

For confirmed bugs, please report:
- Version: All
- Operating System: Linux
- Steps to Reproduce:
  - Create a VM or a host that has `/opt` as a seperate mount
  - Install the Elastic Agent RPM with `--prefix=/opt/Elastic`
  - Restart the host (Elastic Agent doesn't start)

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes the RPM installation with `--prefix` to copy the service file to `/lib/systemd/system`.

## Why is it important?

The service file needs to be placed into `/lib/systemd/system` and not symlinked, because symlinking doesn't gaurentee that the mount point will be available when `systemd` reads the symlink point to a different mount.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test (RPM install is validated)

## Disruptive User Impact

None

## How to test this PR locally

- Build the RPM package.
- Create a RPM based distro with /opt on a seperate mount point.
- Install with `--prefix=/opt/Elastic`.
- Reboot and verify that Elastic Agent starts.

## Related issues

- Closes #13283

### CODE REVIEW

File: dev-tools/packaging/templates/linux/postrm.sh.tmpl [hunk 1]
```diff
@@ -29,13 +29,9 @@ case "$1" in
...
-        echo "Found elastic-agent.service link, unlink"
-        unlink /lib/systemd/system/elastic-agent.service
-    fi
-    if test -L /etc/systemd/system/elastic-agent.service; then
-        echo "Found /etc/systemd/system/elastic-agent.service link, unlink"
-        unlink /etc/systemd/system/elastic-agent.service
+    if test -L /lib/systemd/system/elastic-agent.service || test -f /lib/systemd/system/elastic-agent.service; then
+        echo "Found /lib/systemd/system/elastic-agent.service, removing"
+        rm -f /lib/systemd/system/elastic-agent.service
     fi
```
Comment (ycombinator) [inline dev-tools/packaging/templates/linux/postrm.sh.tmpl:39]: Should we keep this code in, for users who upgrade from an older installation?  Otherwise, I believe a dangling `/etc/systemd/system/elastic-agent.service` symlink would be left behind?

That said, I can't find anywhere in the Agent code where this symlink is being created in the first place.  It looks like this code was introduced in https://github.com/elastic/elastic-agent/pull/12263.  @michel-laterman do you recall why it was needed at the time?

Comment (michel-laterman) [reply dev-tools/packaging/templates/linux/postrm.sh.tmpl:39]: I think the `/etc/systemd` link is created at install time by RPM; I'm going to run the rpm installer on a VM to see if it works as expected

Comment (michel-laterman) [reply dev-tools/packaging/templates/linux/postrm.sh.tmpl:39]: Installing 9.3.2 with prefix results in:
```
[ec2-user@ip-172-31-22-105 ~]$ ls -la /etc/systemd/system/elastic-agent.service
lrwxrwxrwx.  1 root root   59 Mar 24 16:28 elastic-agent.service -> /opt/elastic-agent/lib/systemd/system/elastic-agent.service
```

Upgrading to a snapshot built with this PR via `sudo rpm -U --prefix /opt/elastic-agent ./elastic-agent-9.4.0-SNAPSHOT-x86_64.rpm`

But the link still exists after the upgrade:
```
ls -la /etc/systemd/system/elastic-agent.service
lrwxrwxrwx. 1 root root 59 Mar 24 16:28 /etc/systemd/system/elastic-agent.service -> /opt/elastic-agent/lib/systemd/system/elastic-agent.service
```

However after uninstall it's removed as expected:
```
[ec2-user@ip-172-31-22-105 ~]$ sudo rpm -e elastic-agent
found symlink /opt/elastic-agent/usr/share/elastic-agent/bin/elastic-agent, unlink
Found elastic-agent.service link, unlink
systemd daemon-reload
[ec2-user@ip-172-31-22-105 ~]$ ls /opt/elastic-agent/usr/share/elastic-agent/bin/elastic-agent
ls: cannot access '/opt/elastic-agent/usr/share/elastic-agent/bin/elastic-agent': No such file or directory=
```

I tried building an RPM with the `if test -L /etc/systemd/system/elastic-agent.service; then` statement still present in the 9.4.0 rpm and the link to from /etc/systemd to /opt/elastic-agent was still present.
So I think we still handle the link when upgrading in the postinstall.sh script

Comment (blakerouse) [reply dev-tools/packaging/templates/linux/postrm.sh.tmpl:39]: I have updated this to unlink if the link is present and then do the copy. That ensures on upgrade that it will replace the symlink with the actual file.

This should now be working for both new installation and upgrade.

**Comment by blakerouse** [comment]
@michel-laterman Give this another review, I have it working along with adding a check in the new integration tests to confirm.

File: dev-tools/packaging/templates/linux/postinstall.sh.tmpl [hunk 2]
```diff
@@ -75,9 +75,22 @@ if [[ ${PREFIX} != "" ]]; then
...
+    # pointing into the prefix mount; unlink them so cp creates a real file and systemctl enable recreates the
+    # /etc/systemd/system/ link pointing at the new /lib/systemd/system/ copy instead of the prefix path.
+    if test -L /lib/systemd/system/elastic-agent.service; then
+        echo "removing legacy symlink /lib/systemd/system/elastic-agent.service"
+        unlink /lib/systemd/system/elastic-agent.service
+    fi
+    if test -L /etc/systemd/system/elastic-agent.service; then
+        echo "removing legacy symlink /etc/systemd/system/elastic-agent.service"
+        unlink /etc/systemd/system/elastic-agent.service
+    fi
```
Comment (michel-laterman) [inline dev-tools/packaging/templates/linux/postinstall.sh.tmpl:90]: After upgrading from a previous version to this version; or on a fresh install, no new link gets created from `/etc/systemd/system/elastic-agent.service -> /lib/systemd/system/elastic-agent.service`
But `systemctl status elastic-agent.service` functions, and the service comes up after a restart.
I'm not sure if there are other side effects, but we probably should make sure that the link here points at the `/lib/systemd/system/elastic-agent.service` file; i think if we just added another `ln -s` below the coppy on line. 93 we would be ok

Comment (michel-laterman) [reply dev-tools/packaging/templates/linux/postinstall.sh.tmpl:90]: Actually I don't think we need the link, enable creates one in `/etc/systemd/system/multi-user.target.wants/elastic-agent.service`
