### PR TITLE
change elasticsearch configuration DecodeHook function to handle string to []string

### LINKED ISSUE #11352: OTel manager failed: failed to generate otel config: error translating config for output: ... source data must be an array or slice, got string
To reproduce in 9.2.1 use the following configuration and run the agent with the command:

```sh
ELASTIC_ENDPOINT="myESHost:9200" ./elastic-agent run -e --develop
```

```yaml
  outputs:
    default:
      type: elasticsearch
      hosts: ${ELASTIC_ENDPOINT}
      api_key: "example-key"
      preset: balanced

  agent.monitoring:
    enabled: true
    metrics: true
    logs: true
    use_output: default

  inputs:
    - id: unique-system-metrics-id
      type: system/metrics
      streams:
        - metricset: load
          data_stream.dataset: system.cpu
```

The agent will become unhealthy with the following error:

```yaml
message: |-
    OTel manager failed: failed to generate otel config: error translating config for output: monitoring, unit: prometheus/metrics-monitoring, error: failed decoding config. decoding failed due to the following error(s):

    'hosts' source data must be an array or slice, got string
```

Looking at how Filebeat (or Metricbeat) want the hosts format to be they want it to be a list: https://www.elastic.co/docs/reference/beats/filebeat/elasticsearch-output#hosts-option so at first glance this error seems correct:

```yaml
output.elasticsearch:
  hosts: ["https://myEShost:9200"]
```

However Beats will happily start if you use a string instead, so we have become more strict than before. The following config will run for a standalone beat where as it fails with a 9.2.1 agent if it is used in the monitoring output.

```yaml
filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - /var/log/*.log

output.elasticsearch:
  hosts: "myESHost:9200"
```

The workaround is to fix the format of `hosts` to be a list the way it is expected to be. Since there is only one host the config change below will fix it immediately (`hosts: ["${ELASTICSEARCH_HOST}"]` also works):

```yaml
outputs:
    default:
        hosts: 
            - ${ELASTICSEARCH_HOST}
```

### PR DESCRIPTION
**Pull request by leehinman**
## What does this PR do?

Change elasticsearch configuration DecodeHook function to convert a single string to a slice of string with one value if the destination type is a slice of string.

## Why is it important?

Beats configs allow for single values when the type is an slice.  For example `ssl.certificate_authorities` is a slice of strings, but beat configuration allows for these to be a string instead of a slice with one entry.

## Checklist

- [ ] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [ ] I have added an integration test or an E2E test

## How to test this PR locally

```
cd internal/pkg/otel/translate
go test .
```

## Related issues

- Closes #11352

## Questions to ask yourself

- How are we going to support this in production?
- How are we going to measure its adoption?
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

**Review by ycombinator — COMMENTED** [review]
While this change would work, it seems the only effect we're interested in is:

> single values are converted to slices if required. Each element is weakly decoded. For example: "4" can become []int{4} if the target type is an int slice. 

Since we're already defining a `DecodeHook` function, `cfgDecodeHookFunc`, would it be possible to use this function to convert `T` values into `[]T` values if the target type is `[]T`?  That might be preferable/safer if we don't want or expect the rest of the implications of using `WeaklyTypedInput`?

**Comment by leehinman** [comment]
> Since we're already defining a `DecodeHook` function, `cfgDecodeHookFunc`, would it be possible to use this function to convert `T` values into `[]T` values if the target type is `[]T`? That might be preferable/safer if we don't want or expect the rest of the implications of using `WeaklyTypedInput`?

I was waffling on this myself.  I leaned towards the `WeaklyTypedInput` because beats config is so permissive, but since it set off your Spidey Senses too, l'll switch to the more targeted approach.  If we hit more of these we can re-evaluate.

File: internal/pkg/otel/translate/output_elasticsearch_test.go [hunk 1]
```diff
@@ -173,6 +173,51 @@ compression_params:
 		compareAndAssert(t, expOutput, confmap.NewFromStringMap(got))
 	})
 
+	t.Run("ssl.certificate_authorities can be a string", func(t *testing.T) {
+		beatCfg := `
+hosts: "localhost:9200"
+index: "some-index"
+api_key: "TiNAGG4BaaMdaH1tRfuU:KnR6yE41RrSowb0kQ0HWoA"
+ssl.certificate_authorities: "/not/a/real/path/ca.pem"
```
Comment (cmacknz) [inline internal/pkg/otel/translate/output_elasticsearch_test.go:181]: There are a couple more list types we should proactively check:

- https://www.elastic.co/docs/reference/beats/filebeat/configuration-ssl#supported-protocols
- https://www.elastic.co/docs/reference/beats/filebeat/configuration-ssl#cipher-suites
- https://www.elastic.co/docs/reference/beats/filebeat/configuration-ssl#curve-types

I think it will be rarer to have those be a single value, probably supported protocols being only TLSv1.3 is the most likely to be seen in practice.

Comment (leehinman) [reply internal/pkg/otel/translate/output_elasticsearch_test.go:181]: Added supported_protocols and cipher_suites.

curve_types is going to be problamatic since the type isn't exported.

https://github.com/elastic/elastic-agent-libs/blob/bfea61ec0446e0b2f25adf53866d24998466c9d6/transport/tlscommon/config.go#L35

It also doesn't work with `WeaklyTypedInput`

Comment (cmacknz) [reply internal/pkg/otel/translate/output_elasticsearch_test.go:181]: We should probably just export the type then

Comment (leehinman) [reply internal/pkg/otel/translate/output_elasticsearch_test.go:181]: opened https://github.com/elastic/elastic-agent-libs/issues/377 and https://github.com/elastic/elastic-agent/issues/11776 so we don't forget
