### PR TITLE
Prefix BK metadata with fips indicator

### LINKED ISSUE #9033: [Flaky Test]: TestFIPS – Condition never satisfied
### Failing test case

TestFIPS

### Error message

Fleet Server's Elastic Agent should be healthy and FIPS-capable

### Build

https://buildkite.com/elastic/elastic-agent/builds/24155#0198130c-cad8-43ed-8f0b-f559192fee59/817-1133

### OS

Linux

### Stacktrace and notes

```markdown
=== Failed
=== FAIL: testing/integration/ess TestFIPS (20.65s)
    fips_test.go:65: statusUrl = https://61129ea44fe8f26e2a3317efb43acc8f.fleet.us-west2.gcp.elastic-cloud.com:443/api/status
    fips_test.go:95: body.Status = HEALTHY
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:147: FIPS: false, Status: online
    fips_test.go:65:
        	Error Trace:	/opt/buildkite-agent/builds/bk-agent-prod-aws-1752666585753281992/elastic/elastic-agent/testing/integration/ess/fips_test.go:99
        	            				/opt/buildkite-agent/builds/bk-agent-prod-aws-1752666585753281992/elastic/elastic-agent/testing/integration/ess/fips_test.go:65
        	Error:      	Condition never satisfied
        	Test:       	TestFIPS
        	Messages:   	Fleet Server's Elastic Agent should be healthy and FIPS-capable
```

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Prefix BK metadata with fips indicator

## Why is it important?

There are timing issues inbetween FIPS and non-FIPS ESS testing where FIPS tests can retrieve data for non-FIPS deployments.

## Related issues

- Closes #9033

### CODE REVIEW

**Comment by michel-laterman** [comment]
I think the attempt in the [earlier commit](https://buildkite.com/elastic/elastic-agent/builds/24224) and into the same issue; i've added some echo statements so we can be sure what we're referencing.

i'll run the tests a few times to see if it re-occurs

**Comment by michel-laterman** [comment]
buildkite test this

File: .buildkite/scripts/steps/integration_tests_tf.sh [hunk 1]
```diff
@@ -39,13 +39,19 @@ if [[ "${BUILDKITE_RETRY_COUNT}" -gt 0 || "${FORCE_ESS_CREATE:-false}" == "true"
...
+    JOB_ID=$(buildkite-agent meta-data get "ess.job")
+  fi
+  echo "Using JOB_ID: ${JOB_ID}"
+  export ELASTICSEARCH_HOST=$(buildkite-agent meta-data get "es.host" --job ${JOB_ID})
+  export ELASTICSEARCH_USERNAME=$(buildkite-agent meta-data get "es.username" --job ${JOB_ID})
+  export ELASTICSEARCH_PASSWORD=$(buildkite-agent meta-data get "es.pwd" --job ${JOB_ID})
+  export KIBANA_HOST=$(buildkite-agent meta-data get "kibana.host" --job ${JOB_ID})
+  export KIBANA_USERNAME=$(buildkite-agent meta-data get "kibana.username" --job ${JOB_ID})
+  export KIBANA_PASSWORD=$(buildkite-agent meta-data get "kibana.pwd" --job ${JOB_ID})
+  export INTEGRATIONS_SERVER_HOST=$(buildkite-agent meta-data get "integrations_server.host" --job ${JOB_ID})
```
Comment (pkoutsovasilis) [inline .buildkite/scripts/steps/integration_tests_tf.sh]: you need to do the same for the ps1 (windows powershell) script. Look [here](https://buildkite.com/elastic/elastic-agent/builds/24225#019819e2-60b3-4203-ac66-c3e44a978e67/140-330) and [here](https://buildkite.com/elastic/elastic-agent/builds/24225#019819e2-629e-45e0-b652-207ab09947a0/764-765). Evidently when you don't specify the job this is getting any it finds?!

please add a an echo to the ELASTICSEARCH_HOST also for in this file to be able to tell which ES each runner is using and from where 🙂

File: .buildkite/scripts/steps/integration_tests_tf.sh [hunk 2]
```diff
@@ -39,13 +39,19 @@ if [[ "${BUILDKITE_RETRY_COUNT}" -gt 0 || "${FORCE_ESS_CREATE:-false}" == "true"
...
   echo "~~~ Receiving ESS stack metadata"
-  export ELASTICSEARCH_HOST=$(buildkite-agent meta-data get "es.host")
-  export ELASTICSEARCH_USERNAME=$(buildkite-agent meta-data get "es.username")
-  export ELASTICSEARCH_PASSWORD=$(buildkite-agent meta-data get "es.pwd")
-  export KIBANA_HOST=$(buildkite-agent meta-data get "kibana.host")
-  export KIBANA_USERNAME=$(buildkite-agent meta-data get "kibana.username")
-  export KIBANA_PASSWORD=$(buildkite-agent meta-data get "kibana.pwd")
-  export INTEGRATIONS_SERVER_HOST=$(buildkite-agent meta-data get "integrations_server.host")
+  if [[ $BUILDKITE_STEP_KEY == "integration-fips-ess" ]]; then
+    JOB_ID=$(buildkite-agent meta-data get "ess.job.fips")
```
Comment (v1v) [inline .buildkite/scripts/steps/integration_tests_tf.sh]: Can we use `BUILDKITE_JOB_ID` instead of `JOB_ID`? Or is `BUILDKITE_JOB_ID` a built-in env variable?

**Review by v1v — COMMENTED** [review]
IIUC, this is related to the step at https://github.com/elastic/elastic-agent/blob/5ce48712326b996c0a7f78665fa60620e07babb8/.buildkite/bk.integration-fips.pipeline.yml#L21-L35 that creates a new deployment. Shall we simplify the current implementation and use the same [deployment](https://github.com/elastic/elastic-agent/blob/5ce48712326b996c0a7f78665fa60620e07babb8/.buildkite/bk.integration.pipeline.yml#L72-L90) regardless?

File: .buildkite/scripts/steps/integration_tests_tf.sh (hunk 2 above)
Comment (pkoutsovasilis) [reply .buildkite/scripts/steps/integration_tests_tf.sh]: yes @v1v I think that `BUILDKITE_JOB_ID` is already set by buildkite and is different per invocation, look at the env [here](https://buildkite.com/elastic/elastic-agent/builds/24230#01981a5d-cbfb-4418-b39c-a4c0a2afad5d) and [here](https://buildkite.com/elastic/elastic-agent/builds/24230#01981a5d-cbfe-4d09-93cd-1bfc290a85cf)

Comment (v1v) [reply .buildkite/scripts/steps/integration_tests_tf.sh]: Then I said nothing - it was about normalising it everywhere, but that's totally fine

Comment (pkoutsovasilis) [reply .buildkite/scripts/steps/integration_tests_tf.sh]: I agree 100% that what he have here is far from ideal, hopefully when could re-visit that approach with the migration to oblt-cli, wdyt?

**Comment by michel-laterman** [comment]
@v1v the deployment used by FIPS testing is different from the deployments used by normal integration tests, and custom ECH test. The difference is as follows:

* FIPS testing: deployed [integrations server](https://github.com/elastic/elastic-agent/blob/5ce48712326b996c0a7f78665fa60620e07babb8/.buildkite/bk.integration-fips.pipeline.yml#L25) is built from the FIPS variant of the commit
* standard integration testing: no special instructions
* custom ECH test: deployed [integrations server](https://github.com/elastic/elastic-agent/blob/5ce48712326b996c0a7f78665fa60620e07babb8/.buildkite/bk.integration.pipeline.yml#L53) is built from the commit

We needed to separate FIPS from non-FIPS as the binary differs.
We wanted to separate the test with a custom integration server from normal integration tests to isolate any issues (it would be easier to debug one test if the custom server fails, then it would be to find the issue if all tests fail)

File: .buildkite/scripts/steps/integration_tests_tf.sh (hunk 1 above)
Comment (michel-laterman) [reply .buildkite/scripts/steps/integration_tests_tf.sh]: done

File: .buildkite/scripts/steps/ess.ps1 [hunk 3]
```diff
@@ -101,20 +101,26 @@ function Get-Ess-Stack {
...
   )
-  
+
   if ($Env:BUILDKITE_RETRY_COUNT -gt 0) {
-      Write-Output "The step is retried, starting the ESS stack again"        
+      Write-Output "The step is retried, starting the ESS stack again"
       ess_up $StackVersion
       Write-Output "ESS stack is up. ES_HOST: $Env:ELASTICSEARCH_HOST"
   } else {
+      if ($Env:BUILDKITE_STEP_KEY -eq "integration-fips-ess") {
```
Comment (michel-laterman) [inline .buildkite/scripts/steps/ess.ps1]: I don't think we need this at the moment (we don't run windows tests in FIPS); but I think this is good to add now in case we need it in the future

**Review by v1v — APPROVED** [review]
LGTM, however I'll wait for a second review to play safe.

I can see builds are running those new steps:
- https://buildkite.com/elastic/elastic-agent/builds/24300#01982dfc-4224-4f77-a240-414a77a19dfd/196-197
- https://buildkite.com/elastic/elastic-agent/builds/24300#01982dfc-420c-4958-bea6-29316e6a8e5a/767-768

File: .buildkite/scripts/steps/ess.ps1 [hunk 4]
```diff
@@ -101,20 +101,24 @@ function Get-Ess-Stack {
...
   )
-  
+
   if ($Env:BUILDKITE_RETRY_COUNT -gt 0) {
-      Write-Output "The step is retried, starting the ESS stack again"        
+      Write-Output "The step is retried, starting the ESS stack again"
       ess_up $StackVersion
       Write-Output "ESS stack is up. ES_HOST: $Env:ELASTICSEARCH_HOST"
   } else {
+      # TODO: Use "ess.job.fips" if we need to build and test fips artifacts for Windows releases; Env:BUILDKITE_GROUP_KEY can be used to deterimine jpw tp set $job_id
```
Comment (v1v) [inline .buildkite/scripts/steps/ess.ps1]: what does `jpw tp` stand for?

File: .buildkite/scripts/steps/ess_start.sh [hunk 5]
```diff
@@ -12,10 +12,18 @@ ess_up $OVERRIDE_STACK_VERSION
...
-buildkite-agent meta-data set "es.host" $ELASTICSEARCH_HOST
-buildkite-agent meta-data set "es.username" $ELASTICSEARCH_USERNAME
-buildkite-agent meta-data set "es.pwd" $ELASTICSEARCH_PASSWORD
-buildkite-agent meta-data set "kibana.host" $KIBANA_HOST
-buildkite-agent meta-data set "kibana.username" $KIBANA_USERNAME
-buildkite-agent meta-data set "kibana.pwd" $KIBANA_PASSWORD
-buildkite-agent meta-data set "integrations_server.host" $INTEGRATIONS_SERVER_HOST
+echo "BUILDKITE_JOB_ID: ${BUILDKITE_JOB_ID}"
+
+if [[ $BUILDKITE_STEP_KEY == "integration-fips-ess" ]]; then
```
Comment (v1v) [inline .buildkite/scripts/steps/ess_start.sh]: I wonder, whether FIPS == true could be the way to do it here instead?

according to https://github.com/elastic/elastic-agent/blob/main/.buildkite/bk.integration-fips.pipeline.yml#L46 is the env variable used. however, it's important to take into account the  `set -euo pipefail` to avoid if FIPS is unset

File: .buildkite/scripts/steps/integration_tests_tf.sh [hunk 6]
```diff
@@ -39,13 +39,20 @@ if [[ "${BUILDKITE_RETRY_COUNT}" -gt 0 || "${FORCE_ESS_CREATE:-false}" == "true"
...
   # For the first run, we start the stack in the start_ess.sh step and it sets the meta-data
   echo "~~~ Receiving ESS stack metadata"
-  export ELASTICSEARCH_HOST=$(buildkite-agent meta-data get "es.host")
-  export ELASTICSEARCH_USERNAME=$(buildkite-agent meta-data get "es.username")
-  export ELASTICSEARCH_PASSWORD=$(buildkite-agent meta-data get "es.pwd")
-  export KIBANA_HOST=$(buildkite-agent meta-data get "kibana.host")
-  export KIBANA_USERNAME=$(buildkite-agent meta-data get "kibana.username")
-  export KIBANA_PASSWORD=$(buildkite-agent meta-data get "kibana.pwd")
-  export INTEGRATIONS_SERVER_HOST=$(buildkite-agent meta-data get "integrations_server.host")
+  if [[ $BUILDKITE_GROUP_KEY == "integration-tests-ubuntu-fips" ]]; then
```
Comment (v1v) [inline .buildkite/scripts/steps/integration_tests_tf.sh]: ditto

File: .buildkite/scripts/steps/integration_tests_tf.sh [hunk 7]
```diff
@@ -39,13 +39,20 @@ if [[ "${BUILDKITE_RETRY_COUNT}" -gt 0 || "${FORCE_ESS_CREATE:-false}" == "true"
...
+    JOB_ID=$(buildkite-agent meta-data get "ess.job.fips")
```
Comment (v1v) [inline .buildkite/scripts/steps/integration_tests_tf.sh]:
```suggestion
    JOB_ID=$(buildkite-agent meta-data get "ess.job.fips")
    echo "FIPS metadata has been retrieved"
```

File: .buildkite/scripts/steps/ess_start.sh [hunk 8]
```diff
@@ -12,10 +12,18 @@ ess_up $OVERRIDE_STACK_VERSION
...
+    buildkite-agent meta-data set "ess.job.fips" ${BUILDKITE_JOB_ID}
```
Comment (v1v) [inline .buildkite/scripts/steps/ess_start.sh]:
```suggestion
    buildkite-agent meta-data set "ess.job.fips" ${BUILDKITE_JOB_ID}
    echo "FIPS metadata has been set"
```

**Review by v1v — COMMENTED** [review]
I added a couple of comments

File: .buildkite/scripts/steps/ess_start.sh (hunk 5 above)
Comment (pkoutsovasilis) [reply .buildkite/scripts/steps/ess_start.sh]: I like that proposal 👍

File: .buildkite/scripts/steps/ess.ps1 (hunk 4 above)
Comment (michel-laterman) [reply .buildkite/scripts/steps/ess.ps1]: typo's for of the letter "o", i'll fix it 😛

**Comment by michel-laterman** [comment]
Looks like we still have some (fips) pipeline issues:
```
fatal: failed to get meta-data: POST https://agent.buildkite.com/v3/jobs/019837ed-bbfe-41d6-af65-7066b4df62f8/data/get: 404 Not Found: No key "ess.job.fips" found
```

Looks like a test runs before the FIPS provisioning is complete

File: .buildkite/scripts/steps/ess_start.sh [hunk 9]
```diff
@@ -12,10 +12,19 @@ ess_up $OVERRIDE_STACK_VERSION
...
+    buildkite-agent meta-data set "ess.job" ${BUILDKITE_JOB_ID}
+fi
+
+buildkite-agent meta-data set "es.host" $ELASTICSEARCH_HOST --job ${BUILDKITE_JOB_ID}
+buildkite-agent meta-data set "es.username" $ELASTICSEARCH_USERNAME --job ${BUILDKITE_JOB_ID}
+buildkite-agent meta-data set "es.pwd" $ELASTICSEARCH_PASSWORD --job ${BUILDKITE_JOB_ID}
+buildkite-agent meta-data set "kibana.host" $KIBANA_HOST --job ${BUILDKITE_JOB_ID}
+buildkite-agent meta-data set "kibana.username" $KIBANA_USERNAME --job ${BUILDKITE_JOB_ID}
+buildkite-agent meta-data set "kibana.pwd" $KIBANA_PASSWORD --job ${BUILDKITE_JOB_ID}
+buildkite-agent meta-data set "integrations_server.host" $INTEGRATIONS_SERVER_HOST --job ${BUILDKITE_JOB_ID}
```
Comment (pkoutsovasilis) [inline .buildkite/scripts/steps/ess_start.sh]: let's take an alternative route here, that is gonna be helpful I think 🙂 

```suggestion
METADATA_PREFIX=""
if [[ "${FIPS:-false}" == "true" ]]; then
  METADATA_PREFIX="fips."
  echo "Using FIPS metadata prefix: ${METADATA_PREFIX}"
fi

buildkite-agent meta-data set "${METADATA_PREFIX}es.host" $ELASTICSEARCH_HOST
buildkite-agent meta-data set "${METADATA_PREFIX}es.username" $ELASTICSEARCH_USERNAME
buildkite-agent meta-data set "${METADATA_PREFIX}es.pwd" $ELASTICSEARCH_PASSWORD
buildkite-agent meta-data set "${METADATA_PREFIX}kibana.host" $KIBANA_HOST
buildkite-agent meta-data set "${METADATA_PREFIX}kibana.username" $KIBANA_USERNAME
buildkite-agent meta-data set "${METADATA_PREFIX}kibana.pwd" $KIBANA_PASSWORD
buildkite-agent meta-data set "${METADATA_PREFIX}integrations_server.host" $INTEGRATIONS_SERVER_HOST
```

File: .buildkite/scripts/steps/integration_tests_tf.sh [hunk 10]
```diff
@@ -39,13 +39,21 @@ if [[ "${BUILDKITE_RETRY_COUNT}" -gt 0 || "${FORCE_ESS_CREATE:-false}" == "true"
...
+  fi
+  echo "Using JOB_ID: ${JOB_ID}"
+  export ELASTICSEARCH_HOST=$(buildkite-agent meta-data get "es.host" --job ${JOB_ID})
+  export ELASTICSEARCH_USERNAME=$(buildkite-agent meta-data get "es.username" --job ${JOB_ID})
+  export ELASTICSEARCH_PASSWORD=$(buildkite-agent meta-data get "es.pwd" --job ${JOB_ID})
+  export KIBANA_HOST=$(buildkite-agent meta-data get "kibana.host" --job ${JOB_ID})
+  export KIBANA_USERNAME=$(buildkite-agent meta-data get "kibana.username" --job ${JOB_ID})
+  export KIBANA_PASSWORD=$(buildkite-agent meta-data get "kibana.pwd" --job ${JOB_ID})
+  export INTEGRATIONS_SERVER_HOST=$(buildkite-agent meta-data get "integrations_server.host" --job ${JOB_ID})
+  echo "Elasticsearch Host: ${ELASTICSEARCH_HOST}"
```
Comment (pkoutsovasilis) [inline .buildkite/scripts/steps/integration_tests_tf.sh]: alignment with the alternative route proposed above
```suggestion
  METADATA_PREFIX=""
  if [[ "${FIPS:-false}" == "true" ]]; then
    METADATA_PREFIX="fips."
    echo "Using FIPS metadata prefix: ${METADATA_PREFIX}"
  fi
  echo "Using JOB_ID: ${JOB_ID}"
  export ELASTICSEARCH_HOST=$(buildkite-agent meta-data get "${METADATA_PREFIX}es.host")
  export ELASTICSEARCH_USERNAME=$(buildkite-agent meta-data get "${METADATA_PREFIX}es.username")
  export ELASTICSEARCH_PASSWORD=$(buildkite-agent meta-data get "${METADATA_PREFIX}es.pwd")
  export KIBANA_HOST=$(buildkite-agent meta-data get "${METADATA_PREFIX}kibana.host")
  export KIBANA_USERNAME=$(buildkite-agent meta-data get "${METADATA_PREFIX}kibana.username")
  export KIBANA_PASSWORD=$(buildkite-agent meta-data get "${METADATA_PREFIX}kibana.pwd")
  export INTEGRATIONS_SERVER_HOST=$(buildkite-agent meta-data get "${METADATA_PREFIX}integrations_server.host")
  echo "Elasticsearch Host: ${ELASTICSEARCH_HOST}"
```

File: .buildkite/scripts/steps/ess.ps1 [hunk 11]
```diff
@@ -101,20 +101,24 @@ function Get-Ess-Stack {
...
-      $Env:KIBANA_HOST = & buildkite-agent meta-data get "kibana.host"
-      $Env:KIBANA_USERNAME = & buildkite-agent meta-data get "kibana.username"
-      $Env:KIBANA_PASSWORD = & buildkite-agent meta-data get "kibana.pwd"
+      Write-Output "Using JOB ID: $job_id"
+      $Env:ELASTICSEARCH_HOST = & buildkite-agent meta-data get "es.host" --job "$job_id"
+      $Env:ELASTICSEARCH_USERNAME = & buildkite-agent meta-data get "es.username" --job "$job_id"
+      $Env:ELASTICSEARCH_PASSWORD = & buildkite-agent meta-data get "es.pwd" --job "$job_id"
+      $Env:KIBANA_HOST = & buildkite-agent meta-data get "kibana.host" --job "$job_id"
+      $Env:KIBANA_USERNAME = & buildkite-agent meta-data get "kibana.username" --job "$job_id"
+      $Env:KIBANA_PASSWORD = & buildkite-agent meta-data get "kibana.pwd" --job "$job_id"
```
Comment (pkoutsovasilis) [inline .buildkite/scripts/steps/ess.ps1]: if we go with the proposal below no change is needed here

**Review by pkoutsovasilis — COMMENTED** [review]
proposed a new approach, lemme know if it makes sense to you @michel-laterman

**Review by pkoutsovasilis — COMMENTED** [review]
@michel-laterman please add 

```
FIPS: "true"
``` 
here 
https://github.com/elastic/elastic-agent/blob/7b951783a00fe742312b2cf0417f0465cc75149c/.buildkite/bk.integration-fips.pipeline.yml#L20-L29

**Review by pkoutsovasilis — APPROVED** [review]
LGTM
