### PR TITLE
Fix agent stuck in upgrading state after manual rollback

### LINKED ISSUE #11534: Create integration test for Fleet managed manual rollback
After merging https://github.com/elastic/fleet-server/pull/5975 and https://github.com/elastic/elastic-agent/pull/11143 implement an integration test  where a manual rollback is triggered for a Fleet managed agent both within and without grace period.

As a rough guide, [TestStandaloneUpgradeManualRollback](https://github.com/elastic/elastic-agent/blob/cfa14fac0c9f57d63c1b483cbb27bdc612dc6b6c/testing/integration/ess/upgrade_rollback_test.go#L348) can be used with [what is being done to test fleet-managed automatic rollbacks](https://github.com/elastic/elastic-agent/blob/cfa14fac0c9f57d63c1b483cbb27bdc612dc6b6c/testing/integration/ess/upgrade_rollback_test.go#L295).

This cannot be done as part of https://github.com/elastic/elastic-agent/pull/11143 since fleet managed upgrades require valid signatures for the downloaded packages and there's no way to disable the verification when upgrading from Fleet (there's no equivalent to standalone upgrade `--skip-verify` switch and skipping verification in DEV builds has been removed a long time ago)

### LINKED ISSUE #12910: [Fleet]: On rolling back windows agent shows “Upgrade Failed” banner instead of "upgrade rolled back" and remain stuck in upgrading state.
**Kibana version:**
```
VERSION: 9.3.1 BC2
BUILD: 95692
COMMIT: fc8541f410eb2093fb31383e9308f6159452f09f

VERSION: 9.4.0 SNAPSHOT
BUILD: 97528
COMMIT: bdba8dc7f7ce1c391efc794a96d9118ea03b4e3c

```

**Preconditions:**

1. A 9.4.0 SNAPSHOT Kibana cloud environment is available.
2. 9.3.0 Windows agents should be installed.
3. Agents should be upgraded to 9.4.0.

**Steps to reproduce:**

1. Navigate to Assets > Agent Tab.
2. Select the windows agent.
3. Click on action button > Upgrade Management > Roll back agent.
4. Wait for 5 min
5. Observe that 
    - On rollback agent, “Upgrade failed” banner is display instead of “rolled back” banner.
    - After rollback , Agent remains stuck in the “Upgrading” state.

**Note:** This issue is also reproducible on 9.3.1 BC2 build.

**Whats Working Fine:**
-  This issue is working fine with Linux and Mac agent.

**Expected behavior:**
- On rolling back a Windows agent, the UI should display an “Upgrade rolled back” banner.
- Agent should exit the upgrade flow and should not remain stuck in the “Upgrading” state.

**Screenshot:**
- 9.4.0 SNAPSHOT

Image
Image

- 9.3.1 BC2
Image
Image

**Screencast**

https://github.com/user-attachments/assets/7c1b5c3e-3f75-4ef9-afdd-e5a3a4196a59

**Linked Feature ticket:**
https://github.com/elastic/ingest-dev/issues/3971

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Detect rollbacks earlier in `Coordinator.Upgrade` — before any state changes by checking whether the rollback targets the version already running. The action is acked immediately and no upgrade processing occurs. The previous late-stage ErrNoRollbacksAvailable fallback is removed as it is no longer reachable. This results in the next checkin being sent without any upgrade details signalling a successful rollback.

Also adds a Fleet-managed integration test (TestFleetManagedUpgradeRollback) that runs on all OSes, verifying the agent stays healthy and Fleet reflects the correct status after both a rollback and a replayed rollback.

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>
## Why is it important?

After a manual rollback, the rolled-back agent restarts with a stale ackToken, causing Fleet Server to re-send the same rollback action. Previously, the replayed action was detected only after the coordinator had already set the upgrading state and invoked the upgrade manager, which returned ErrNoRollbacksAvailable. The late fallback handler could not fully undo the side effects, leaving the agent stuck in "Upgrade failed" state.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- [x] I have added an integration test or an E2E test

## Disruptive User Impact

None. This change only adds a no-op short-circuit for an action that was already completed. The agent behavior for all other upgrade/rollback paths is unchanged.

## How to test this PR locally

Enroll an agent built from this PR, force it to upgrade to the latest snapshot or a previous minor release in fleet. Use the roll-back action in fleet to restore to the initial version.

## Related issues

- Closes https://github.com/elastic/elastic-agent/issues/12910
- Closes #11534

### CODE REVIEW

File: pkg/testing/tools/fleettools/fleet.go [hunk 1]
```diff
@@ -61,6 +63,23 @@ func UpgradeAgent(ctx context.Context, client *kibana.Client, agentID, version s
 	return nil
 }
 
+// RollbackAgent requests a rollback for the given agent via the Fleet API.
+// TODO: Replace with a dedicated method once elastic-agent-libs supports
+// the rollback endpoint (POST /api/fleet/agents/{agentId}/rollback).
```
Comment (ycombinator) [inline pkg/testing/tools/fleettools/fleet.go]: Do we have an issue or PR for this change?

File: testing/integration/ess/upgrade_rollback_test.go [hunk 2]
```diff
@@ -418,6 +557,68 @@ func TestStandaloneUpgradeManualRollback(t *testing.T) {
 
 }
 
+// TestStandaloneUpgradeReplayedRollback is a regression test for
+// https://github.com/elastic/elastic-agent/issues/12910.
+// After a successful manual rollback, we trigger a rollback twice
```
Comment (ycombinator) [inline testing/integration/ess/upgrade_rollback_test.go]:
```suggestion
// After a successful manual rollback, we trigger a rollback a second time
```

File: pkg/testing/tools/fleettools/fleet.go (hunk 1 above)
Comment (michel-laterman) [reply pkg/testing/tools/fleettools/fleet.go]: https://github.com/elastic/elastic-agent-libs/pull/399

File: internal/pkg/agent/application/coordinator/coordinator.go [hunk 3]
```diff
@@ -882,22 +906,6 @@ func (c *Coordinator) Upgrade(ctx context.Context, version string, sourceURI str
...
-			// was received by the "upgraded" elastic-agent.
-			// This block here is to avoid setting an error state because the rollback requested no longer exist after
-			// having performed the rollback once.
-			// A better test would be to compare actionIDs but there's no way to persist the actionID of the rollback action
-			// from the upgraded agent to the rolled back agent (upgrade details is reset when the upgrade marker is deleted)
-			c.logger.Infow(
-				"Received a rollback action with the same version as current and no rollbacks available, ignoring the likely replayed action",
-				"action_id", action.ID())
-			c.ClearOverrideState()
-			det.SetState(details.StateRollback)
```
Comment (cmacknz) [inline internal/pkg/agent/application/coordinator/coordinator.go:897]: IIRC Fleet wants the agent to stay in the rolled back state in this case, is this what happens?

File: pkg/testing/tools/fleettools/fleet.go (hunk 1 above)
Comment (ycombinator) [reply pkg/testing/tools/fleettools/fleet.go]: Consider mentioning this in the inline comment so someone looking at this code in the future could clean it up once https://github.com/elastic/elastic-agent-libs/pull/399 is merged.  Unless you plan to do it right away yourself.

Comment (michel-laterman) [reply pkg/testing/tools/fleettools/fleet.go]: added

**Review by ycombinator — APPROVED** [review]
