### PR TITLE
Fix logging of service based components (aka. endpoint)

### LINKED ISSUE #1939: [Fleet]: 'elastic_agent.endpoint_security' option is not shown on the 'Dataset' dropdown on Logs page
**Kibana version:** 8.6 Kibana Cloud environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.6.0 BC6
Build: 58740
Commit: f329a77595950244361736dff7208a810299fd69
```

**Preconditions:**

- 8.6 Kibana Cloud environment should be available.
- Agent Policies should be created.
- Endpoint integration should be added to the Agent policies.
- Agents should be installed.

**Steps to reproduce:**

1. Navigate to `Fleet > Agents tab`.
2. Click on the `Agent`.
3. Click on `Logs` tab.
4. Click on `Datasets` tab.
5. `Datasets` dropdown  is shown.
6. Observe that `elastic_agent.endpoint_security` option is not shown on the `Datasets` dropdown on `Logs` tab for `all OSs`.

**Expected Result:**

- `elastic_agent.endpoint_security` option should be shown on the `Datasets` dropdown on `Logs` tab for `all OSs`.

**Screen Recording:**

https://user-images.githubusercontent.com/97870262/206986415-a6e13e3f-a3d9-4ee0-84a4-e3bd246d2910.mp4

**Agent Logs:**

- **Windows:**

[elastic-agent-diagnostics-2022-12-12T08-06-28Z-00.zip](https://github.com/elastic/kibana/files/10205876/elastic-agent-diagnostics-2022-12-12T08-06-28Z-00.zip)

- **Linux:**

[elastic-agent-diagnostics-2022-12-12T07-57-41Z-00.zip](https://github.com/elastic/kibana/files/10205878/elastic-agent-diagnostics-2022-12-12T07-57-41Z-00.zip)

- **Mac**

[elastic-agent-diagnostics-2022-12-12T08-11-38Z-00.zip](https://github.com/elastic/kibana/files/10205916/elastic-agent-diagnostics-2022-12-12T08-11-38Z-00.zip)

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

This adds to the filestream monitor so it can gather log files from any service based component that defined a log path to be used in its specification.

## Why is it important?

This fixes the issue where 8.6 was not shipping log information for Endpoint Security.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #1939

### CODE REVIEW

**Comment by blakerouse** [comment]
`TestActionDispatcher/Cancel_queued_action` seems flaky.

File: internal/pkg/agent/application/monitoring/v1_monitor.go [hunk 1]
```diff
@@ -14,6 +14,8 @@ import (
 	"strings"
 	"unicode"
 
+	"github.com/elastic/elastic-agent/pkg/component"
+
```
Comment (belimawr) [inline internal/pkg/agent/application/monitoring/v1_monitor.go:18]: nit:
```suggestion
```

**Review by belimawr — APPROVED** [review]
