### PR TITLE
Properly check if and error matches a windows/syscall error

### LINKED ISSUE #3316: Flaky test: TestRemovePath, error is not considered retriable
## Flaky Test

* **Test Name:** internal/pkg/agent/install TestRemovePath

* **Link:** [uninstall_windows_test.go](https://github.com/elastic/elastic-agent/blob/0f3229248d82145a49005204ebff2d8a1cb864fc/internal/pkg/agent/install/uninstall_windows_test.go#L31)

* **Branch:** 
 - main
 - others

* **Artifact Link:** 
  - [Jenkins](https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/main/1298/pipeline/2133/)

* **Notes:** 
 - the issue seems to be on how the error is considered retriable 
 - this failure happened on Windows 8

### Stack Trace

```
=== RUN   TestRemovePath
    uninstall_windows_test.go:54: 
        	Error Trace:	C:/Users/jenkins/workspace/tic-agent_elastic-agent-mbp_main/src/github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall_windows_test.go:54
        	Error:      	Received unexpected error:
        	            	could not remove "C:\\Users\\jenkins\\AppData\\Local\\Temp\\TestRemovePath2573796789\\001\\subdir", unretriable error: failed to open handle for "C:\\Users\\jenkins\\AppData\\Local\\Temp\\TestRemovePath2573796789\\001\\subdir\\main.exe": The process cannot access the file because it is being used by another process.
        	Test:       	TestRemovePath
--- FAIL: TestRemovePath (0.62s)
```

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Properly check if and error matches a windows/syscall error

## Why is it important?

RemovePath is failing as it considers the error not retriable when it actually is.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- ~~[ ] I have added an integration test or an E2E test~~

## Related issues

- Closes #3316 

## Questions to ask yourself

- How are we going to support this in production? 
- How are we going to measure its adoption? 
- How are we going to debug this?
- What are the metrics I should take care of?
- ...

### CODE REVIEW

File: internal/pkg/agent/install/uninstall_windows.go [hunk 1]
```diff
@@ -20,22 +20,27 @@ func isBlockingOnExe(err error) bool {
 	if err == nil {
 		return false
 	}
-	path, errno := getPathFromError(err)
```
Comment (cmacknz) [inline internal/pkg/agent/install/uninstall_windows.go:23]: Where did this call go?

Comment (AndersonQ) [reply internal/pkg/agent/install/uninstall_windows.go:23]: away - uahuahuahua (sorry I could not resist the joke)

Why it went away:
I don't see any evidence the fact the error does not have a path on it prevents it from being one of the retriable error. Besides the path isn't used at all here, so I don't see the relevance of this check. `err == syscall.ERROR_ACCESS_DENIED` seems to be the only thing relevant to determine if the error `isBlockingOnExe`.

Comment (cmacknz) [reply internal/pkg/agent/install/uninstall_windows.go:23]: Looking at the way this gets used, the error needs to have a path for the special case for removing a blocking exe to work. The call is unnecessary in the overall logic chain since it gets called again later, but if the error doesn't have a path the work around for it can't work.

Comment (cmacknz) [reply internal/pkg/agent/install/uninstall_windows.go:23]: I wonder if SHARING_VIOLATION was just forgotten here.

Comment (AndersonQ) [reply internal/pkg/agent/install/uninstall_windows.go:23]: > I wonder if SHARING_VIOLATION was just forgotten here.
me too.

However the error in the test doe not come from `isBlockingOnExe`, but from `isRetryableError`. So that might be only checking for `syscall.ERROR_ACCESS_DENIED` intentionally.

>Looking at the way this gets used, the error needs to have a path for the special case for removing a blocking exe to work. The call is unnecessary in the overall logic chain since it gets called again later, but if the error doesn't have a path the work around for it can't work.

yes, but it's another case and there it still checks for the path not being empty.

Comment (cmacknz) [reply internal/pkg/agent/install/uninstall_windows.go:23]: Reading the original PR https://github.com/elastic/elastic-agent/pull/3120 the implemetation was adapted from https://github.com/golang/go/blob/master/src/testing/testing.go#L1257 which does the same.

> yes, but it's another case and there it still checks for the path not being empty.

If we get rid of the path check here, this function is no longer answering the question "is this an error from blocking waiting on an exe" it is just "is this an access denied error" which is mislead. Just because the code happens to be written today so that this doesn't matter, doesn't mean that will stay true in the future.

You could rename the function to something like `possiblyBlockingOnExe` to indicate that the error here might not have anything to do with an executable file. There are a lots of other reasons to get an access is denied error.

Comment (AndersonQ) [reply internal/pkg/agent/install/uninstall_windows.go:23]: Well either way it does not answer _"is this an error from blocking waiting on an exe"_ as it did not do any check on the path, not even if it was from an exe file.
Also the Go implementation does not check the path. I'm happy to rename it, but unless there is a proper check on the path, I don't believe to be worth checking it

**Review by cmacknz — APPROVED** [review]
Thanks, at least the function name matches what it actually checks now.

**Comment by cmacknz** [comment]
No new test failures, merging.
