### PR TITLE
Report crashing OTEL process cleanly with proper status reporting

### LINKED ISSUE #11173: [beats receivers] Supervised collector failing to start only reports OTel manager failed: supervised collector (pid: 94473) exited with error: exit status 1'
- Relates https://github.com/elastic/elastic-agent/issues/11171
- Relates https://github.com/elastic/elastic-agent/issues/11172

When the supervised OTel collector fails to start, the overall agent status is set to `OTel manager failed: supervised collector (pid: 94473) exited with error: exit status 1` with no other details. To determine the root cause of the failure you must read the logs.

This is a regression from the existing health reporting experience where the message in the agent status tells you specifically what is wrong and with what component.

Ideally we can have a way to put the actual error causing the problem in the message instead of forcing us and users to read through the agent logs each time. In 9.2.1 in particular where Beat receivers is used for monitoring, when a failure like this happens there will be no agent logs in Fleet to debug and the only way to diagnose the problem is via diagnostics or looking at agent logs on the host.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

At the moment when a spawned OTEL subprocess fails it is just reported as exit code 1. It provides no information of what has failed and marks the entire Elastic Agent as failed.

This changes that behavior by looking at the actual output to determine the issue and report a proper component status for the entire configuration. It does this by parsing the configuration and building its own aggregated status for the component graph that would be returned by the healthcheckv2 extension if it could successfully run. It inspects the error message to determine if it can correlate the error to a specific component in the graph. If it cannot it falls back to reporting error on all components.

## Why is it important?

The Elastic Agent needs to provide clean status reporting even when the subprocess fails to run. It needs to not mark the entire Elastic Agent in error when that happens as well.

## Checklist

- [x] I have read and understood the [pull request guidelines](https://github.com/elastic/elastic-agent/blob/main/CONTRIBUTING.md#pull-request-guidelines) of this project.
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)
- ~~[ ] I have added an integration test or an E2E test~~(covered by unit tests)

## Disruptive User Impact

None

## How to test this PR locally

Use either an invalid OTEL configuration or one that will fail to start. Observer that when running `elastic-agent run` with that OTEL configuration in the `elastic-agent.yml` filed (aka. Hybrid Mode) that `elastic-agent status --output=full` provides correct state information.

## Related issues

- Closes #11173

### CODE REVIEW

File: internal/pkg/otel/manager/testing/testing.go [hunk 1]
```diff
@@ -50,6 +51,7 @@ func main() {
 	exitCode := 0
 	err = cmd.RunCollector(ctx, nil, true, "debug", monitoringURL)
 	if err != nil && !errors.Is(err, context.Canceled) {
+		fmt.Fprintln(os.Stderr, err)
```
Comment (swiatekm) [inline internal/pkg/otel/manager/testing/testing.go]: FYI, if you use otelcol builder, its generated `main.go` [uses](https://github.com/open-telemetry/opentelemetry-collector/blob/73f090cd0d59a3faa237168750d44a0036d8fd5c/cmd/otelcorecol/main.go#L58C3-L58C66) `log.Fatalf` here. We should do the same if we can.

File: internal/pkg/otel/manager/common.go [hunk 2]
```diff
@@ -80,3 +86,124 @@ func findRandomTCPPorts(count int) (ports []int, err error) {
...
+
+	// track connectors
+	connectors := make(map[component.ID]struct{})
+	connectorsAsReceiver := make(map[component.ID][]pipeline.ID)
+	connectorsAsExporter := make(map[component.ID][]pipeline.ID)
+
+	// pipelines
+	for pipelineID, pipelineCfg := range c.Service.Pipelines {
+		for _, recvID := range pipelineCfg.Receivers {
+			instanceID := componentstatus.NewInstanceID(recvID, component.KindReceiver, pipelineID)
```
Comment (swiatekm) [inline internal/pkg/otel/manager/common.go:135]: I think it's worth commenting that the upstream graph building code creates a single instance id for each receiver, containing information about all the pipelines it appears in. The status reporting then makes a copy of the status for each pipeline, so it's fine for us to do so here as well, but it's worth calling out imo.

File: internal/pkg/otel/manager/common.go [hunk 3]
```diff
@@ -80,3 +86,124 @@ func findRandomTCPPorts(count int) (ports []int, err error) {
...
+		return aggStatus, nil
+	}
+	// no match found so generic failed on all instances
+	aggStatus, _ := aggGeneric.AggregateStatus(status.ScopeAll, status.Verbose)
+	return aggStatus, nil
+}
+
+func recordSpecificErr(agg *status.Aggregator, instanceID *componentstatus.InstanceID, err error, extraMatchStrs ...string) bool {
+	forIDStr := fmt.Sprintf("for id: %q", instanceID.ComponentID().String())
+	failedMatchStr := fmt.Sprintf("failed to start %q %s:", instanceID.ComponentID().String(), strings.ToLower(instanceID.Kind().String()))
```
Comment (swiatekm) [inline internal/pkg/otel/manager/common.go:197]: It'd be good to specify what conditions these lines refer to. The one about starting the component is relatively obvious, but `forIDStr`, not so much. Is this an error about the otel collector not knowing about the component type?

File: internal/pkg/otel/manager/manager.go [hunk 4]
```diff
@@ -555,6 +562,25 @@ func (m *OTelManager) handleOtelStatusUpdate(otelStatus *status.AggregateStatus)
 	return m.processComponentStates(componentStates), nil
 }
 
+// reportStartupErr maps this error to the *status.AggregateStatus.
+// this is done by parsing the `m.mergedCollectorCfg` and converting it into the best effort *status.AggregateStatus.
+func (m *OTelManager) reportStartupErr(ctx context.Context, err error) {
```
Comment (swiatekm) [inline internal/pkg/otel/manager/manager.go:569]: One thing I don't like about this function, is that it pretends to report an error, but actually reports a status. We have different delivery requirements for these. Reporting errors is non-blocking, as a newer error can always overwrite an older error. The same is not true about statuses - we need to make sure all the component statuses are delivered, or else we get bugs like the one in https://github.com/elastic/elastic-agent/pull/10675.

As a result, `reportStartupErr` needs to be called with care, as it can potentially deadlock the manager. I wonder if we should bite the bullet and just make the update channel buffered with some reasonable size, and emit a fatal error if it can't be written to. What do you think?

**Review by swiatekm — COMMENTED** [review]
The logic looks good to me, but I have some concerns about deadlocks in the otel manager caused by trying to report status from the main loop.

File: internal/pkg/otel/manager/common.go [hunk 5]
```diff
@@ -80,3 +86,124 @@ func findRandomTCPPorts(count int) (ports []int, err error) {
 
 	return ports, err
 }
+
+// otelConfigToStatus converts the `cfg` to `status.AggregateStatus` using the reported error.
+//
+// The flow of this function comes from https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/graph/graph.go
+// It's a much simpler version, but follows the same for loop ordering and building of connectors of the internal
+// graph system that OTEL uses to build its component graph.
+func otelConfigToStatus(cfg *confmap.Conf, err error) (*status.AggregateStatus, error) {
```
Comment (cmacknz) [inline internal/pkg/otel/manager/common.go:95]: This is complex enough to have its own tests. The configurations in manager_test.go right now don't cover it all e.g. there are no configurations with connectors.

To me it seems like tests for this should focus on mapping status for complex configurations and the tests in manager_test.go can focus purely on ensuring various failure scenarios result in capturing a status regardless of what the configuration is.

File: internal/pkg/otel/manager/testing/testing.go (hunk 1 above)
Comment (blakerouse) [reply internal/pkg/otel/manager/testing/testing.go]: I updated to `logp` because our `logp` package when sets up it redirects `log.` to devnull. This makes it similar and actually writes. This took a bit to track down, I made this simple change and nothing was working (that was fun).

File: internal/pkg/otel/manager/common.go (hunk 5 above)
Comment (blakerouse) [reply internal/pkg/otel/manager/common.go:95]: I added full coverage over this function, and just simplified the test in manager_test.go to just verify it is used in 1 case.

File: internal/pkg/otel/manager/common.go (hunk 2 above)
Comment (blakerouse) [reply internal/pkg/otel/manager/common.go:135]: I added the comment.

File: internal/pkg/otel/manager/common.go (hunk 3 above)
Comment (blakerouse) [reply internal/pkg/otel/manager/common.go:197]: I added comments for the checks.

File: internal/pkg/otel/manager/manager.go (hunk 4 above)
Comment (blakerouse) [reply internal/pkg/otel/manager/manager.go:569]: I agree it is safer. I updated it to have a buffer channel of 5, I think that is rather lower and would ensure no case of blocking.

**Comment by blakerouse** [comment]
@cmacknz @swiatekm Thanks for the reviews. I have updated this PR to resolve all your comments.

**Review by swiatekm — DISMISSED** [review]
👍

File: internal/pkg/otel/manager/manager_test.go [hunk 6]
```diff
@@ -1387,12 +1506,14 @@ func TestOTelManagerEndToEnd(t *testing.T) {
...
-		collectorStatusCh:          make(chan *status.AggregateStatus, 1),
-		componentStateCh:           make(chan []runtime.ComponentComponentState),
+		logger:            testLogger,
+		baseLogger:        testLogger,
+		errCh:             make(chan error, 1), // holds at most one error
+		updateCh:          make(chan configUpdate, 1),
+		collectorStatusCh: make(chan *status.AggregateStatus, 1),
+		// componentStateCh uses a buffer channel to ensure that no state transitions are missed and to prevent
+		// any possible case of deadlock, 5 is used just to give a small buffer.
+		componentStateCh:           make(chan []runtime.ComponentComponentState, 5),
```
Comment (swiatekm) [inline internal/pkg/otel/manager/manager_test.go:1514]: Shouldn't this go in the manager constructor?

**Comment by cmacknz** [comment]
Still see the healthcheck extension get output when there is a failure which I don't think we should do:

```
❯ sudo elastic-development-agent status
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (DEGRADED) 1 or more components/units in a failed state
   ├─ beat/metrics-monitoring
   │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  ├─ beat/metrics-monitoring
   │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  └─ beat/metrics-monitoring-metrics-monitoring-beats
   │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   ├─ filestream-monitoring
   │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  ├─ filestream-monitoring
   │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  └─ filestream-monitoring-filestream-monitoring-agent
   │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   ├─ http/metrics-monitoring
   │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  ├─ http/metrics-monitoring
   │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  └─ http/metrics-monitoring-metrics-monitoring-agent
   │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   ├─ prometheus/metrics-monitoring
   │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  ├─ prometheus/metrics-monitoring
   │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   │  └─ prometheus/metrics-monitoring-metrics-monitoring-collector
   │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
   └─ extensions
      ├─ status: StatusFatalError ['' has invalid keys: not_a_setting]
      └─ extension:healthcheckv2/04d1d7a2-5a25-4834-bf8d-cd715d1d80a5
         └─ status: StatusFatalError ['' has invalid keys: not_a_setting]
~/Downloads/builds/elastic-agent-9.3.0-SNAPSHOT-darwin-aarch64 ······································ 02:01:06 PM
❯ sudo elastic-development-agent version
Binary: 9.3.0-SNAPSHOT (build: af48211496d454f5f68c57e5ff8b7228056128e2 at 2025-12-09 18:58:25 +0000 UTC)
Daemon: 9.3.0-SNAPSHOT (build: af48211496d454f5f68c57e5ff8b7228056128e2 at 2025-12-09 18:58:25 +0000 UTC)
```

File: internal/pkg/otel/manager/manager_test.go (hunk 6 above)
Comment (blakerouse) [reply internal/pkg/otel/manager/manager_test.go:1514]: You are correct. I am crazy. I have also added this to the manager.go

**Review by swiatekm — APPROVED** [review]

**Comment by blakerouse** [comment]
> Still see the healthcheck extension get output when there is a failure which I don't think we should do:
> 
> ```
> ❯ sudo elastic-development-agent status
> ┌─ fleet
> │  └─ status: (STOPPED) Not enrolled into Fleet
> └─ elastic-agent
>    ├─ status: (DEGRADED) 1 or more components/units in a failed state
>    ├─ beat/metrics-monitoring
>    │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  ├─ beat/metrics-monitoring
>    │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  └─ beat/metrics-monitoring-metrics-monitoring-beats
>    │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    ├─ filestream-monitoring
>    │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  ├─ filestream-monitoring
>    │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  └─ filestream-monitoring-filestream-monitoring-agent
>    │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    ├─ http/metrics-monitoring
>    │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  ├─ http/metrics-monitoring
>    │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  └─ http/metrics-monitoring-metrics-monitoring-agent
>    │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    ├─ prometheus/metrics-monitoring
>    │  ├─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  ├─ prometheus/metrics-monitoring
>    │  │  └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    │  └─ prometheus/metrics-monitoring-metrics-monitoring-collector
>    │     └─ status: (FAILED) Fatal: '' has invalid keys: not_a_setting
>    └─ extensions
>       ├─ status: StatusFatalError ['' has invalid keys: not_a_setting]
>       └─ extension:healthcheckv2/04d1d7a2-5a25-4834-bf8d-cd715d1d80a5
>          └─ status: StatusFatalError ['' has invalid keys: not_a_setting]
> ~/Downloads/builds/elastic-agent-9.3.0-SNAPSHOT-darwin-aarch64 ······································ 02:01:06 PM
> ❯ sudo elastic-development-agent version
> Binary: 9.3.0-SNAPSHOT (build: af48211496d454f5f68c57e5ff8b7228056128e2 at 2025-12-09 18:58:25 +0000 UTC)
> Daemon: 9.3.0-SNAPSHOT (build: af48211496d454f5f68c57e5ff8b7228056128e2 at 2025-12-09 18:58:25 +0000 UTC)
> ```

Lets file that as a separate issue, because that exists even before this PR.

**Comment by blakerouse** [comment]
Filed an issue for hiding the extension https://github.com/elastic/elastic-agent/issues/11714
