### PR TITLE
Refactor and fix all upgrade integration tests

### LINKED ISSUE #3155: TestStandaloneUpgradeRetryDownload is failing regularly on main
## Flaky Test

* **Test Name:** TestStandaloneUpgradeRetryDownload
* **Link:** https://github.com/cmacknz/elastic-agent/blob/0158f7755cd411443587211b3afa89215b7fd201/testing/integration/upgrade_test.go#L315-L318
* **Branch:** main
* **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/2160#0189acba-5002-471d-99e3-b759b8733356
* **Notes:** First noticed in https://github.com/elastic/elastic-agent/pull/3153

### Stack Trace

```
=== RUN   TestStandaloneUpgradeRetryDownload
    upgrade_test.go:384: Testing Elastic Agent upgrade from 8.10.0-SNAPSHOT to 8.8.0...
    fetcher.go:90: Using existing artifact elastic-agent-8.10.0-SNAPSHOT-linux-arm64.tar.gz
    fixture.go:200: Extracting artifact elastic-agent-8.10.0-SNAPSHOT-linux-arm64.tar.gz to /tmp/TestStandaloneUpgradeRetryDownload2438491427/001
    fixture.go:213: Completed extraction of artifact elastic-agent-8.10.0-SNAPSHOT-linux-arm64.tar.gz to /tmp/TestStandaloneUpgradeRetryDownload2438491427/001
    fixture.go:511: Components were not modified from the fetched artifact
    upgrade_test.go:398: Install the built Agent
    fixture.go:344: >> running agent with: [/tmp/TestStandaloneUpgradeRetryDownload2438491427/001/elastic-agent-8.10.0-SNAPSHOT-linux-arm64/elastic-agent install --force --non-interactive]
    upgrade_test.go:400: Installing in non-interactive mode.Elastic Agent has been successfully installed.
        
    upgrade_test.go:403: Ensure the correct version is running
    fixture.go:344: >> running agent with: [/opt/Elastic/Agent/elastic-agent version --yaml]
    upgrade_test.go:502: binary:
          version: 8.10.0
          commit: 0158f7755cd411443587211b3afa89215b7fd201
          build_time: 2023-07-31T13:54:35Z
          snapshot: true
        could not get version. failed to communicate with running daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/elastic-agent.sock: connect: no such file or directory"
        Use --binary-only flag to skip trying to retrieve version from running daemon
        
    fixture.go:344: >> running agent with: [/opt/Elastic/Agent/elastic-agent version --yaml]
    upgrade_test.go:407: Modify /etc/hosts to simulate transient network error
    upgrade_test.go:413: /etc/hosts modify command:  /usr/bin/sed -i.bak s/localhost/localhost artifacts.elastic.co artifacts-api.elastic.co/g /etc/hosts
    upgrade_test.go:427: Check /etc/hosts command:  /usr/bin/grep artifacts /etc/hosts
    upgrade_test.go:440: Start the Agent upgrade
    upgrade_test.go:452: Check Agent logs for at least two retry messages
    fixture.go:344: >> running agent with: [/opt/Elastic/Agent/elastic-agent upgrade 8.8.0]
    upgrade_test.go:462: Find logs command:  /usr/bin/grep download.*retrying --recursive --include *.ndjson /opt/Elastic/Agent/data/elastic-agent-0158f7/logs
    upgrade_test.go:471: [/opt/Elastic/Agent/data/elastic-agent-0158f7/logs/elastic-agent-20230731.ndjson:{"log.level":"warn","@timestamp":"2023-07-31T14:19:58.041Z","log.origin":{"file.name":"upgrade/step_download.go","file.line":184},"message":"unable to download package: 2 errors occurred:\n\t* package '/opt/Elastic/Agent/data/elastic-agent-0158f7/downloads/elastic-agent-8.8.0-linux-arm64.tar.gz' not found: open /opt/Elastic/Agent/data/elastic-agent-0158f7/downloads/elastic-agent-8.8.0-linux-arm64.tar.gz: no such file or directory\n\t* fetching package failed: Get \"https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.8.0-linux-arm64.tar.gz\": dial tcp [::1]:443: connect: connection refused\n\n; retrying (will be retry 1) in 17.831015822s.","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"} /opt/Elastic/Agent/data/elastic-agent-0158f7/logs/elastic-agent-20230731.ndjson:{"log.level":"warn","@timestamp":"2023-07-31T14:20:15.874Z","log.origin":{"file.name":"upgrade/step_download.go","file.line":184},"message":"unable to download package: 2 errors occurred:\n\t* package '/opt/Elastic/Agent/data/elastic-agent-0158f7/downloads/elastic-agent-8.8.0-linux-arm64.tar.gz' not found: open /opt/Elastic/Agent/data/elastic-agent-0158f7/downloads/elastic-agent-8.8.0-linux-arm64.tar.gz: no such file or directory\n\t* fetching package failed: Get \"https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.8.0-linux-arm64.tar.gz\": dial tcp 127.0.0.1:443: connect: connection refused\n\n; retrying (will be retry 2) in 38.104452751s.","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}]
    upgrade_test.go:472: Number of retry messages:  2
    upgrade_test.go:476: Restore /etc/hosts so upgrade can proceed
    upgrade_test.go:481: Waiting for upgrade to finish
    upgrade_test.go:484: Waiting for upgrade watcher to finish running...
    upgrade_test.go:484: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_test.go:315
        	            				/home/ubuntu/agent/testing/integration/upgrade_test.go:484
        	Error:      	Condition never satisfied
        	Test:       	TestStandaloneUpgradeRetryDownload
        	Messages:   	agent never removed update marker
    fixture.go:344: >> running agent with: [/opt/Elastic/Agent/elastic-agent uninstall --force]
--- FAIL: TestStandaloneUpgradeRetryDownload (340.32s)```

### LINKED ISSUE #3461: Integration tests are not upgrading to the actual build being tested
I have been digging into why tests are still failing to install on Windows. While I did lots of manual testing of PR https://github.com/elastic/elastic-agent/pull/3384 confirming that it was indeed stopping and killing the watcher, I was shocked to find similar issues still occurring on Windows with my windows integration runner.

After spending too much time thinking that it could be the code to find the watcher, and too much time pausing the tests and inspecting running processes I identified the issue.

The issue is that some tests are not even upgrading to the build of the Elastic Agent that is under test. It is instead upgrading to the SNAPSHOT build from the artifacts. This can be seen clearly here:

### TestStandaloneUpgrade/Upgrade_7.17.13_to_8.11.0-SNAPSHOT

```
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): === FAIL: testing/integration TestStandaloneUpgrade/Upgrade_7.17.13_to_8.11.0-SNAPSHOT (68.48s)
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:176: Downloading artifact from https://staging.elastic.co/7.17.13-d6f555d2/downloads/beats/elastic-agent/elastic-agent-7.17.13-windows-x86_64.zip
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 9.97%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 17.77%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 24.18%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 30.77%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 38.99%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 51.99%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 64.59%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 75.38%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 83.18%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 93.29%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:255: Downloading artifact progress 100.00%
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:222: Completed downloading artifact from https://staging.elastic.co/7.17.13-d6f555d2/downloads/beats/elastic-agent/elastic-agent-7.17.13-windows-x86_64.zip
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:176: Downloading artifact from https://staging.elastic.co/7.17.13-d6f555d2/downloads/beats/elastic-agent/elastic-agent-7.17.13-windows-x86_64.zip.sha512
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fetcher_artifact.go:222: Completed downloading artifact from https://staging.elastic.co/7.17.13-d6f555d2/downloads/beats/elastic-agent/elastic-agent-7.17.13-windows-x86_64.zip.sha512
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:221: Extracting artifact elastic-agent-7.17.13-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUpgrade_7.17.13_to_8.11.0-SNAPSHOT3632557646\001
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:234: Completed extraction of artifact elastic-agent-7.17.13-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUpgrade_7.17.13_to_8.11.0-SNAPSHOT3632557646\001
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:540: Components were not modified from the fetched artifact
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture_install.go:90: [test TestStandaloneUpgrade/Upgrade_7.17.13_to_8.11.0-SNAPSHOT] Inside fixture install function
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUpgrade_7.17.13_to_8.11.0-SNAPSHOT3632557646\001\elastic-agent-7.17.13-windows-x86_64\elastic-agent.exe install --force]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:474: Agent installation output: "Elastic Agent has been successfully installed.\n"
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe status --output json]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:590: current agent state: {Status:V1_HEALTHY Message: Applications:[]}
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe version --yaml]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:603: current agent version: {Binary:7.17.13 (build: de195afbaa6ed4f7823e91e5544927b84275103b at 2023-08-31 22:03:50 +0000 UTC) Daemon:7.17.13 (build: de195afbaa6ed4f7823e91e5544927b84275103b at 2023-08-31 22:03:50 +0000 UTC)}
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:487: Upgrading from version "7.17.13" to version "8.11.0-SNAPSHOT"
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe upgrade 8.11.0-SNAPSHOT --skip-verify]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe status --output yaml]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:530: error getting the agent state: exit status 1
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe status --output yaml]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:530: error getting the agent state: exit status 1
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe status --output yaml]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:530: current agent state: {Info:{ID:c2870809-3718-4ccc-b334-49b07f424cd3 Version:8.11.0 Commit:b1d2e6b04062b8572718e583590afe678579bf9d BuildTime:2023-09-21 15:18:03 +0000 UTC Snapshot:true} State:HEALTHY Message:Running Components:[] FleetState:STOPPED FleetMessage:Not enrolled into Fleet}
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:533: Version "7.17.13" is too old for a quick update marker check, skipping...
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture_install.go:114: [test TestStandaloneUpgrade/Upgrade_7.17.13_to_8.11.0-SNAPSHOT] Inside fixture cleanup function
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture.go:365: >> running agent with: [C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall --force]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture_install.go:174: fixture.Install Cleanup: uninstall failed: process running: PID: 5572 [C:\Program Files\Elastic\Agent\data\elastic-agent-de195a\elastic-agent watch --path.config C:\Program Files\Elastic\Agent --path.home C:\Program Files\Elastic\Agent]
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): fixture_install.go:179:
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): Error Trace:        C:/Users/windows/agent/pkg/testing/fixture_install.go:179
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): C:/Program Files/Go/src/testing/testing.go:1150
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): C:/Program Files/Go/src/testing/testing.go:1328
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): C:/Program Files/Go/src/testing/testing.go:1570
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): Error:              Received unexpected error:
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): error running uninstall command: exit status 1
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): Test:               TestStandaloneUpgrade/Upgrade_7.17.13_to_8.11.0-SNAPSHOT
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): Messages:           uninstalling agent failed. Output: "Error: failed to remove installation directory (C:\\Program Files\\Elastic\\Agent): timed out while removing \"C:\\\\Program Files\\\\Elastic\\\\Agent\". Last error: remove C:\\Program Files\\Elastic\\Agent\\watcher.lock: The process cannot access the file because it is being used by another process.\nFor help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.11/fleet-troubleshooting.html\n"
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): === FAIL: testing/integration TestStandaloneUpgrade (325.47s)
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): upgrade_test.go:189: Skipping version "8.11.0-SNAPSHOT" since it's newer or equal to version after upgrade "8.11.0-SNAPSHOT"
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stdout): DONE 4 tests, 2 failures in 392.055s
>>> (windows-amd64-2022-teststandaloneupgrade) Test output (sudo) (stderr): Error: go test returned a non-zero value: exit status 1
>>> (windows-amd64-2022-teststandaloneupgrade) sudo tests failed: Process exited with status 1
```

The interesting part is this line (I removed the prefix), which is after the upgrade has completed.

`upgrade_test.go:530: current agent state: {Info:{ID:c2870809-3718-4ccc-b334-49b07f424cd3 Version:8.11.0 Commit:b1d2e6b04062b8572718e583590afe678579bf9d BuildTime:2023-09-21 15:18:03 +0000 UTC Snapshot:true} State:HEALTHY Message:Running Components:[] FleetState:STOPPED FleetMessage:Not enrolled into Fleet}`

The `Commit` and `BuildTime` does not match by build that was placed on the host under test (aka. the instance):

```
windows@OGC-WINDOWS-AMD C:\Users\windows\elastic-agent-8.11.0-SNAPSHOT-windows-x86_64>.\elastic-agent.exe version --binary-only --yaml       
binary:
  version: 8.11.0
  commit: 14d017359f23293e5a44e6bfa962668198defe9a
  build_time: 2023-09-22T00:46:57Z
  snapshot: true
```

This means that the test is not even really testing the build of Elastic Agent we are expecting and that is the reason that the watcher is not being killed. I would not see the benefit of https://github.com/elastic/elastic-agent/pull/3384 until a new snapshot is built and published.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

This refactors and fixes all upgrade integration tests. This provides a unified path for the tests to follow for testing upgrade. Includes code to make the upgrades faster, and allows downgrades to work. Includes fixes for upgrade tests that where skipped because they where flaky and enables the retry upgrade test on Windows.

## Why is it important?

Ensures that all upgrade tests are working properly so we can catch real errors instead of fighting the CI.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `./changelog/fragments` using the [changelog tool](https://github.com/elastic/elastic-agent#changelog)~~
- [x] I have added an integration test or an E2E test

## How to test this PR locally

`mage integration:test`

## Related issues

- Closes #3155
- Closes #3461

### CODE REVIEW

**Comment by blakerouse** [comment]
This has a replace present until this PR is merged and new elastic-agent-libs is released - https://github.com/elastic/elastic-agent-libs/pull/152

**Comment by cmacknz** [comment]
`testing/**` needs to be added to the SonarQube exclusion list to silence the coverage failure.

https://github.com/elastic/elastic-agent/blob/main/sonar-project.properties

File: pkg/testing/fixture.go [hunk 1]
```diff
@@ -456,6 +456,23 @@ func (f *Fixture) ExecInspect(ctx context.Context, opts ...process.CmdOption) (A
 	return inspect, err
 }
 
+// ExecVersion executes to version subcommand on the prepared Elastic Agent binary
+// with '--binary-only'. It returns the parsed YAML output.
```
Comment (cmacknz) [inline pkg/testing/fixture.go:460]:
```suggestion
// ExecVersion executes the version subcommand on the prepared Elastic Agent binary
// with '--binary-only'. It returns the parsed YAML output.
```

File: testing/upgradetest/upgrader.go [hunk 2]
```diff
@@ -0,0 +1,361 @@
...
+	if upgradeOpts.preUpgradeHook != nil {
+		if err := upgradeOpts.preUpgradeHook(); err != nil {
+			return fmt.Errorf("pre upgrade hook failed: %w", err)
+		}
+	}
+
+	logger.Logf("Upgrading from version %q to version %q", startParsedVersion, endVersionInfo.Binary.String())
+
+	// always pull from local path (as fixture is required)
+	// doesn't mean
```
Comment (cmacknz) [inline testing/upgradetest/upgrader.go:193]: > // doesn't mean

Doesn't mean what?

File: testing/upgradetest/watcher.go [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+agent.upgradetest.watcher:
+  grace_period: 1m
+  error_check.interval: 15s
+  crash_check.interval: 15s
+`
+
+// ConfigureFastWatcher writes an Elastic Agent configuration that
+// adjusts the watcher to be faster.
+func ConfigureFastWatcher(ctx context.Context, f *atesting.Fixture) error {
+	return f.Configure(ctx, []byte(FastWatcherCfg))
```
Comment (cmacknz) [inline testing/upgradetest/watcher.go:28]: Does this work if the agent is Fleet managed?

File: testing/upgradetest/watcher.go [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+				return nil
+			}
+			// still watcher running after `killTimeout` we consider it
+			// has been long enough. Just kill the watcher because it should
+			// have completed with in the `killTimeout` being it didn't means
+			// that the running Elastic Agent version does respect `ConfigureFastWatcher`.
+			for _, pid := range pids {
+				proc, err := os.FindProcess(pid)
+				if err == nil {
+					_ = proc.Kill()
```
Comment (cmacknz) [inline testing/upgradetest/watcher.go:100]: Should we fail the test if we need to do this in a version of the agent that has the watcher killed as part of the uninstall?

File: testing/upgradetest/watcher.go (hunk 3 above)
Comment (cmacknz) [reply testing/upgradetest/watcher.go:28]: I think from previous testing it doesn't, since the only config the agent respects is the one from Fleet. We should note this here to avoid people using this where it doesn't help (unless I'm wrong about it).

File: pkg/testing/fetcher_artifact.go [hunk 5]
```diff
@@ -68,7 +68,9 @@ func (f *artifactFetcher) Fetch(ctx context.Context, operatingSystem string, arc
 	}
 	preVersion := version
 	if uri == "" {
-		version = fmt.Sprintf("%s-SNAPSHOT", version)
+		if !strings.HasSuffix(version, "-SNAPSHOT") {
+			version += "-SNAPSHOT"
+		}
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/testing/fetcher_artifact.go:73]: We actually did force it there. What didn't work was when you passed in a version string that had the suffix `-SNAPSHOT` it would append it again, which resulted in `-SNAPSHOT-SNAPSHOT` which was incorrect.

File: testing/upgradetest/watcher.go (hunk 3 above)
Comment (blakerouse) [reply testing/upgradetest/watcher.go:28]: I think your correct, I will add a note.

File: testing/upgradetest/watcher.go (hunk 4 above)
Comment (blakerouse) [reply testing/upgradetest/watcher.go:100]: I will add a specific test that checks for that case. I prefer to keep this here always just to ensure that it doesn't cause other unrelated tests to break. That way its clear why that one test fails.

File: testing/upgradetest/upgrader.go (hunk 2 above)
Comment (blakerouse) [reply testing/upgradetest/upgrader.go:193]: both comments are wrong, will remove it

File: testing/integration/upgrade_broken_package_test.go [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	// Start at the build version as we want to test the retry
+	// logic that is in the build.
+	startFixture, err := define.NewFixture(t, define.Version())
+	require.NoError(t, err)
+
+	// Upgrade to an old build, see `BackwardTwoMinors` for why.
+	upgradeToVersion, err := upgradetest.BackwardTwoMinors(define.Version())
```
Comment (pchila) [inline testing/integration/upgrade_broken_package_test.go:41]: Why do we use BackwardTwoMinors here? 
We already know that GetPreviousMinor() makes assumptions about the version numbers (set the patch version to 0, return a fixed version for 7.x), why not taking the version from artifact API as it was before the refactor?

File: testing/integration/upgrade_fleet_test.go [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+		atesting.WithFetcher(atesting.ArtifactFetcher()),
+	)
+	require.NoError(t, err)
+	err = endFixture.Prepare(ctx)
+	require.NoError(t, err)
+	endVersionInfo, err := endFixture.ExecVersion(ctx)
+	require.NoError(t, err)
+	if startVersionInfo.Binary.Commit == endVersionInfo.Binary.Commit {
+		t.Skipf("Build under test is the same as the build from the artifacts repository (commit: %s)", startVersionInfo.Binary.Commit)
+	}
```
Comment (pchila) [inline testing/integration/upgrade_fleet_test.go:69]: Heads up: this does not work for repackaged agents (different agent package versions will have the same commit for the agent binary but different components).
For the moment, it will work

File: testing/integration/upgrade_fleet_test.go [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+
+	t.Logf("Testing Elastic Agent upgrade from %s to %s with Fleet...", define.Version(), endVersionInfo.Binary.String())
+
+	// start fixture gets the agent configured to use a faster watcher
+	err = upgradetest.ConfigureFastWatcher(ctx, startFixture)
+	require.NoError(t, err)
```
Comment (pchila) [inline testing/integration/upgrade_fleet_test.go:75]: Does this work for Fleet managed agents now?

File: testing/integration/upgrade_downgrade_test.go [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+		upgradeToVersion,
+		atesting.WithFetcher(atesting.ArtifactFetcher()),
+	)
+	require.NoError(t, err)
+
+	t.Logf("Testing Elastic Agent upgrade from %s to %s...", define.Version(), upgradeToVersion)
+
+	err = upgradetest.PerformUpgrade(ctx, startFixture, endFixture, t)
+	assert.NoError(t, err)
+}
```
Comment (pchila) [inline testing/integration/upgrade_downgrade_test.go:49]: This tests was testing the ability to upgrade/downgrade to a specific snapshot build before the refactor... I don't think it's doing that now...

File: testing/upgradetest/upgrader.go [hunk 10]
```diff
@@ -0,0 +1,358 @@
...
+		}
+	}
+
+	logger.Logf("Upgrading from version %q to version %q", startParsedVersion, endVersionInfo.Binary.String())
+
+	upgradeCmdArgs := []string{"upgrade", endVersionInfo.Binary.String()}
+	if upgradeOpts.sourceURI != "" {
+		// specific ---source-uri
+		upgradeCmdArgs = append(upgradeCmdArgs, "--source-uri", upgradeOpts.sourceURI)
+	} else if upgradeOpts.customPgp == nil {
```
Comment (pchila) [inline testing/upgradetest/upgrader.go:196]: Not sure why this is an `else if` clause instead of being a simple `if`... 
Are we saying that this function will ignore PGP options if a custom `source-uri` is provided ? 
Shouldn't that decision be left to the test calling this function with the appropriate options?

**Review by pchila — CHANGES_REQUESTED** [review]
There is at least 1 test that has changed meaning in the refactor: ` TestStandaloneDowngradeToPreviousSnapshotBuild` is supposed to test the upgrade in form of `elastic-agent upgrade x.y.z-SNAPSHOT+<buildid>` and from what I see it doesn't do that anymore but it just performs a downgrade 2 minors back

There are a few other comments on other parts of the code but another element that pops is that we use `version.GetPreviousMinor()` more even if we know that it has some limitation as it tries to guess what the previous minor would be.
Maybe you want to take a look at https://github.com/elastic/elastic-agent/pull/3458 (which I imagine is now replaced by this) for a possible alternative of selecting previous versions

File: testing/integration/upgrade_broken_package_test.go (hunk 6 above)
Comment (blakerouse) [reply testing/integration/upgrade_broken_package_test.go:41]: Almost all the tests where written completely different, but basically doing the same thing. I tried my best to merge them onto a path that is very similar and easy to follow. To me read ability is the most important thing, because if I cannot open the test and easily read and understand what is going on then its useless.

I tried my best to align the tests in a common pattern. If I have change the meaning of what the test is testing please let me know I will fix it.

Does this change the meaning of this test?

For why we use `BackwardTwoMinors` check the docstring on that function. It explains it.

File: testing/integration/upgrade_fleet_test.go (hunk 7 above)
Comment (blakerouse) [reply testing/integration/upgrade_fleet_test.go:69]: How would that ever be the case for a PR? A PR should always result in a new build, and as a developer testing from your laptop it should always be from a custom build as well.

I don't see a reality where that is not true.

File: testing/integration/upgrade_fleet_test.go (hunk 8 above)
Comment (blakerouse) [reply testing/integration/upgrade_fleet_test.go:75]: No it doesn't. I will remove this line.

File: testing/integration/upgrade_downgrade_test.go (hunk 9 above)
Comment (blakerouse) [reply testing/integration/upgrade_downgrade_test.go:49]: Sadly the title of the test did not make that clear. Most test where so hard to follow and read I could not fully understand what the test was doing.

If you can provide me some more detail on what this test is really doing, I can fix it.

File: testing/upgradetest/upgrader.go (hunk 10 above)
Comment (blakerouse) [reply testing/upgradetest/upgrader.go:196]: True. I will update.

Comment (blakerouse) [reply testing/upgradetest/upgrader.go]: Updated.

File: testing/upgradetest/watcher.go (hunk 4 above)
Comment (blakerouse) [reply testing/upgradetest/watcher.go:104]: I added `TestStandaloneUpgradeUninstallKillWatcher` for testing this specific behavior.

**Comment by blakerouse** [comment]
The modreplace has been removed but the lint is still failing, not clear as to why.

File: testing/integration/upgrade_downgrade_test.go (hunk 9 above)
Comment (pchila) [reply testing/integration/upgrade_downgrade_test.go:49]: The original test would select the second-to-last (penultimate) snapshot build from Artifact API, use the buildid to issue a `elastic-agent upgrade x.y.z-SNAPSHOT+<buildid>` in order to distinguish the result from a regular `elastic-agent upgrade x.y.z-SNAPSHOT`

It would then proceed to verify that the commit of the upgraded agent would correspond to the specific build selected, proving that the feature works.

There was also an ugly workaround because the commit hash reported by Artifact API is not always the correct one, but with your approach of creating an endFixture we may sidestep that one if the artifactFetcher is able to pinpoint a specific snapshot build.

File: testing/integration/upgrade_fleet_test.go (hunk 7 above)
Comment (pchila) [reply testing/integration/upgrade_fleet_test.go:69]: If this is only for PRs run on CI it will work (because the merge commit is always different from whatever we may download from Artifact API)
In the case of a dev testing, it can happen once https://github.com/elastic/elastic-agent/issues/2579 and https://github.com/elastic/elastic-agent/issues/2780 are implemented (somebody is packaging uncommitted stuff on top of main and use a different AGENT_PACKAGE_VERSION value)

I agree it's not an immediate concern and the local case can be solved by a simple commit on whatever branch

File: testing/integration/upgrade_broken_package_test.go (hunk 6 above)
Comment (pchila) [reply testing/integration/upgrade_broken_package_test.go:41]: It doesn't change the meaning of the test, I am not that comfortable with us not using the latest patch for a given <major>.<minor>

File: testing/upgradetest/upgrader.go [hunk 11]
```diff
@@ -0,0 +1,365 @@
...
+		}
+
+		if len(upgradeOpts.customPgp.PGPUri) > 0 {
+			upgradeCmdArgs = append(upgradeCmdArgs, "--pgp-uri", upgradeOpts.customPgp.PGPUri)
+		}
+
+		if len(upgradeOpts.customPgp.PGPPath) > 0 {
+			upgradeCmdArgs = append(upgradeCmdArgs, "--pgp-path", upgradeOpts.customPgp.PGPPath)
+		}
+	}
```
Comment (pchila) [inline testing/upgradetest/upgrader.go:223]: This still doesn't look great (I know it comes from the very specific logic of upgrade tests with PGP).
I would be tempted to separate the customPGP != nil and customPGP == nil at cost of a little duplication for the sourceURI logic but I leave that choice up to you

File: testing/integration/upgrade_broken_package_test.go (hunk 6 above)
Comment (blakerouse) [reply testing/integration/upgrade_broken_package_test.go:41]: Are you saying that you want it to only go down a single version? I could possibly switch all to that way, and then possibly only go down 2 in the case the last 1 doesn't exist.

File: testing/integration/upgrade_fleet_test.go (hunk 7 above)
Comment (blakerouse) [reply testing/integration/upgrade_fleet_test.go:69]: What about checking both the versions and the commit in the same compare, would that fix the compare when AGENT_PACKAGE_VERSION is set?

File: testing/integration/upgrade_downgrade_test.go (hunk 9 above)
Comment (blakerouse) [reply testing/integration/upgrade_downgrade_test.go:49]: Okay I will go back and look at the original test and see if there is a clean and simple way of finding the `<buildid>`. The artifact fetcher in the testing library might need to be updated to use that `+<buildid>` as well to pull the correct build.

File: testing/upgradetest/upgrader.go (hunk 11 above)
Comment (blakerouse) [reply testing/upgradetest/upgrader.go:223]: I will have to go with a `*string` for the `sourceURI` to use that logic. That means the GPG tests would need to set `WithSourceURI("")` that way it doesn't use the local `sourceURI`. I can change to that way of operation.

Comment (blakerouse) [reply testing/upgradetest/upgrader.go]: I changed to to how I described. See if you like that way better.

File: testing/integration/upgrade_broken_package_test.go (hunk 6 above)
Comment (pchila) [reply testing/integration/upgrade_broken_package_test.go:41]: Note: this is not blocking for the merge

It's not the number of version we downgrade to: in this specific case it doesn't really matter how far back we go, we just want to test that even with a broken package version we can upgrade to something else.

The thing making me uncomfortable is that from `8.11.0-SNAPSHOT` we are going back to `8.10.0` or `8.9.0` instead of `8.10.3` or `8.9.2` because we cannot guess how patch versions a certain major.minor combination has.

As a personal preference I favored using [artifact api version list](https://artifacts-api.elastic.co/v1/versions) to search for a previous version instead of computing a likely value but it's true that unless we have serious bugs on our `x.y.0` versions this won't break any time soon for 8.x

7.x may break when 7.17.10 will no longer be available through artifact api (have a look at GetPreviousMinor() code)
9.x if and when it will land will need also some special handling in GetPreviousMinor()

As long as we use this to go a couple of minors  back from the latest 8.x we will not fall into those cases so it comes down to preference.

File: testing/integration/upgrade_fleet_test.go (hunk 7 above)
Comment (pchila) [reply testing/integration/upgrade_fleet_test.go]: Yep that would work nicely :+1:

File: testing/upgradetest/upgrader.go [hunk 12]
```diff
@@ -190,25 +190,20 @@ func PerformUpgrade(
...
+			return fmt.Errorf("failed to get end agent source package path: %w", err)
 		}
+		sourceURI := "file://" + filepath.Dir(srcPkg)
+		upgradeCmdArgs = append(upgradeCmdArgs, "--source-uri", sourceURI)
+	} else if *upgradeOpts.sourceURI != "" {
+		// specific ---source-uri
+		upgradeCmdArgs = append(upgradeCmdArgs, "--source-uri", *upgradeOpts.sourceURI)
+	}
 
+	if upgradeOpts.customPgp != nil {
```
Comment (pchila) [inline testing/upgradetest/upgrader.go:206]: Much easier to follow (at least for me). Thank you :+1:

File: testing/upgradetest/upgrader.go (hunk 11 above)
Comment (pchila) [reply testing/upgradetest/upgrader.go]: Looks good now! Thanks! :+1:

**Comment by ycombinator** [comment]
The conflicts are due to me merging #3085, introducing a new upgrade integration test, `TestStandaloneUpgradeFailsRestart`. @blake.rouse I'll make a PR to thiw refactoring PR fixing up the test I just added to bring it in line with your improvements.  I just wanted to get #3085 in since it's been open for two months!

**Comment by blakerouse** [comment]
@ycombinator Don't worry about it. I have fixed the conflict and updated the test to use the new patterns.

File: testing/integration/upgrade_downgrade_test.go (hunk 9 above)
Comment (blakerouse) [reply testing/integration/upgrade_downgrade_test.go]: I have updated the test so it is testing what used to be tested. Sorry about that.

I had to add support for the testing framework to work with build ids in the version name as well.

File: testing/integration/upgrade_broken_package_test.go (hunk 6 above)
Comment (blakerouse) [reply testing/integration/upgrade_broken_package_test.go]: I have updated the code to take the same idea you had from your other PR and use it in this PR. Now it uses the artifacts API to find the previous version that has a snapshot build and uses that for the test.

**Comment by blakerouse** [comment]
@pchila I believe this is ready for a final review. I have fixed all conflicts and issues you pointed out.

**Review by pchila — CHANGES_REQUESTED** [review]
The  `TestStandaloneDowngradeToSpecificSnapshotBuild` looks better but we need to select the penultimate build to have a result that is noticeably different from a normal upgrade to a snapshot version

File: testing/integration/upgrade_downgrade_test.go [hunk 13]
```diff
@@ -8,41 +8,74 @@ package integration
...
+	aac := tools.NewArtifactAPIClient()
+	latestSnapshotVersion, err := tools.GetLatestSnapshotVersion(ctx, t, aac)
+	require.NoError(t, err)
+
+	// get all the builds of the snapshot version (need to pass x.y.z-SNAPSHOT format)
+	builds, err := aac.GetBuildsForVersion(ctx, latestSnapshotVersion.VersionWithPrerelease())
+	require.NoError(t, err)
+	if len(builds.Builds) == 0 {
+		t.Skipf("no SNAPSHOT's exists for version %s", latestSnapshotVersion.VersionWithPrerelease())
+	}
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply testing/integration/upgrade_downgrade_test.go:51]: I never understood why the test needed 2 builds. I get it now. Next time more comments on why things are done the way they where in the test would be helpful. I just keep looking at it thinking why does it need 2? Its only upgrading to 1 build.

File: testing/integration/upgrade_downgrade_test.go [hunk 14]
```diff
@@ -8,41 +8,74 @@ package integration
...
+
+	// find the specific build to use for the test
+	upgradeVersionString := builds.Builds[0]
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply testing/integration/upgrade_downgrade_test.go]: Done.

File: testing/integration/upgrade_downgrade_test.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (blakerouse) [reply testing/integration/upgrade_downgrade_test.go]: Done.

File: pkg/testing/fetcher_artifact.go [hunk 15]
```diff
@@ -168,13 +170,35 @@ func findURI(ctx context.Context, doer httpDoer, version string) (string, error)
...
+	return split[0], split[1]
+}
+
+func stripSnapshot(version string) string {
+	if strings.HasSuffix(version, "-SNAPSHOT") {
+		return strings.TrimSuffix(version, "-SNAPSHOT")
+	}
+	return version
+}
+
```
[the remark this answers is not in the document]
Comment (blakerouse) [reply pkg/testing/fetcher_artifact.go:201]: Its simple and this module doesn't import that module at the moment, so I am just going to keep it here.

**Comment by blakerouse** [comment]
@pchila I have fixed that test and fixed the conflicts.

@ycombinator I have fixed the two tests in conflict if you want to give them a look over. Both where new tests that you added.

File: testing/integration/upgrade_standalone_inprogress.go [hunk 16]
```diff
@@ -0,0 +1,97 @@
...
+		require.NoError(t, err)
+	}
+
+	// upgrade has occurred and the watcher is running
+
+	// wait for the agent to be healthy and correct version
+	// before trying to perform another upgrade
+	err = upgradetest.WaitHealthyAndVersion(ctx, startFixture, endVersionInfo.Binary, 2*time.Minute, 10*time.Second, t)
+	if err != nil {
+		// agent never got healthy, but we need to ensure the watcher is stopped before continuing
```
Comment (ycombinator) [inline testing/integration/upgrade_standalone_inprogress.go:72]: It wasn't immediately obvious to me _why_ the watcher was being killed here.  I think it's so it doesn't interfere with _other_ tests (as opposed to having anything to do with continuing on in this test, since this test should now fail due to the `require.NoError(t, err)` on line 79), right?  Could you clarify that in the code comment here please?

File: testing/integration/upgrade_standalone_inprogress.go [hunk 17]
```diff
@@ -0,0 +1,97 @@
...
+
+	// trigger another upgrade that should fail because the current watcher
+	// is still running and another upgrade can be performed until it is complete
+	upgradeCmdArgs := []string{"upgrade", endVersionInfo.Binary.String()}
+	upgradeOutput, err := startFixture.Exec(ctx, upgradeCmdArgs)
+	require.NotNil(t, err)
+	require.Contains(t, string(upgradeOutput), "an upgrade is already in progress; please try again later.")
+
+	// killTimeout is greater than timeout as the watcher should have been
+	// stopped on its own, and we don't want this test to hide that fact
```
Comment (ycombinator) [inline testing/integration/upgrade_standalone_inprogress.go:89]: 👍

File: testing/integration/upgrade_rollback_test.go [hunk 18]
```diff
@@ -0,0 +1,195 @@
...
+	define.Require(t, define.Requirements{
+		Local: false, // requires Agent installation
+		Sudo:  true,  // requires Agent installation
+	})
+
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	// Start at the build version as we want to test the retry
+	// logic that is in the build.
```
Comment (ycombinator) [inline testing/integration/upgrade_rollback_test.go:130]: I think this comment is not relevant to this test?

File: testing/integration/upgrade_rollback_test.go [hunk 19]
```diff
@@ -0,0 +1,195 @@
...
+		t.Logf("Restarting Agent via service to simulate crashing")
+		err = install.RestartService(topPath)
+		require.NoError(t, err)
+	}
+
+	// wait for the agent to be healthy and back at the start version
+	err = upgradetest.WaitHealthyAndVersion(ctx, startFixture, startVersionInfo.Binary, 10*time.Minute, 10*time.Second, t)
+	if err != nil {
+		// agent never got healthy, but we need to ensure the watcher is stopped before continuing
+		// this kills the watcher instantly and waits for it to be gone before continuing
```
Comment (ycombinator) [inline testing/integration/upgrade_rollback_test.go:177]: Same comment as https://github.com/elastic/elastic-agent/pull/3477/files#r1341596538 about the "continuing" being unclear.

**Comment by ycombinator** [comment]
> @ycombinator I have fixed the two tests in conflict if you want to give them a look over. Both where new tests that you added.

@blakerouse I reviewed the two tests. The logic in both looks good and even improved towards the end of the tests! I left some feedback about clarifying comments, that's all.

File: testing/integration/upgrade_standalone_inprogress.go (hunk 16 above)
Comment (blakerouse) [reply testing/integration/upgrade_standalone_inprogress.go:72]: I added more to the comment to make this clear. The reason you gave is the correct.

File: testing/integration/upgrade_rollback_test.go (hunk 18 above)
Comment (blakerouse) [reply testing/integration/upgrade_rollback_test.go:130]: It is relevant.

File: pkg/testing/fetcher_artifact.go [hunk 20]
```diff
@@ -68,6 +68,7 @@ func (f *artifactFetcher) Fetch(ctx context.Context, operatingSystem string, arc
 		uri, prevErr = findURI(ctx, f.doer, version)
 	}
 	preVersion := version
+	version, _ = splitBuildID(version)
 	if uri == "" {
 		if !strings.HasSuffix(version, "-SNAPSHOT") {
```
Comment (pchila) [inline pkg/testing/fetcher_artifact.go:73]: If we have a snapshot with a buildId we need to prepare the uri in the format of x.y.z-<buildid>, for example
`https://snapshots.elastic.co/8.11.0-2574a657/downloads/beats/elastic-agent/elastic-agent-8.11.0-SNAPSHOT-linux-x86_64.tar.gz` (we can see the build details from https://artifacts-api.elastic.co/v1/versions/8.11.0-SNAPSHOT/builds/8.11.0-2574a657 )

**Comment by blakerouse** [comment]
@pchila You are correct it was not, my most recent commit fixed it. See here - https://github.com/elastic/elastic-agent/pull/3477/commits/967969f1d2e640b923160d5e666d690821c43871
